### ISSUE TITLE
Update link to new tutorial in the website

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#104]
Current [GrimoireLab website](https://chaoss.github.io/grimoirelab) docs section links to [old/legacy Gitbook based GrimoireLab tutorial](https://grimoirelab.gitbooks.io/tutorial/content/).
It should link to [new tutorial site](https://chaoss.github.io/grimoirelab-tutorial/)

**Comment by jgbarah** [comment]
Hopefully fixed in #112 and #113.
