### ISSUE TITLE
Adding different data sources with Dockerhub installation

### ISSUE THREAD

**Issue by aravindputrevu** [chaoss/grimoirelab#105]
Hi,

Thanks GrimoireLab for creating this tool. I used it but, I find it difficult to add data sources and see the dashboard for those org's or repo's. This is particularly with DockerHub. 

Could anyone guide me to right resource?

**Comment by aravindputrevu** [comment]
Thank you I figured it out. 👍

**Comment by jgbarah** [comment]
Thanks a lot, @aravindputrevu.

If you have some time, would you mind sharing the experience by writing in this ticket how you added those data sources, and your experience with that? I'm about to write that part in the GrimoireLab Tutorial, and it would be very useful for me to have the view of a person not in the GrimoireLab core team.

**Comment by aravindputrevu** [comment]
@jgbarah Here you go...

I used the docker hub to spin up GrimoireLab. I opened localhost:5601 and found that it is pulling data from GrimoireLab GH repo's. I logged into the container and checked that at the "/" there is a endpoint.sh script which starts the services. projects.cfg and projects.json which has what GH repo's to pull. So, I changed to add my repo's and then I could see my data. 

There is **"0"** documentation about this. But that is fine. 

Happy to explain more if needed. :)

**Comment by jgbarah** [comment]
Thanks a lot! I had understood that you were tracking data for DockerHub images (which is one of  the data sources supported by GrimoireLab), not that you were using the GrimoireLab docker image and couldn't find info to configure it.

If this is the case, are you aware of the document [Docker images for GrimoireLab](https://github.com/chaoss/grimoirelab/blob/master/docker/README.md) and the chapter [Mordred in a container](https://chaoss.github.io/grimoirelab-tutorial/mordred/mordred-in-a-container.html) in the [GrimoireLab tutorial](https://chaoss.github.io/grimoirelab-tutorial/mordred/mordred-in-a-container.html)? Just to know if there is not enough information to get to these documents, or that these documents are not good enough for what you needed.
