### ISSUE TITLE
Visualising the Metrics

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/grimoirelab#106]
As per the discussion with @jgbarah, apart from creating pdfs of analysis of the projects using Manuscripts, we can look at other methods to visualise the metrics.
Some of them being:
- HTML pages (One for each Metric describing the activity metrics under that Metric).
- Interactive Notebooks by embedding D3.js code in them so that the users can analyse the Metrics more throughly. Using [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) for that.
- Using [Vega](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md) to visualise the Metrics.

This ticket can serve as a discussion point for how the Metrics can be further visualised.

**Comment by jgbarah** [comment]
Thanks, @aswanipranjal. WRT to the combination of Pandas and Vega, I would explore [Altair](https://altair-viz.github.io/) and [pdvega](https://jakevdp.github.io/pdvega/). You can have a summary of how they work (although for Altair, that corresponds to an old version) in [Introduction to Data Visualization with Altair ](http://pbpython.com/altair-intro.html) and [Intro to pdvega - Plotting for Pandas using Vega-Lite](http://pbpython.com/pdvega.html).

**Comment by aswanipranjal** [comment]
Long time no update!!

So, I've been experimenting with Plotly and Altair. Both are awesome libraries to get interactive visualizations but both these libraries do not provide static image files so easily. 

Plotly DOESNOT let the users export to any image format offline. There are twisted ways to get the screenshot of the visualisation [using selenium, PhantomJS and such](https://duckduckgo.com/?q=plotly+offline+export+to+png&atb=v122-2o_&ia=qa), but it is too much of a hassle.

In a similar fashion, Altair also does not provide simple exportation to image formats so easily. We will have to [download selenium and chrome/gecko drivers for Altair](https://altair-viz.github.io/user_guide/saving_charts.html?highlight=png).

The way I see it, we can go this way:
- Create interactive visualizations for Notebooks using Plotly and Altair
- Create static charts and graphs using Matplotlib and Pandas visualisation functionalities.

Thoughts? @jgbarah @valeriocos ?

**Comment by jgbarah** [comment]
@aswanipranjal I think we already discussed this during the GSoC period... Do you think we could close?

**Comment by jgbarah** [comment]
Thx!
