### ISSUE TITLE
Setting up the infrastructure for tracking my GSoC project

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/grimoirelab#108]
This issue is about the details of how my GSoC project will be tracked and how updates will be provided on the progress of the project.
- This is the [experimentation repository](https://github.com/aswanipranjal/gsoc-manuscripts). This will contain all the notebooks and libraries developed for the project.
- It also contains a [document](https://github.com/aswanipranjal/gsoc-manuscripts/blob/master/Readme.md) which contains information about the Issues and PRs that have been created.
- This [blog](https://aswanipranjal.github.io/posts) will contain detailed information about what I did that week.

Other information will be updated on the [repo](https://github.com/aswanipranjal/gsoc-manuscripts) or in this issue. Stay tuned for more!

**Comment by jgbarah** [comment]
I think we can close this. Thanks, @aswanipranjal
