### ISSUE TITLE
run in docker on windows

### ISSUE THREAD

**Issue by tkowalczyk** [chaoss/grimoirelab#111]
Hi,

Please tell me how to run this project in docker on windows? I am trying this as follow:
`docker run -p 127.0.0.1:5601:5601 -v credentials.cfg:/override.cfg -t grimoirelab/full`
but getting error:
`Error response from daemon: readdirent: not a directory.`

I am doing it as admin and the `credentials.cfg` file is also created.

**Comment by jgbarah** [comment]
@tkowalczyk, could you run the stuff? (I'm sorry, I missed the notification of you opening this issue).

**Comment by tkowalczyk** [comment]
Yeah, I run it on Windows so had to define paths in other way:

`docker run -p 127.0.0.1:5601:5601 -p 127.0.0.1:9200:9200 -v D:\test\credentials.cfg:/override.cfg -v D:\test\projects.json:/projects.json -t grimoirelab/full`

**Comment by jgbarah** [comment]
Oh, I see. I'll add a note to the tutorial about that! Thanks for the heads-up.
