### ISSUE TITLE
[releases] 18.06-01 includes a package with no new version

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab#118]
The commit for SirMordred in 18.06-01 is: e5bc96aeb9a6798e427ed104e92783d1bbee708c.

However, this commit does not include a new version number for the package.

Please, fix this in 18.06-02, so that packages and container images can be produced...

**Comment by acs** [comment]
Fixed in: https://github.com/chaoss/grimoirelab-sirmordred/commit/c015ce9d15e1beb0410bf3204d163edd71b9a7c9

Thanks for the heads up @jgbarah !
