### ISSUE TITLE
Version check failed when building 18.06-03 packages

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab#127]
When running the checks before building packages:

* Failed version check for kidash
* Failed version check for grimoirelab-panels

@acs can you please have a look at this?

**Comment by acs** [comment]
For grimoirelab-panels we are using the kibana5 maintenance branch. Hmmm, probably we should add versioning there. Is that enough?

I will check also the kidash and create a hot fix. Thanks @jgbarah for the review!

**Comment by acs** [comment]
> In any case, why we need a specific kibana5 branch? 

In https://github.com/chaoss/grimoirelab-sigils their policy is to create a maintenance branch for each major Kibana release. Until now:

* Kibana 4: https://github.com/chaoss/grimoirelab-sigils/tree/kibana4-maintenance
* KIbana 5: https://github.com/chaoss/grimoirelab-sigils/tree/kibana5-maintenance

And master panels are the ones working with the latest version of KIbana supported in GrimoireLab, now KIbana 6.

> If needed, we could specify to kidash which dashboards to upload (from one of two directories, for example). In particular, for the coummunity docker images, we're using ES/KB 6.x, so we need those panels...

During the next two weeks all the KB 6.x must be available. In any case,  think that I am going to publish the release for kibana 6.x as you suggested, but in Grimoire releases, I will use the kibana5 branch until we have completed the migration to KB 6.x in Bitergia. Dos it sounds good to you? Other option is to have a specific Grimoire release for this KB 5.x version until all is migrated to 6.x.

If you thing something should be changed in sigils open a ticket there. I don't think kibana must be changed to support this sigils/grimoirelab behavior.

**Comment by acs** [comment]
Closing this ticket once all has been fixed in 18.07-01. @jgbarah if you have any issues just reopen this ticket or open a new one.
