### ISSUE TITLE
Problem with author_date formatting

### ISSUE THREAD

**Issue by BenLloydPearson** [chaoss/grimoirelab#143]
I'm using the grimoirelab/full container and I've identified an issue with the author_date field that's stored in elasticsearch. All date fields except for author_date include the time information in the field by default. You can see this in the following screenshot.

<img width="640" alt="screen shot 2018-08-29 at 7 19 17 pm" src="https://user-images.githubusercontent.com/7205829/44822378-77fdea80-abc0-11e8-9731-afc11d6f7d83.png">

When I edit the field through the kibana management page, I see that the moment.js pattern for the field is `MMM Do YYYY`, when it should be `MMMM Do YYYY, HH:mm:ss.SSS`

**Comment by jgbarah** [comment]
@BenLloydPearson, is this fixed?

**Comment by BenLloydPearson** [comment]
Yes, this has been resolved. Thank you.
