### ISSUE TITLE
[DOC]: elastic-search instance (shallowed doc prerequisite)

### ISSUE THREAD

**Issue by MalloZup** [chaoss/grimoirelab#144]
Hi all,
i am reading the grimoirelab tutorial and various github repositories. ( i have also fun reading it so i try to improve the docs too :smiley: )

I wanted to give just a simple feedback or the `experience` as newbie that i got:

i have the impression that during the tutorial and docs we don"t state precisely the dependence between `grimoireLab` and  an already running `elastic search` during the installation.

Eleastic-search is mentioned in many places but during the install we could think that
```pip3 install grimoirelab``` would do everything and we don"t need even to install elasticsearch.

To me we should state more clearly that `eleastic search` instance ( locally or somewhere installed) is a requirement.

We might create just a small section were we could write it down 
what do you think? :thinking:

**Comment by jgbarah** [comment]
Thanks a lot for the comment. Could you read this in https://chaoss.github.io/grimoirelab-tutorial/ and in particular in the current [The basics chapter](https://chaoss.github.io/grimoirelab-tutorial/basics/components.html) and the [Installation for the impatient section](https://chaoss.github.io/grimoirelab-tutorial/basics/quick.html#installation-for-the-impatient)?

**Comment by MalloZup** [comment]
@jgbarah thx yop we can close

**Comment by jgbarah** [comment]
Thx!
