### ISSUE TITLE
[DOC Bug] broken link on https://grimoirelab.gitbooks.io/tutorial/grimoireelk/dashboards/dashboards/dashboards/github-dashboard.json

### ISSUE THREAD

**Issue by MalloZup** [chaoss/grimoirelab#145]
https://grimoirelab.gitbooks.io/tutorial/grimoireelk/dashboards/dashboards/dashboards/github-dashboard.json

**Comment by MalloZup** [comment]
@jgbarah  CC 
i think the 404 is related to this github repo.
https://github.com/chaoss/grimoirelab-tutorial

**Comment by jgbarah** [comment]
Thanks, @MalloZup 

That's an old version of the tutorial, that was maintained in GitBooks until it stopped using free software for the production of the HTML version. Now, the tutorial can be read on-line at https://chaoss.github.io/grimoirelab-tutorial/

Thanks in any case for pointing out, I did delete the old version, to avoid confusion.

I'm clossing the issue, please feel free to reopen if you feel that's still convenient.
