### ISSUE TITLE
Sorting Hat 1.0

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab#165]
Sorting Hat was started as a command line tool into the Metrics Grimoire project. Its purpose was to make easier the daily tasks related with identities management.

Late,  it was adopted as part of GrimoireLab project. It was been used as a command line tool but also as a library by Grimoire ELK library to access identities data. Despite this usage, Sorting Hat was not conceived for the simultaneous access of multiple actors to its data, This causes many problems and and produces complex workflows to operate it.

Sorting Hat will be converted into a web service to solve these problems.

**Comment by jgbarah** [comment]
Will the library API (or an evolution of it) be maintained? And the command line interface?

**Comment by sduenas** [comment]
Yes. There are more details here: https://github.com/chaoss/grimoirelab-sortinghat/wiki/Roadmap-to-Sorting-Hat-1.0

**Comment by sduenas** [comment]
I'm going to close this issue. We should have SortingHat 1.0 when we release GrimoireLab 1.0, which it's gonna take some time :D. We accomplished all we wanted with the new version of SortingHat
