### ISSUE TITLE
Github Pull Requests metric

### ISSUE THREAD

**Issue by flaviobeck** [chaoss/grimoirelab#169]
Hello,

I can see there are several dashboards and visualizations related to github pull requests, but I really could not find anything related to pull requests comments:

I would like to study some metrics to measure pull requests quality. One idea is to relate the pull request content (number of files or LOC, or number of commits, etc) to the number of Review comments.

If I am not wrong, we can consider an hierarchy of objects for pull requests:

- Pull Request (pull request it self)
   - Pull Request Review (Pull Request Reviews are groups of Pull Request Review Comments on the Pull Request, grouped together with a state and optional body comment.)
      - Pull Request Review Comment (Pull Request review comments are comments on a portion of the unified diff. )

[from: https://developer.github.com/v3/pulls/]

Its possuble to collect data from Pull request Review ?
like number of comments per Pull request Review

Its possible to collect number of pull request review per pull request?

Thank you in advance,
Flavio

**Comment by valeriocos** [comment]
Hi @flaviobeck ,
Sure it is possible, but currently GrimoireLab doesn't provide visualizations for Pull request data (i.e., reviews, reviewers). You can collect pull request data using the Perceval GitHub backend with category `pull_request`. You will have data about: submitters, mergers, review comments, requested reviewers and commits in PR (see code at: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L240).

To collect and enrich PR data you should include in your setup.cfg and projects.json something like this:

**setup.cfg**
```
[github:pull]
raw_index = ...
enriched_index = ...
api-token = xxxx
sleep-for-rate = true
category = pull_request
...
```
**projects.json**
```
"github:pull": [
            "https://github.com/..."
        ],
```
Once you have the enriched data in your ElasticSearch, you can either create your own visualizations in Kibiter or write scripts to perform the analysis you need.

Let me know if you have any problem to collect this data.

**Comment by valeriocos** [comment]
@flaviobeck I would close this issue . Feel free to reopen it if needed.
