### ISSUE TITLE
[tests] Check some details in projects.json

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab#17]
There are some details to check in projects.json, in the tests directory:

* why "*jenkins" and "jenkins" as entries?
* Why "*jira" (two of them) and "jira"?

Let's check them, and either explain why they are needed, or just remove those entries.

**Comment by acs** [comment]
@jgbarah is this still relevant?

**Comment by jgbarah** [comment]
I think this is no longer relevant. Closing.
