### ISSUE TITLE
Error enriching `project` field in GitLab data

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#171]
It seems there is an issue enriching GitLab data, because for any project in your projects.json file, you get their enriched data field `project` as `Main`.

You can see it in https://gitlab.biterg.io/app/kibana#/dashboard/2e968fe0-b1bb-11e8-8aac-ef7fd4d8cbad

And for this [projects.json](https://gitlab.com/jsmanrique/grimoirelab-demos/blob/master/GNOME/projects.json), I am getting only one `Main` project for GitLab data:
http://46.101.128.86:5601/app/kibana#/dashboard/2e968fe0-b1bb-11e8-8aac-ef7fd4d8cbad
while I have the expected projects for git, for example:
http://46.101.128.86:5601/app/kibana#/dashboard/Git

**Comment by sduenas** [comment]
Fixed by https://github.com/chaoss/grimoirelab-elk/pull/530
