### ISSUE TITLE
Addition of GitHub Stars, Forks and Watchers

### ISSUE THREAD

**Issue by dicortazar** [chaoss/grimoirelab#184]
The goal of this task is to produce a final 'adoption' or 'popularity' panel that helps to understand how a technology is adopted by people outside of the project.

There are some ideas around (first contributions, newcomers ratio, etc), but it seems that having these initial set of metrics may help at least to have a first understanding of what's going on.

This issue may require actions on the following repositories:
* [Perceval](https://github.com/chaoss/grimoirelab-perceval)
* [GELK](https://github.com/chaoss/grimoirelab-gelk)
* [Mordred](https://github.com/chaoss/grimoirelab-mordred)
* [Sigils](https://github.com/chaoss/grimoirelab-sigils)

The initial set of expected metrics are the following ones:
* Stars
* Watchers
* Forks

There are others that might be interesting for this such as those under the /traffic part of the API. However in a first a quick view, they seem to be related to the development of Apps within the GitHub ecosystem.

The closing condition for this would be to have a process to retrieve this information and a final panel or panels that helps with this process.

**Comment by alpgarcia** [comment]
@dicortazar, @sduenas should we close this?

**Comment by sduenas** [comment]
Not yet. I need to review the PR needed to upload panels and aliases with Mordred.

**Comment by sduenas** [comment]
This feature was added to the last release: [0.2.14]( https://github.com/chaoss/grimoirelab/releases/tag/0.2.14).
