### ISSUE TITLE
Require DCO sign-off for new commits

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab#188]
This issue is to activate [protobot/dco](https://github.com/apps/dco) (or similar bot) to check that all commits have a sign-off in this repository. 

The [CHAOSS Project Charter section 8.2.1](https://chaoss.community/about/charter/#user-content-8-intellectual-property-policy) requires that all contributions are signed-off. The CHAOSS project has been piloting the use of DCO sign-offs. Once contributors know how to do it, sign-offs are easy to do with little overhead. 

> For users of the git command line interface, a sign-off is accomplished with the `-s` as part of the commit command: `git commit -s -m 'This is a commit message'`
>
> For users of the GitHub interface, a sign-off is accomplished by writing `Signed-off-by: Your Name <YourName@example.org>` into the commit comment field. This can be automated by using a browser plugin like [scottrigby/dco-gh-ui](https://github.com/)

**To-Do for repo maintainers:** Please inform your contributors about DCO sign-offs and comment on this issue when your are ready for the DCO bot to be activated on this repository.

**Comment by sduenas** [comment]
Developers and users were informed used GrimoireLab mailing list. The date to start with DCO was set to April 1st.

I've just activated https://github.com/apps/dco for all GrimoireLab repositories. If everything is configured, I think we can close this issue and the series of issues openened in other repositories.

**Comment by jgbarah** [comment]
I've just added a note in `CONTRIBUTING.md` about this. I think we could close this issue once that pr, #190, is accepted.

**Comment by GeorgLink** [comment]
Thanks @sduenas and @jgbarah

**Comment by alpgarcia** [comment]
@GeorgLink do you think we are done with this or is there anything else needed to close the issue?

**Comment by GeorgLink** [comment]
Yes, thank you!
