### ISSUE TITLE
[tests] Some details in docker-compose.yml:

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab#19]
When reading the file docker-compose.yml: in tests, shouldn't mariadb export some port? Or maybe not, and we could do the same for elasticsearch and kibitter? As the file is now, you need some ports available, which maybe are not in a certain host.

**Comment by acs** [comment]
mariadb should not be used outside the docker containers, so it is not needed. Maybe if we want to access mariadb from the host for debugging SortingHat issues, this could be changed.

Kibiter and Elasticsearch are used in different scenarios in the host, ad this is why the ports are openeded to the host.

**Comment by jgbarah** [comment]
I think I finally understood how this works. Sorry for my lack of understanding about docker. Please, correct me if I'm wrong: Inside the containers, `mariadb` is the name of the host hosting MariaDB, as `elasticsearch` is the name of the host with ElasticSearch, for example. So, it is perfectly fine to "connect" to `mariadb` inside the containers.

If this is the case, I will produce a patch to use these names, instead of IP addresses, for all the hosts in the configuration for `docker-compose`.

**Comment by jgbarah** [comment]
Yes, I'm closing it, thanks for noticing.
