### ISSUE TITLE
Error with grimoirelab/secured docker image

### ISSUE THREAD

**Issue by alangsto** [chaoss/grimoirelab#200]
There is a documented error for the searchguard version being used as a plugin for kibiter. 
See more here: https://github.com/floragunncom/search-guard-kibana-plugin/issues/95

Should upgrade to version 13 to eliminate the error in the grimoirelab/secured image.

**Comment by jgbarah** [comment]
Reopening, because this seems like a valid issue. In fact, I see that current version of Kibiter (6.1.4) is no longer supported by SearchGuard...

@alangsto, did you close this for some specific reason?

**Comment by alangsto** [comment]
@jgbarah I originally reported this issue because I thought it was causing an error with my image, although I actually believe the issue I was having was due to an elasticsearch connection problem. 

I haven't retested the secured image, so maybe it was related to the searchguard version.

**Comment by jgbarah** [comment]
Thanks! I was observing that very same behavior with a local docker container, so i think it is a valid issue. I will still re-test it, just to be sure.

**Comment by sduenas** [comment]
This image version is out of maintenance. The new one doesn't have kibana or searchguard integrated.
