### ISSUE TITLE
Unable to see documents to implement GitLab repos on grimoirelab/full.

### ISSUE THREAD

**Issue by asharabu** [chaoss/grimoirelab#216]
Hi,

We could able to configure kibana dashboard using grimoirelab/full for GitHub public and private repos. 

![image](https://user-images.githubusercontent.com/42669995/65480515-66fcd700-deaf-11e9-92d2-1b1a57105ac6.png)

But we are unable to see the documents to append the GitLab private repos along with the above picture.  Please share the steps how to append the buttons GitLab issues, GitLab PRs and GitLab repositories along with the above  GitHub issues, GitHub PRs and GitHub repositories.

**Comment by valeriocos** [comment]
Hi @asharabu ,

Please set to `true` the attributes `gitlab-issues` and `gitlab-merges` in the section `panels` of the dashboard.cfg/setup.cfg. Make sure you have defined in that file and in the projects.json the section `gitlab:issue` and `gitlab:merge` (see example below). Note that the repositories section doesn't exist for GitLab.

**setup.cfg**
```
[panels]
kibiter_time_from = now-90d
...
gitlab-issues = true
gitlab-merges = true

...
[gitlab:issue]
category = issue
raw_index = ...
enriched_index = ...
api-token = ...
sleep-for-rate = true
no-archive = true

[gitlab:merge]
category = merge_request
raw_index = ...
enriched_index = ...
api-token = ...
sleep-for-rate = true
no-archive = true
```

**projects.json**
```
{
    "Gitlab": {
        ...
        "gitlab:issue": [
            "https://gitlab.com/....",
            "https://gitlab.com/..."
        ],
        "gitlab:merge": [
            "https://gitlab.com/....",
            "https://gitlab.com/..."
        ],
....
```

**Comment by asharabu** [comment]
Hi,

Thanks for your update.

I am using dashboard.cfg file and I have added as you mention on dashboard.cfg

---
[gitlab:issue]
category = issue
raw_index = gitlab_grimoirelab-issues
enriched_index = gitlab_grimoirelab_issue
api-token = \<key\>
sleep-for-rate = true
no-archive = true

[gitlab:merge]
category = merge_request
raw_index = gitlab_grimoirelab-merges
enriched_index = gitlab_grimoirelab_merge
api-token = \<key\>
sleep-for-rate = true
no-archive = true

---

Should we pass api-token on dashboard.cfg or can we pass via credentials.cfg which is mount as override.cfg on the container?

I have added the repo url as below on projects.json file,

---
    "openproject-git-test": {
        "git": [
            "https://<username>:<key>@<gitlaburl>/ashar_ma/openproject-git-test"
        ],
        "gitlab:issue": [
            "https://<gitlaburl>/ashar_ma/openproject-git-test"
        ],
        "gitlab:merge": [
            "https://<gitlaburl>/ashar_ma/openproject-git-test"
        ]
    }
---

We are getting below error,

---

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 229, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 229, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 245, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 160, in fetch
    self.client = self._init_client()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 214, in _init_client
    self.archive, from_archive)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 423, in __init__
    self._init_rate_limit()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 646, in _init_rate_limit
    raise error
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 642, in _init_rate_limit
    response = super().fetch(url)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://gitlab.com/api/v4/projects/ashar_ma%2Fopenproject-git-test
2019-09-24 07:59:13,467 - grimoire_elk.elk - ERROR - Error feeding ocean from gitlab (https://gitlab.com/ashar_ma/openproject-git-test): 401 Client Error: Unauthorized for url: https://gitlab.com/api/v4/projects/ashar_ma%2Fopenproject-git-test

---

Please note that our git URL is our custom domain, not gitlab.com.

**Comment by valeriocos** [comment]
> Should we pass api-token on dashboard.cfg or can we pass via credentials.cfg which is mount as override.cfg on the container?

It's probably better to pass it via the credentials.cfg

> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://gitlab.com/api/v4/projects/ashar_ma%2Fopenproject-git-test
> 2019-09-24 07:59:13,467 - grimoire_elk.elk - ERROR - Error feeding ocean from gitlab (https://gitlab.com/ashar_ma/openproject-git-test): 401 Client Error: Unauthorized for url: https://gitlab.com/api/v4/projects/ashar_ma%2Fopenproject-git-test

The token is not correctly passed, this is reason of `401 Client Error: Unauthorized for url`

> Please note that our git URL is our own custom domain, not gitlab.com.

If this applies also to your gitlab projects, you should add to the dashboard.cfg the param `enterprise-url`, which is the `Base URL for GitLab Enterprise instance`

**Comment by asharabu** [comment]
Hi,

Can we use more than one URL at a time for Gitlab URLs? for example gitlab.com and customdomain.com?

**Comment by valeriocos** [comment]
It's not possible to pass the entreprise-url via the projects.json. However, you can create other gitlab sections in the dashboard.cfg, where the raw and enriched indexes are the same of the previous gitlab sections you defined. For instance:
```
[gitlab:issue]
category = issue
raw_index = gitlab_grimoirelab-issues
enriched_index = gitlab_grimoirelab_issue
api-token = <key>
sleep-for-rate = true
no-archive = true

[gitlab:issueent]
category = issue
raw_index = gitlab_grimoirelab-issues
enriched_index = gitlab_grimoirelab_issue
api-token = <key1>
sleep-for-rate = true
no-archive = true
enterprise-url = ....

[gitlab:merge]
category = merge_request
raw_index = gitlab_grimoirelab-merges
enriched_index = gitlab_grimoirelab_merge
api-token = <key>
sleep-for-rate = true
no-archive = true

[gitlab:mergeent]
category = merge_request
raw_index = gitlab_grimoirelab-merges
enriched_index = gitlab_grimoirelab_merge
api-token = <key1>
sleep-for-rate = true
no-archive = true
enterprise-url = ....
```

The new sections should appear also in the projects.json

Let me know if this helps, thanks

**Comment by valeriocos** [comment]
Feel free to reopen the issu @asharabu , thanks
