### ISSUE TITLE
add new enriched field utc_commit_time_of_day

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab#217]
The goal is to add a new enriched field `utc_commit_time_of_day` to the git index. 

`utc_commit_time_of_day = REMOVEDATEBUTKEEPTIME(utc_commit)`

This new field will support the new common metric "Commit Hours and Time"

The idea for this feature came from: https://github.com/chaoss/wg-common/issues/29

**Comment by alpgarcia** [comment]
Closing this via chaoss/grimoirelab-elk#691
