### ISSUE TITLE
How to set period between data pulls?

### ISSUE THREAD

**Issue by mpas** [chaoss/grimoirelab#229]
I am trying to setup and understand how the configure a simple stack and was wondering if there is parameter that influences at what time interval data is being pulled from sources. In the configuration there is a general setting called `min_update_delay ` but according to the documentation this is a setting that tries to influence the time between tasks (collect, enrich ...) etc.. Is there a setting that for example tells the stack to check every xxx seconds?

**Comment by valeriocos** [comment]
Hi @mpas, thank you for your interest in GrimoireLab. I'm pretty sure there is no param that check a data source every x seconds, I'll double-check and let you know.

Why you need to check a source every x seconds?

**Comment by mpas** [comment]
@valeriocos There is no real need, but i was just wondering what the interval would be that GrimoireLab is using when trying to get data from external resources. When checking the logging i saw stuff like "sleeping for 300 seconds" and was wondering what is influencing the timer etc :) So just being curious.

**Comment by jgbarah** [comment]
I think it is `min_update_delay` in the SirMordred configuration file(s). For example, in [the one we use for `grimoirelab/installed` and `grimoirelab/full` Docker containers](https://github.com/chaoss/grimoirelab/blob/1f6c10a6477cf74b79cafe475f95cd5ea354b457/docker/mordred-dashboard.cfg#L16), you can find the lines: 

```
# Don't start a new update earlier than (since last update, seconds)
min_update_delay = 300
```
You can tweak it to shorten or enlarge the period until trying to update from a given data source. AFAIK, enriching comes directly after data collection is done, so this parameter does not affect the delay between both (which is rather short).

@mpas, @valeriocos, if you find this is correct, please close this issue.

**Comment by mpas** [comment]
@jgbarah Thanks for the explanation.

My expectation would be that if i set this value to a low number like 10 (seconds) the update will be triggered every 10 seconds or am i missing something? I tried to set this value to a low number and see what the effect in on the collection of data. Setting this parameter to a low value actually seems to influence little.

```
[general]
# Debug mode (logging mainly)
debug = true

# Don't start a new update earlier than (since last update, seconds)
min_update_delay = 10
```

**Comment by sduenas** [comment]
Hi @mpas,

That depends of how fast the processes retrieving and updating data are. The idea is once these processes finish, a new iteration will start again. As we cannot guarantee the processes will finish fast, nothing will be triggered to start again even if you set a very small delay.

**Comment by mpas** [comment]
@sduenas that makes perfect sense, but when i check the logs using the official `grimoirelab/installed:0.2.32' image the retrieval is fast using a github project.

```
grimoirelab_1    | Collection for git: starting...
grimoirelab_1    | Collection for git: finished after 00:00:13 hours
grimoirelab_1    | Collection for git: starting...
grimoirelab_1    | Collection for git: finished after 00:00:01 hours
grimoirelab_1    | Collection for git: starting...
grimoirelab_1    | Collection for git: finished after 00:00:01 hours
grimoirelab_1    | Collection for git: starting...
grimoirelab_1    | Collection for git: finished after 00:00:01 hours
grimoirelab_1    | Collection for git: starting...
grimoirelab_1    | Collection for git: finished after 00:00:01 hours
```

Letting the process run for a number of minutes i would expect that the number of messages telling me that Collection is starting and finishing would be a lot more when setting this number to a lower number like 10's.

**Comment by mpas** [comment]
If the setting `min_update_delay` is changed in the infra.cfg file do you see any changes to the data requests? Or any log messages that this setting is actually being overriden ?

**Comment by mpas** [comment]
I have set the setting on a strange value like 12345 (seconds) and the data pulls are still every 300 seconds (5 minutes)

```
2019-11-05T10:56:03.128304344Z Collection for git: starting...
2019-11-05T10:56:04.808523009Z Collection for git: finished after 00:00:01 hours
2019-11-05T11:01:20.607438478Z Collection for git: starting...
2019-11-05T11:01:22.461658768Z Collection for git: finished after 00:00:01 hours
2019-11-05T11:06:49.264506134Z Collection for git: starting...
2019-11-05T11:06:51.091506394Z Collection for git: finished after 00:00:01 hours
2019-11-05T11:12:07.578690820Z Collection for git: starting...
2019-11-05T11:12:09.512700931Z Collection for git: finished after 00:00:01 hours
```

**Comment by valeriocos** [comment]
sorry for the late reply @mpas 

> If the setting min_update_delay is changed in the infra.cfg file do you see any changes to the data requests? Or any log messages that this setting is actually being overriden ?

A log message should be produced by this code:
https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/task_manager.py#L104

**Comment by valeriocos** [comment]
@mpas let's close this issue, feel free to reopen it if needed.
