### ISSUE TITLE
Redefine GrimoireLab releases

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab#240]
Over the last few years we have been doing GrimoireLab releases manually. The process is long and tedious and full of steps. Moreover, the artifacts generated (pip packages, docker images and tarballs) are not well defined.

For those reasons I think is the time to improve this process focusing in the next topics:

- [x] Generate better documentation with each release
- [x] Improve versioning
- [x] Automate GrimoireLab releases
- [x] Define how pip packages are generated
- [x] Define Docker images

**Comment by jgbarah** [comment]
The process for generating pip packages & Docker images is at least in part automated, once the release file is produced: have a look at the [Building.md](https://github.com/chaoss/grimoirelab/blob/master/BUILDING.md), and in particular to section "[pip packages and Docker images using Ansible](https://github.com/chaoss/grimoirelab/blob/master/BUILDING.md#pip-packages-and-docker-images-using-ansible)". Of course, it can be improved, and better documented.

**Comment by sduenas** [comment]
Completed. We can generate an release and Docker image using just GitHub Actions. Kudos to @jjmerchante and @vchrombie for all their work here.
