### ISSUE TITLE
Stop any further development on Kibiter

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#244]
GrimoireLab Kibiter has been an important part of GrimoireLab toolkit for a long time, but mainly because it has been part of Bitergia Analytics offering. But the value it provides to any GrimoireLab user is too low to justify maintaining a fork of Kibana as part of GrimoireLab toolkit at all, specially since important features like security access, or desired ones like multitenancy or alerts, are part of [OpenDistro](https://opendistro.github.io/for-elasticsearch/), now supported by GrimoireLab.

Wouldn't it be great to use just upstream components instead of maintaining forked versions that generate a lot of issues?

I would suggest to stop any further development on Kibiter and work on improving support for OpenDistro, and use its Kibana as reference visualization tool for GrimoireLab data.

**Comment by sduenas** [comment]
What should I do then with the components developed in Kibiter? The menu for example?

**Comment by jsmanrique** [comment]
> What should I do then with the components developed in Kibiter? The menu for example?

Sorry, I don't understand the question. Which component are you talking about when you say "menu"? The custom html for having a top navigation menu?

In Kibana that's solved with "Dashboards" link. I know, it is not perfect, but it works.

The navigation menu, I would say it's a "extra feature" developed by Bitergia for its customers, not strictly linked with GrimoireLab toolkit (to gather, to process, and to consume data)

Has it answered your question?

**Comment by sduenas** [comment]
> The navigation menu, I would say it's a "extra feature" developed by Bitergia for its customers, not strictly linked with GrimoireLab toolkit (to gather, to process, and to consume data)
> 

Well, it was developed by Bitergia but it was integrated with GrimoireLab and it's part of the code of GrimoireLab.

So my question is, should GrimoireLab stop proving menus and a way to organize panels?

**Comment by jsmanrique** [comment]
> > The navigation menu, I would say it's a "extra feature" developed by Bitergia for its customers, not strictly linked with GrimoireLab toolkit (to gather, to process, and to consume data)
> 
> Well, it was developed by Bitergia but it was integrated with GrimoireLab and it's part of the code of GrimoireLab.
> 
> So my question is, should GrimoireLab stop proving menus and a way to organize panels?

IMHO, yes. Kibana already provides a way to access and search for existing dashboards, through the "Dashboard" button.

From GrimoireLab point of view, the need to update Kibiter for such features avoids more synced updates with Elasticsearch + Kibana or the Open Distro for Elasticsearch upstream projects

But I would love reading others' comments.

**Comment by sanacl** [comment]
From the community point of view I don't see a huge difference in the added value and the scope of the project is more clear. We would miss in the community version would be the new viz we created such as the network chart.

Said that, the plan makes sense to me. Maybe we could tell the rest of the community to take care of this component if they want to keep it alive.

:+1:

**Comment by acs** [comment]
> We would miss in the community version would be the new viz we created such as the network chart.

AFAIK these are plugins maintained by their original developers, in this case, @dlumbrer : https://github.com/dlumbrer/kbn_network. And it should work in Kibana and probably in Open Distro is the plugins has been updated to the needed version. So IMHO no losses about it if Kibiter is not maintained anymore. The same applies for he rest of the features implemented as plugins.

And for the specific features which modify Kibana, I share the idea that they are too costly and the value offered to the community too low in comparison to maintain them. At the end, the cost of maintain modifications not propagated upstream is very high.
