### ISSUE TITLE
Measuring GitLab activity, community and performance with GrimoireLab

### ISSUE THREAD

**Issue by anajsana** [chaoss/grimoirelab#247]
Issue related with blog post from blog.bitergia.com [ https://blog.bitergia.com/2019/01/04/measuring-gitlab-activity-community-and-performance-with-grimoirelab/ ]

Asking for steps related with configuration files (in order to graph GitLab contribution activity)

**Comment by valeriocos** [comment]
Please, find below the steps and examples of the configuration files. Note that the figures with captions `Network analysis visualization..` and `Median time open issue..` are related to visualizations created for the blogpost (thus not included in the standard panels).

**steps**
- clone the repo https://github.com/chaoss/grimoirelab
- cd to `grimoirelab/default-grimoirelab-settings`
- modify the projects.json with the content in **projects.json**
- create the file dashboard.cfg with the content in **dashboard.cfg**
- create the file credentials.cfg with the content in **credentials.cfg**
- execute: `docker run -p 5601:5601 -p 9000:9200 -v $(pwd)/projects.json:/projects.json -v 
  $(pwd)/dashboard.cfg:/dashboard.cfg -v $(pwd)/credentials.cfg:/override.cfg -t grimoirelab/full`
- you can check the indexes at this URL (via browser or curl): `http://localhost:9000/_cat/indices?pretty`
- you can access the dashboard at http://localhost:5601

**projects.json**
```
{
    "gnome-shell": {
        "git": ["https://gitlab.gnome.org/GNOME/gnome-shell.git"],
        "gitlab:issue": ["https://gitlab.gnome.org/GNOME/gnome-shell"],
        "gitlab:merge": ["https://gitlab.gnome.org/GNOME/gnome-shell"],
        "pipermail": ["https://mail.gnome.org/archives/gnome-shell-list/"]
    }
  }
```

**dashboard.cfg**
```
[general]
# Update incrementally, forever
update = true
# Don't start a new update earlier than (since last update, seconds)
min_update_delay = 300
# Produce debugging data for the logs
debug = true

[es_enrichment]
# Refresh identities and projects for all items after enrichment
autorefresh = true

[sortinghat]
# Run affilation
affiliate = True
# How to match to unify
matching = [email]
# How long to sleep before running again, for identities tasks
sleep_for = 100

[panels]
# Dashboard: default time frame
kibiter_time_from = "now-1y"
# Dashboard: default index pattern
kibiter_default_index = "git"
# GitLab panels
gitlab-issues = true
gitlab-merges = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
# Names for raw and enriched indexes
raw_index = git_gnome_shell-raw
enriched_index = git_gnome_shell
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[gitlab:issue]
raw_index = gitlab_issues_gnome_shell_raw
enriched_index = gitlab_issues_gnome_shell_enriched
no-archive = true
enterprise-url = https://gitlab.gnome.org
sleep-for-rate = true

[gitlab:merge]
raw_index = gitlab_merges_gnome_shell_raw
enriched_index = gitlab_merges_gnome_shell_enriched
no-archive = true
enterprise-url = https://gitlab.gnome.org
category = merge_request
sleep-for-rate = true

# Studies

[enrich_demography:git]
#no_incremental = true   # default: false

[enrich_areas_of_code:git]
in_index = git_gnome_shell-raw
out_index = git_aoc_gnome_shell-enriched
#sort_on_field = metadata__timestamp
#no_incremental = false

[enrich_onion:git]
in_index = git_gnome_shell
out_index = git_onion_gnome_shell-enriched
#data_source = git
#contribs_field = hash
#timeframe_field = grimoire_creation_date
#sort_on_field = metadata__timestamp
#no_incremental = false
```

**credentials.cfg**
```
[gitlab:issue]
api-token = xxx

[gitlab:merge]
api-token = xxx
```

**Comment by valeriocos** [comment]
Issue closed, @anajsana feel free to reopen it if needed, thanks
