### ISSUE TITLE
Why do we have two docker-compose solutions?

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab#250]
In the [Docker-Compose folder](https://github.com/chaoss/grimoirelab/tree/master/docker-compose), we have the regular 'docker-compose.yml' and the 'docker-compose-secured.yml'. 

From the README in that folder, I cannot see why we need to different files.

Why not simply make the "secured" solution the only one we offer?

**Comment by valeriocos** [comment]
The `secured` solution is documented at https://github.com/chaoss/grimoirelab/blob/master/docker-compose/README.md#secured-infrastructure. Depending on the type of the grimoirelab users, it seems reasonable to have the non-secured and secured solutions.

**Comment by valeriocos** [comment]
(I clicked on the wrong button, however we could close this issue)

**Comment by GeorgLink** [comment]
According to the README section on the secured solution, it is not clear to me what the difference is between to the none-secured option.

If there is no difference in how I can use it, then I propose to eliminate the non-secure solution and make the secured solution the only available option.

**Comment by valeriocos** [comment]
Related to this issue: https://github.com/chaoss/grimoirelab/pull/251

The difference is that kibiter is protected by a password in the `secured` solution (https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose-secured.yml#L43). 

It may be possible that some users (e.g., students) don't need a password to play with grimoirelab.

**Comment by GeorgLink** [comment]
I compared the secured files with the non-secured files (and created pr #252).

I see two differences in the docker compose instructions:
- different elasticsearch image: our own elastisearch version vs. the official oss elastic verison.
- a secured kibiter image

This requires two changes in the setup.cfg file:
- different elasticsearch url
- different kibiter url
