### ISSUE TITLE
Add Rocket.chat support

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab#257]
It would be nice to support FLOSS alternatives to Slack suck Rocket.chat. As they define the product in the web "Rocket.Chat is free, unlimited and open source. Replace email, HipChat & Slack with the ultimate team chat software solution."

The ideal scenario would be to have a compatible mapping between Slack and these alternatives, so it is possible to study the evolution of the data when organizations migrate from one to another.

The API is available at https://rocket.chat/docs/developer-guides/rest-api/

**Comment by valeriocos** [comment]
Related to https://github.com/chaoss/grimoirelab-perceval/issues/543

**Comment by Syn3rman** [comment]
Hey @valeriocos, 

I'd like to start working on this if this is still available and relevant. What data does it make sense to fetch from the API?

Thanks

**Comment by valeriocos** [comment]
Thank you for your interest @Syn3rman!

You can rely on the same structure of slack or mattermost. Thus, the backend should receive the pointer to a channel and fetch its messages. Good endpoints should be:
- https://rocket.chat/docs/developer-guides/rest-api/channels/history/
- https://rocket.chat/docs/developer-guides/rest-api/channels/info/
- https://rocket.chat/docs/developer-guides/rest-api/channels/members/ (optionally)

**Comment by Syn3rman** [comment]
Hey @valeriocos,
I've started implementing the feature [over here](https://github.com/Syn3rman/grimoirelab-perceval/blob/master/perceval/backends/core/rocketchat.py) and the progress is as follows: 

- [x] Add backend to fetch messages from a RocketChat server.
- [ ] Run tests
- [ ] Get channel info from channels.info

I also haven't yet looked at how ssl_verify works so I'll do that too. Is there anything else to do in this issue before I open a PR? (or should I open one and then continue working on it?)

**Comment by valeriocos** [comment]
That's a great news @Syn3rman ! Please open a PR (as draft if you want), so it will be easier to check the evolution of this work.

> I also haven't yet looked at how ssl_verify works so I'll do that too. Is there anything else to do in this issue before I open a PR? (or should I open one and then continue working on it?)

`ssl_verify` allows to enable/disable SSL verification. In same cases, it is useful (for instance), when dealing with private instances of gitlab and github.

**Comment by vchrombie** [comment]
GrimoireLab now has the support for Rocket.Chat, thanks to @Syn3rman @animeshk08 @valeriocos for being involved and contributing to the data source implementation.

Thanks @sanacl for opening the issue. :)

**Comment by GeorgLink** [comment]
Woot woot! 🎉
