### ISSUE TITLE
Following the readme, there is no result on the dashboard

### ISSUE THREAD

**Issue by Pretice** [chaoss/grimoirelab#260]
Following the readme, I use docker run to run grimoirelab. However, it shows 'No results displayed because all values equal 0'. So what can I do to resolve this?

**Comment by jgbarah** [comment]
Did you wait for a little while? Data has to be retrieved, and enriched, before it shows up in the dashboard.

If you waited for say 10 min (likely less, but let's stay on the safe side), and still get nothing, please post here:

* The exact command that you executed to "run grimoirelab"
* The output you got on the console where you executed it.

**Comment by Pretice** [comment]
> Did you wait for a little while? Data has to be retrieved, and enriched, before it shows up in the dashboard.
> 
> If you waited for say 10 min (likely less, but let's stay on the safe side), and still get nothing, please post here:
> 
> * The exact command that you executed to "run grimoirelab"
> * The output you got on the console where you executed it.

Sorry, I have waited for more than 10 min but there is still no results. Maybe it need more time to show up in the dashboard? Because there is no error or other tips on the console.

**Comment by Pretice** [comment]
I also used the 'docker-compose' to run the grimoirelab just, but on the dashboard, it showed 'Status: Red', and showed 'Status BreakDown plugin:metrics@6.1.4-1 Request Timeout after 3000ms'.

**Comment by Pretice** [comment]
> Did you wait for a little while? Data has to be retrieved, and enriched, before it shows up in the dashboard.
> 
> If you waited for say 10 min (likely less, but let's stay on the safe side), and still get nothing, please post here:
> 
> * The exact command that you executed to "run grimoirelab"
> * The output you got on the console where you executed it.

The exact command I used to executed is:

`sudo docker run -p 127.0.0.1:5601:5601 \
-v $(pwd)/default-grimoirelab-settings/projects.json:/projects.json \
-v $(pwd)/default-grimoirelab-settings/setup.cfg:/setup.cfg \
-t grimoirelab/full`

**Comment by valeriocos** [comment]
Hi @Pretice, did you try to give more virtual memory to elasticsearch?
You can do it with `sysctl -w vm.max_map_count=262144` on Linux (more info at: https://github.com/chaoss/grimoirelab/tree/master/docker-compose#requirements)

**Comment by Pretice** [comment]
> Hi @Pretice, did you try to give more virtual memory to elasticsearch?
> You can do it with `sysctl -w vm.max_map_count=262144` on Linux (more info at: https://github.com/chaoss/grimoirelab/tree/master/docker-compose#requirements)

Thank U so much, it works. But it still shows 'no results' on the dashboard, maybe it need some time to show up?

**Comment by valeriocos** [comment]
You're welcome! If you are using the [default conf files](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings), it should take around 10 minutes.

To check that the data is flowing to ElasticSearch, you can use the following command: `<es-url>:<es-port>/_cat/indices?pretty` (e.g., http://127.0.0.1:9200/_cat/indices?pretty). More info on `_cat/indices` is available at: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html

**Comment by Pretice** [comment]
> You're welcome! If you are using the [default conf files](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings), it should take around 10 minutes.
> 
> To check that the data is flowing to ElasticSearch, you can use the following command: `<es-url>:<es-port>/_cat/indices?pretty` (e.g., http://127.0.0.1:9200/_cat/indices?pretty). More info on `_cat/indices` is available at: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html

There is something :

`yellow open git_demo_raw qH2BeI_mTNyPSVaOB0kR3A 5 1   0  0   1.1kb   1.1kb
yellow open .kibana      KdrpEGvcR6aneeFnAgX1_w 1 1 178 22 253.5kb 253.5kb
`

Does this mean I will continue to wait?

**Comment by valeriocos** [comment]
```
There is something :

yellow open git_demo_raw qH2BeI_mTNyPSVaOB0kR3A 5 1 0 0 1.1kb 1.1kb 
yellow open .kibana KdrpEGvcR6aneeFnAgX1_w 1 1 178 22 253.5kb 253.5kb
```
The index `git_demo_raw` is empty (first 0, after 5 and 1). It is possible that the repo is still being downloaded.

If you want see some results quickly, you can analyze https://github.com/chaoss/grimoirelab-toolkit, which is a small repo in terms of commits and issues. To do so, please change the projects.json at https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/projects.json with the following content and re-execute the docker run.
```
{
    "grimoirelab": {
      "meta": {
        "title": "GrimoireLab"
      },
      "git": [
          "https://github.com/chaoss/grimoirelab-toolkit"
        ]
    }
  }
```

**Comment by Pretice** [comment]
> ```
> There is something :
> 
> yellow open git_demo_raw qH2BeI_mTNyPSVaOB0kR3A 5 1 0 0 1.1kb 1.1kb 
> yellow open .kibana KdrpEGvcR6aneeFnAgX1_w 1 1 178 22 253.5kb 253.5kb
> ```
> 
> The index `git_demo_raw` is empty (first 0, after 5 and 1). It is possible that the repo is still being downloaded.
> 
> If you want see some results quickly, you can analyze https://github.com/chaoss/grimoirelab-toolkit, which is a small repo in terms of commits and issues. To do so, please change the projects.json at https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/projects.json with the following content and re-execute the docker run.
> 
> ```
> {
>     "grimoirelab": {
>       "meta": {
>         "title": "GrimoireLab"
>       },
>       "git": [
>           "https://github.com/chaoss/grimoirelab-toolkit"
>         ]
>     }
>   }
> ```

Thank U, it works! Using the smaller repo, I can see some results in the dashboard quickly. But I can only see the results about author , commits and organizations. I want to see the resluts about Issues and merge, if I need more configuration in the projects.json and setup.json?

**Comment by valeriocos** [comment]
Cool! Yes, you need to modify the projects.json and add some conf files. Please, find them below.

**projects.json**
```
{
    "grimoirelab": {
      "meta": {
        "title": "GrimoireLab"
      },
      "git": [
          "https://github.com/chaoss/grimoirelab-toolkit"
        ],
      "github": [
         "https://github.com/chaoss/grimoirelab-toolkit"
       ]
    }
}
```

**credentials.cfg**
```
[github]
api-token = <YOUR-API-TOKEN>
```

**dashboard.cfg**
```
[general]
# Update incrementally, forever
update = true
# Don't start a new update earlier than (since last update, seconds)
min_update_delay = 300
# Produce debugging data for the logs
debug = true

[es_enrichment]
# Refresh identities and projects for all items after enrichment
autorefresh = true

[sortinghat]
# Run affilation
affiliate = True
# How to match to unify
matching = [email]
# How long to sleep before running again, for identities tasks
sleep_for = 100

[panels]
# Dashboard: default time frame
kibiter_time_from = "now-1y"
# Dashboard: default index pattern
kibiter_default_index = "git"

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
# Names for raw and enriched indexes
raw_index = git_grimoirelab-raw
enriched_index = git_grimoirelab
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
# Names for raw and enriched indexes
raw_index = github_grimoirelab-raw
enriched_index = github_grimoirelab
# Sleep it GitHub API rate is exhausted, waited until it is recovered
sleep-for-rate = true

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_grimoirelab-raw
out_index = git_aoc_grimoirelab-enriched

[enrich_onion:git]
in_index = git_grimoirelab
out_index = git_onion_grimoirelab-enriched
```

**docker command**
```
docker run -p 5601:5601 -v $(pwd)/projects.json:/projects.json -v $(pwd)/dashboard.cfg:/dashboard.cfg -v $(pwd)/credentials.cfg:/override.cfg -t grimoirelab/full
```

Hope it helps!

**Comment by Pretice** [comment]
> Cool! Yes, you need to modify the projects.json and add some conf files. Please, find them below.
> 
> **projects.json**
> 
> ```
> {
>     "grimoirelab": {
>       "meta": {
>         "title": "GrimoireLab"
>       },
>       "git": [
>           "https://github.com/chaoss/grimoirelab-toolkit"
>         ],
>       "github": [
>          "https://github.com/chaoss/grimoirelab-toolkit"
>        ]
>     }
> }
> ```
> 
> **credentials.cfg**
> 
> ```
> [github]
> api-token = <YOUR-API-TOKEN>
> ```
> 
> **dashboard.cfg**
> 
> ```
> [general]
> # Update incrementally, forever
> update = true
> # Don't start a new update earlier than (since last update, seconds)
> min_update_delay = 300
> # Produce debugging data for the logs
> debug = true
> 
> [es_enrichment]
> # Refresh identities and projects for all items after enrichment
> autorefresh = true
> 
> [sortinghat]
> # Run affilation
> affiliate = True
> # How to match to unify
> matching = [email]
> # How long to sleep before running again, for identities tasks
> sleep_for = 100
> 
> [panels]
> # Dashboard: default time frame
> kibiter_time_from = "now-1y"
> # Dashboard: default index pattern
> kibiter_default_index = "git"
> 
> [phases]
> collection = true
> identities = true
> enrichment = true
> panels = true
> 
> [git]
> # Names for raw and enriched indexes
> raw_index = git_grimoirelab-raw
> enriched_index = git_grimoirelab
> studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]
> 
> [github]
> # Names for raw and enriched indexes
> raw_index = github_grimoirelab-raw
> enriched_index = github_grimoirelab
> # Sleep it GitHub API rate is exhausted, waited until it is recovered
> sleep-for-rate = true
> 
> [enrich_demography:git]
> 
> [enrich_areas_of_code:git]
> in_index = git_grimoirelab-raw
> out_index = git_aoc_grimoirelab-enriched
> 
> [enrich_onion:git]
> in_index = git_grimoirelab
> out_index = git_onion_grimoirelab-enriched
> ```
> 
> **docker command**
> 
> ```
> docker run -p 5601:5601 -v $(pwd)/projects.json:/projects.json -v $(pwd)/dashboard.cfg:/dashboard.cfg -v $(pwd)/credentials.cfg:/override.cfg -t grimoirelab/full
> ```
> 
> Hope it helps!
> 
> PS there are similar issues that may be useful for you:
> 
> * #233
> * #247
> * #242

After modifing the three configurations above, there is another error when using the docker run:

`
2019-12-27 11:32:38,521 - grimoire_elk.elk - ERROR - Error enriching ocean from github (https://github.com/chaoss/grimoirelab-toolkit): HTTPSConnectionPool(host='maps.googleapis.com', port=443): Max retries exceeded with url: /maps/api/geocode/json?address=Austria&sensor=false (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
`
Does this mean I need an oversea server?

**Comment by Pretice** [comment]
If I change to use the docker-compose, I can see something access to "http://127.0.0.1:9200/_cat/indices?pretty"

```
yellow open .kibana                 KdrpEGvcR6aneeFnAgX1_w 1 1 257 32 351.2kb 351.2kb
yellow open .kibana                 KdrpEGvcR6aneeFnAgX1_w 1 1 257 32 351.2kb 351.2kb
yellow open github_demo_raw         btYlklClTailsbWTihV0MQ 5 1  24  1 622.5kb 622.5kb
yellow open github_demo_enriched    usGIatHbTxCwAD1v6qctmA 5 1   0  0   1.2kb   1.2kb
yellow open git_demo_enriched       kyFA3FUKSCq5X-SGOC6T6Q 5 1  57  0 258.4kb 258.4kb
yellow open git_demo_raw            qH2BeI_mTNyPSVaOB0kR3A 5 1  57  0   150kb   150kb
yellow open git-onion_demo_enriched yVNPzg3SRa2dMezZ3_4aGQ 5 1  80  0  96.5kb  96.5kb
yellow open git-aoc_demo_enriched   VTobUbLMRa26xw-MLnS-aQ 5 1 127  0 235.3kb 235.3kb
```
The index `github_demo_enriched` is always empty (first 0, after 5 and 1). It looks the same as the question in Issue #247

**Comment by valeriocos** [comment]
> Does this mean I need an oversea server?

That's possible, it worked for https://github.com/chaoss/grimoirelab/issues/233#issuecomment-551523392

**Comment by valeriocos** [comment]
@Pretice were you able to see data in the dashboard?

**Comment by Pretice** [comment]
> @Pretice were you able to see data in the dashboard?

Sorry for replying so late. After using a proxy, the index `github_demo_enriched` is still empty(first 0, after 5 and i)
```
yellow open .kibana                 KdrpEGvcR6aneeFnAgX1_w 1 1 257 32 351.3kb 351.3kb
yellow open github_demo_raw         btYlklClTailsbWTihV0MQ 5 1  24  1 622.5kb 622.5kb
yellow open github_demo_enriched    usGIatHbTxCwAD1v6qctmA 5 1   0  0   1.2kb   1.2kb
yellow open git_demo_enriched       kyFA3FUKSCq5X-SGOC6T6Q 5 1  57  0 802.8kb 802.8kb
yellow open git_demo_raw            qH2BeI_mTNyPSVaOB0kR3A 5 1  57  0   150kb   150kb
yellow open git-onion_demo_enriched xWd06iqbRf6rA7sOBv9QdQ 5 1  80  0  97.7kb  97.7kb
yellow open git-aoc_demo_enriched   VTobUbLMRa26xw-MLnS-aQ 5 1 127  2 558.4kb 558.4kb
```
So there is still no data in the dashborad about github. I can't find the reason about the question.

**Comment by valeriocos** [comment]
That's possible that the error is due to a call to `maps.googleapis.com`. We have recently removed that code (https://github.com/chaoss/grimoirelab-elk/commit/c63c98ec387f443fae7d1cd27ef2e038051e77dd). As soon as a new release is out, I'll ping you so you can test it again.

Sorry for the inconvenience,
Valerio

**Comment by Pretice** [comment]
> That's possible that the error is due to a call to `maps.googleapis.com`. We have recently removed that code ([chaoss/grimoirelab-elk@c63c98e](https://github.com/chaoss/grimoirelab-elk/commit/c63c98ec387f443fae7d1cd27ef2e038051e77dd)). As soon as a new release is out, I'll ping you so you can test it again.
> 
> Sorry for the inconvenience,
> Valerio

Thank u so much! I am looking forward to seeing the new release.

**Comment by valeriocos** [comment]
Hi @Pretice , sorry for the late reply. Did you have time to check if the error is gone on your side?

**Comment by Pretice** [comment]
> Hi @Pretice , sorry for the late reply. Did you have time to check if the error is gone on your side?

Sorry for replying so late. I have tried the lastest version 0.2.39 by using **docker run** to analyze data in **grimoirelab-toolkit**, and the configuration is the same as before. Unluckily, I still can only see results of **Git**, and there is no results of **GitHub Issuses** and **GitHub PRs**. What's more, I can't connect to "http://127.0.0.1:9200/_cat/indices?pretty".

**Comment by valeriocos** [comment]
No worries @Pretice , thank you for answering!

Can you try to use the docker-compose version (https://github.com/chaoss/grimoirelab#using-docker-compose)? The error you see with the aliases is due to a recent change in the format of the aliases.json (https://github.com/chaoss/grimoirelab-sirmordred/commit/b6fa5962bfc5dcb7cc779a71586d91c92f3a7057#diff-b6d56075b6e9c4f45704f37afc64257e). 

Thanks

**Comment by Pretice** [comment]
@valeriocos , thank u. I just tried the docker-compose version, but the results were the same as using docker run, there was no results of GitHub issues and GitHub PRs. Using docker-compose, I can connect to "http://127.0.0.1:9200/_cat/indices?pretty", but the index github_demo_enriched is still empty:
```json
yellow open github_demo_enriched    usGIatHbTxCwAD1v6qctmA 5 1   0  0   1.2kb   1.2kb
```
BTW, I haven't mentioned the error with aliases before. Do you mean about connect to "http://127.0.0.1:9200/_cat/indices?pretty"? 
And the format of the aliases.json in the version 0.2.39 now is like below:
```json
"askbot": {
        "raw": ["askbot-raw"],
        "enrich": ["askbot", "affiliations"]
    }
```
Do I need to change the format like this:
```json
"askbot": {
    "raw": [
      {
        "alias": "askbot-raw"
      }
    ],
    "enrich": [
      {
        "alias": "askbot"
      },
      {
        "alias": "affiliations"
      },
      {
        "alias": "all_enriched"
      }
    ]
  }
```

**Comment by Pretice** [comment]
@valeriocos ,  when I used the `docker-compose`,  the configuration is as follows：
`projects.json: `
```json
  {
    "grimoirelab": {
      "meta": {
        "title": "GrimoireLab"
      },
      "git": [
          "https://github.com/chaoss/grimoirelab-toolkit"
        ],
      "github": [
         "https://github.com/chaoss/grimoirelab-toolkit"
       ]
    }
}
```
`setup.cfg: `
```
[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = mariadb
user = root
password =
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
gitlab-issues = true
gitlab-merges = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

#[bugzillarest]
#raw_index = bugzillarest_demo_raw
#enriched_index = bugzillarest_demo_enriched
#no-archive = true

#[confluence]
#no-archive = true
#raw_index = confluence_demo_raw
#enriched_index = confluence_demo_enriched

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
api-token = MY_TOKEN
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
#sleep-time = "300"
enriched_index = github_demo_enriched

#[gitlab:issues]
#api-token = <YOUR_API_TOKEN_HERE>
#raw_index = gitlab_issues_demo_raw
#enriched_index = gitlab_issues_demo_enriched
#no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
#sleep-for-rate = true

#[gitlab:merge]
#api-token = <YOUR_API_TOKEN_HERE>
#raw_index = gitlab_merges_demo_raw
#enriched_index = gitlab_merges_demo_enriched
#no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
#category = merge_request
#sleep-for-rate = true

#[jira]
#raw_index = jira_demo_raw
#enriched_index = jira_demo_enriched
#no-archive = true

#[pipermail]
#raw_index = pipermail_demo_raw
#enriched_index = pipermail_demo_enriched
#no-verify = true

#[mediawiki]
#raw_index = mediawiki_demo_raw
#enriched_index = mediawiki_demo_enriched
#no-archive = true

#[meetup]
#raw_index = meetup_demo_raw
#enriched_index = meetup_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = "300"

#[stackexchange]
#raw_index = stackexchange_demo_raw
#enriched_index = stackexchange_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[slack]
#raw_index = slack_demo_raw
#enriched_index = slack_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[supybot]
#raw_index = supybot_demo_raw
#enriched_index = supybot_demo_enriched

#[twitter]
#raw_index = twitter_demo_raw
#enriched_index = twitter_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = 300

## studies based on enriched indexes

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git-aoc_demo_enriched
out_index = git-onion_demo_enriched
contribs_field = hash
```

**Comment by valeriocos** [comment]
> @valeriocos , thank u. I just tried the docker-compose version, but the results were the same as using docker run, there was no results of GitHub issues and GitHub PRs. Using docker-compose, I can connect to "http://127.0.0.1:9200/_cat/indices?pretty", but the index github_demo_enriched is still empty:

You're welcome @Pretice, and thank you for your quick reply! I'm checking the possible reason why you don't have GitHub data. ATM, I'm not able to replicate your issue. I'll keep you posted (sorry for the inconvenience)

> BTW, I haven't mentioned the error with aliases before. Do you mean about connect to "http://127.0.0.1:9200/_cat/indices?pretty"? ...

Sorry for not being clear, yes the error you reported should be related to the changes in the aliases.json.

I see that the file at https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/aliases.json isn't aligned with https://github.com/chaoss/grimoirelab-sirmordred/blob/master/aliases.json. Can you use the latter and in case the error is gone submit a PR to https://github.com/chaoss/grimoirelab to update the aliases.json? Thanks

**Comment by Pretice** [comment]
@valeriocos After changing the format of the `aliases.json`, I still cant't connent to "http://127.0.0.1:9200/_cat/indices?pretty" when using `docker run`.
When I use command `curl http://127.0.0.1:9200/_cat/indices?pretty`, it shows:
```
curl: (7) Failed to connect to 127.0.0.1 port 9200: refuse to connect
```

**Comment by valeriocos** [comment]
Can you check that the logs of your ES container are free from the message:
`max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`? 

The following troubleshooting section should help you to fix this: https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#low-virtual-memory-

If this doesn't fix the error, can you share the logs of your ES container? Thanks

**Comment by Pretice** [comment]
> Can you check that the logs of your ES container are free from the message:
> `max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`?
> 
> The following troubleshooting section should help you to fix this: https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#low-virtual-memory-
> 
> If this doesn't fix the error, can you share the logs of your ES container? Thanks

I used the command before using `docker run`:
```
sudo sysctl -w vm.max_map_count=262144
```
But I can't connect to to 127.0.0.1 port 9200.
 I check the logs and they are:
```
2020-03-23 14:57:31,429 - sirmordred.sirmordred - ERROR - Cannot connect to Elasticsearch: http://elasticsearch:9200
Can not access Elasticsearch service. Exiting sirmordred ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 493, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 520, in _connect
    socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 493, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 520, in _connect
    socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/arthurd", line 295, in <module>
    main()
  File "/usr/local/bin/arthurd", line 98, in main
    writer=writer)
  File "/usr/local/lib/python3.5/dist-packages/arthur/server.py", line 56, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/arthur/arthur.py", line 51, in __init__
    self.conn.flushdb()
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 893, in flushdb
    return self.execute_command('FLUSHDB', *args)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
Waiting for arthur startup completion ...
Starting two workers: collect and update tasks

```

**Comment by valeriocos** [comment]
Hi @Pretice , sorry for the delay! I wasn't able to replicate your exact problem, but the docker-compose at https://github.com/chaoss/grimoirelab/tree/master/docker-compose wasn't updated to the latest version.

Please can you fetch the latest changes from the grimoirelab repo and run the docker-compose again? Thanks

**Comment by Pretice** [comment]
> Hi @Pretice , sorry for the delay! I wasn't able to replicate your exact problem, but the docker-compose at https://github.com/chaoss/grimoirelab/tree/master/docker-compose wasn't updated to the latest version.
> 
> Please can you fetch the latest changes from the grimoirelab repo and run the docker-compose again? Thanks

I use the lastest grimoirelab repo to run the docker-compose, but it shows error in the terminal:
```
sudo docker-compose up -d
Pulling mordred (bitergia/mordred:grimoirelab-0.2.39)...
ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

```
sudo docker-compose up -d
Pulling mordred (bitergia/mordred:grimoirelab-0.2.39)...
ERROR: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout
```

```
sudo docker-compose up -d
Pulling mordred (bitergia/mordred:grimoirelab-0.2.39)...
ERROR: Get https://registry-1.docker.io/v2/bitergia/mordred/manifests/grimoirelab-0.2.39: Get https://auth.docker.io/token?scope=repository%3Abitergia%2Fmordred%3Apull&service=registry.docker.io: net/http: TLS handshake timeout
```

**Comment by valeriocos** [comment]
I pruned all images, containers and volumes and started the docker-compose, and I'm not able to replicate your problem.
```
Pulling mordred (bitergia/mordred:grimoirelab-0.2.39)...
grimoirelab-0.2.39: Pulling from bitergia/mordred
6d28e14ab8c8: Already exists
8e75b0727e79: Pull complete
e58ba658fd4f: Pull complete
a4381a53fdfa: Pull complete
ae5f067a01fd: Pull complete
97bf7f7af5aa: Pull complete
7d2a8b6f9d1a: Pull complete
f1ec33da724c: Pull complete
67d98b023fc8: Pull complete
744d59d69115: Pull complete
2f3ae9bc50af: Pull complete
2d4cfbba5233: Pull complete
fe0cddb53922: Pull complete
874ee96b4a43: Pull complete
Digest: sha256:68c612bcadd32c5ce1ebd6b356174df2e38bce25c969e51d5da06be02a00909c
Status: Downloaded newer image for bitergia/mordred:grimoirelab-0.2.39

...
slimbook@slimbook-KATANA:~/Escritorio/sources/grimoirelab/docker-compose$ docker ps
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                             PORTS                              NAMES
280ef3930bdb        grimoirelab/hatstall:latest                               "/bin/sh -c ${DEPLOY…"   44 seconds ago      Up 41 seconds                      0.0.0.0:8000->80/tcp               docker-compose_hatstall_1
d3ffd728489d        bitergia/mordred:grimoirelab-0.2.39                       "/bin/sh -c ${DEPLOY…"   44 seconds ago      Up 40 seconds (health: starting)                                      docker-compose_mordred_1
70f7ec9944a4        bitergia/kibiter:optimized-v6.1.4-3                       "/docker-entrypoint.…"   46 seconds ago      Up 42 seconds                      0.0.0.0:5601->5601/tcp             docker-compose_kibiter_1
2b0df14412aa        mariadb:10.0                                              "docker-entrypoint.s…"   49 seconds ago      Up 44 seconds                      3306/tcp                           docker-compose_mariadb_1
ea083fe39642        docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.4   "/usr/local/bin/dock…"   49 seconds ago      Up 46 seconds                      0.0.0.0:9200->9200/tcp, 9300/tcp   docker-compose_elasticsearch_1
```

It could be a connection problem with dockerhub, or maybe at some point your connection wasn't stable?

**Comment by Pretice** [comment]
I think my connection is unstable today, I'll try it later.

**Comment by mafesan** [comment]
Hi there @Pretice, did you have the opportunity to run the `docker-compose` again? Thank you!

**Comment by valeriocos** [comment]
Hi @Pretice , let's close this issue. Feel free to reopen it if needed.
