### ISSUE TITLE
https vs http in docker instructions

### ISSUE THREAD

**Issue by marcrepo** [chaoss/grimoirelab#273]
In the docker-compose instructions (README.md on https://github.com/chaoss/grimoirelab)
the user is instructed to pull up the dashboard using **https**://localhost:5601  

whereas the docker instructions mention using **http**://localhost:5601

I suspect the **https** instructions are incorrect as my web browser was never able to make
a secure connection to the localhost  5601 socket. But worked fine with regular http.

**Comment by valeriocos** [comment]
Thank you @marcrepo for reporting this issue!

The instructions at https://github.com/chaoss/grimoirelab#using-docker-compose rely on the non-secured [docker-compose](https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml). In this scenario, the `http://localhost:5601` is the right URL.

`https://localhost:5601` is the right URL when using the secured [docker-compose](https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose-secured.yml). Instructions to use it are detailed at https://github.com/chaoss/grimoirelab/tree/master/docker-compose#secured-infrastructure.

Would you like to submit a PR to fix the error you spotted?

Thanks

**Comment by marcrepo** [comment]
Thanks. I just submitted the pull request.

**Comment by valeriocos** [comment]
Great! Thanks for submitting the PR
