### ISSUE TITLE
Meetups do not appear on data status screen

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab#277]
It would be helpful if meetups could appear on the data status screen in the same way as other projects (e.g. git, slack, discourse) showing the last retrieval date etc.

**Comment by zhquan** [comment]
Hi @RCheesley ,

The widget appears on the `Data Status` panel if you have the data source added in the `setup.cfg` at the very first time you execute mordred. If you add a new data source after the first execution, you have to remove the panel `Data Status` manually (see image below) and execute/restart mordred again (making sure that the option `panels` is set to `true` in the section `phases`).

![data-status](https://user-images.githubusercontent.com/5637233/73866903-f0e98300-4845-11ea-998c-1e790e605278.png)

The same behavior occurs with the panel Overview.

Best,
Quan

**Comment by valeriocos** [comment]
Hi @RCheesley , we have added some doc here: https://github.com/chaoss/grimoirelab-sirmordred#setupcfg. Feel free to have a look, thanks
