### ISSUE TITLE
Identify potential duplicated users

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab#278]
As a user, it would be helpful to have some way of identifying potential duplicated users, so that I can then search for and merge them in Hatstall.

At the moment, this is a manual process of eyeballing the data and spotting duplicates, but having some way to identify them (e.g. these users all have the same or similar name, or the same email address, for example) would massively improve this process.

It could be a screen in the dashboard, or maybe a feature in Hatstall itself?

**Comment by GeorgLink** [comment]
Ruth, maybe something like describe here https://github.com/chaoss/grimoirelab-sortinghat/issues/224 ?

**Comment by RCheesley** [comment]
Yes, perfect! Will add my comments there!
