### ISSUE TITLE
No such index error on new dashboards

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab#279]
Hi folks,

Just updated and have all the new dashboards, but when I access them I get the following errors appear:

Timelion: Error: in cell #1: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="all_enriched" & index_uuid="na" & index="all_enriched" }
Visualize: Error: in cell #1: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="all_enriched" & index_uuid="na" & index="all_enriched" }

Not sure if maybe there's some problem with deprecated fields and the like, as I had another issue with a field which was still present and had been deprecated in the latest release.

**Comment by valeriocos** [comment]
Hi @RCheesley ,

Can you post the result of the command `GET _aliases` (you can executed from the dev tools in Kibiter). Thanks

**Comment by RCheesley** [comment]
Sure, here you are:

`{
  "slack_demo_raw": {
    "aliases": {
      "slack-raw": {}
    }
  },
  "discourse_demo_enriched": {
    "aliases": {
      "discourse": {}
    }
  },
  "meetup_demo_enriched": {
    "aliases": {
      "meetup": {}
    }
  },
  "slack_demo_enriched": {
    "aliases": {
      "slack": {}
    }
  },
  ".kibana": {
    "aliases": {}
  },
  "github_demo_raw": {
    "aliases": {
      "github-raw": {}
    }
  },
  "git_demo_raw": {
    "aliases": {
      "git-raw": {}
    }
  },
  "git-onion_demo_enriched": {
    "aliases": {
      "all_onion": {}
    }
  },
  "github_demo_enriched": {
    "aliases": {
      "github_issues": {},
      "github_issues_enrich": {},
      "issues_closed": {},
      "issues_created": {},
      "issues_updated": {}
    }
  },
  "git_demo_enriched": {
    "aliases": {
      "affiliations": {},
      "demographics": {},
      "git": {},
      "git_author": {},
      "git_enrich": {}
    }
  },
  "git-aoc_demo_enriched": {
    "aliases": {
      "git_areas_of_code": {}
    }
  },
  "meetup_demo_raw": {
    "aliases": {
      "meetup-raw": {}
    }
  },
  "discourse_demo_raw": {
    "aliases": {
      "discourse-raw": {}
    }
  }
}`

**Comment by valeriocos** [comment]
The problem is due to the fact the `all_enriched` is not set in your indices. Furthermore, you miss also other aliases, which are declared at https://github.com/chaoss/grimoirelab-sirmordred/blob/master/aliases.json.

Could you enter in the mordred container and check that the aliases.json is aligned with the one pointed to the link above?

To add the missing aliases, please execute the following commands in the dev tools:

```
POST /_aliases
{
    "actions" : [
        { "add" : { "index" : "discourse_demo_enriched", "alias" : "affiliations" } },
        { "add" : { "index" : "discourse_demo_enriched", "alias" : "all_enriched" } },
        { "add" : { "index" : "meetup_demo_enriched", "alias" : "affiliations" } },
        { "add" : { "index" : "meetup_demo_enriched", "alias" : "all_enriched" } },
        { "add" : { "index" : "slack_demo_enriched", "alias" : "affiliations" } },
        { "add" : { "index" : "slack_demo_enriched", "alias" : "all_enriched" } },
        { "add" : { "index" : "github_demo_enriched", "alias" : "affiliations" } },
        { "add" : { "index" : "github_demo_enriched", "alias" : "all_enriched" } },
        { "add" : { "index" : "github_demo_enriched", "alias" : "all_enriched_tickets", "filter" : {
              "terms" : {
                "pull_request" : ["false"]
              }
            } } }
    ]
}
```
This command will add the missing aliases

```
GET /_aliases
```
This command will list the aliases, if everything goes OK, you should see the new aliases `affiliations`, `all_enriched` and `all_enriched_tickets` .

**Comment by RCheesley** [comment]
Happy days, that fixed the issue completely! Guess it must have been a problem as a result of updating the version of the container :) Thanks for the help!

**Comment by valeriocos** [comment]
great! you're welcome!
