### ISSUE TITLE
Track multiple Discourse instances

### ISSUE THREAD

**Issue by hmitsch** [chaoss/grimoirelab#28]
We would like to be able to have more than one Discourse instance in our Community Analytics stack. It is currently of secondary concern on whether or not these multiple instances will be visualized in one dashboard or in multiple-dashboards (tabs).

-Henrik

**Comment by jgbarah** [comment]
Thanks, @hmitsch for the proposal. I understand that what you mean is having the chance of specifying more than one Discourse instance when you specify the list of repositories to analyze, right?

If this is the case, I think this needs to be supported in mordred. Am I right, @acs ?

**Comment by acs** [comment]
Yes, this should be supported in mordred but not only. In our projects.json format that defines the data sources to be analyzed, only one discourse site can be added. The categories for this unique discourse site are then mapped to projects. Supporting having more than one discourse site will have impact in both places: mordred and projects definition (GrimoireELK).

**Comment by sduenas** [comment]
This is already possible using tags in the mordred configuration:

```
[discourse:site1]
raw_index = discourse_raw
enriched_index = discourse_enriched
no-archive = true

[discourse:site2]
raw_index = discourse_raw
enriched_index = discourse_enriched
no-archive = true
```
This [section](https://github.com/chaoss/grimoirelab-sirmordred#discourse-) describes how to configure the platform for discourse.
