### ISSUE TITLE
docker-compose setup : unexpose mariadb

### ISSUE THREAD

**Issue by mhow2** [chaoss/grimoirelab#283]
The following docker-compose statement at https://github.com/chaoss/grimoirelab/blob/10846f897181d8bc755ef96e0a52f3c111289a3e/docker-compose/docker-compose-secured.yml#L8-L9

publish the port as to make it available to the external world, which is not what we could expect : I think we only want mariadb to be reachable from others containers only (by using `links`)

**Comment by valeriocos** [comment]
Fixed with #290
