### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by ederag** [chaoss/grimoirelab#297]
Following https://chaoss.github.io/grimoirelab-tutorial/basics/install.html (nice docs, by the way !)
on openSUSE Leap-15.1

```bash
venvwrapper -c grimoire  # creates and activates a 'grimoire' venv
pip3 install --upgrade pip
pip3 install --upgrade setuptools
pip3 install --upgrade wheel 
pip3 install grimoirelab

ERROR: sortinghat 0.7.7 has requirement pandas==0.22.0, but you'll have pandas 1.0.1 which is incompatible.
ERROR: grimoire-elk 0.63.0 has requirement pandas==0.22.0, but you'll have pandas 1.0.1 which is incompatible.
ERROR: grimoire-elk 0.63.0 has requirement redis<=2.10.6,>=2.10.0, but you'll have redis 3.0.0 which is incompatible.
ERROR: grimoire-elk 0.63.0 has requirement requests==2.21.0, but you'll have requests 2.23.0 which is incompatible.

grimoirelab -v
GrimoireLab 0.2.32
```

There were errors above, but they do not seem related to the main issue:
```bash
p2o.py --enrich --index git_raw --index-enrich git \
  -e http://localhost:9200 --no_inc --debug \
  git https://github.com/grimoirelab/perceval.git

2020-02-22 15:46:47,737 Debug mode activated
2020-02-22 15:46:47,737 Feeding raw from git (git_raw)
2020-02-22 15:46:47,741 Retrying (Retry(total=20, connect=20, read=8, redirect=5, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f1a6a7d30>: Failed to establish a new connection: [Errno 111] Connection refused',)': /
2020-02-22 15:46:48,142 Retrying (Retry(total=19, connect=19, read=8, redirect=5, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f1a6b0c18>: Failed to establish a new connection: [Errno 111] Connection refused',)': /
...
```

Trying with ssh or giving a `--github-token <token>` did not change anything 
(in agreement with the doc).
What is strange is that `perceval` works just fine.

`elasticsearch-7.5.0` is on:
```
sudo /usr/sbin/rcelasticsearch status
* elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2020-02-22 13:18:36 CET; 15s ago
```
`kibana-7.2.0` is installed, not matching the `elasticsearch-7.5.0` version, but this is probably irrelevant at this stage, or is it ?
A search in the issues and the doc for a FAQ (found tools and tips) did not yield anything.

**Comment by ederag** [comment]
Thanks for the swift and accurate reply ! Indeed:
```bash
curl -XGET http://localhost:9200
curl: (7) Failed to connect to localhost port 9200: Connection refused

sudo sysctl vm.max_map_count
vm.max_map_count = 65530

sudo sysctl -w vm.max_map_count=262144
sudo sysctl vm.max_map_count
vm.max_map_count = 262144

sudo /usr/sbin/rcelasticsearch restart
curl -XGET http://localhost:9200
curl: (7) Failed to connect to localhost port 9200: Connection refused

sudo /usr/sbin/rcelasticsearch status
* elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2020-02-22 20:24:51 CET; 3min 54s ago
```

So the issue is clearly in my system.

> if you want to see GrimoireLab in action ...

Is it possible to use this docker approach to get information on a specific repo,
or is it showcasing on pre-defined examples only ? (the docs are very seductive already)

**Comment by valeriocos** [comment]
> Thanks for the swift and accurate reply ! Indeed:

You're welcome!

> Is it possible to use this docker approach to get information on a specific repo,
or is it showcasing on pre-defined examples only ? (the docs are very seductive already)

Yes, it's possible. Please follow the steps at https://github.com/chaoss/grimoirelab#using-docker-run and modify the setup.cfg and projects.json used (both files are at https://github.com/chaoss/grimoirelab/tree/master/default-grimoirelab-settings).

Details about how to modify the setup.cfg and projects.json for each data source supported by grimoirelab are available at: https://github.com/chaoss/grimoirelab-sirmordred#supported-data-sources. I can help to prepare the setup.cfg and projects.json if needed.

Note that if you want to add just more git repositories, you needed to modify only the projects.json as follows:
```
{
    "grimoirelab": {
      "meta": {
        "title": "GrimoireLab"
      },
      "git": [
          "https://github.com/chaoss/grimoirelab.git",
          "https://github.com/chaoss/grimoirelab-perceval.git",
          "https://github.com/chaoss/grimoirelab-toolkit.git"
        ]
    }
  }
```

In case you want to install nothing, you can rely on [cauldron.io](https://cauldron.io/), a reduced free SaaS version of GrimoireLab to analyze git, github, gitlab and meetup data.

**Comment by ederag** [comment]
The docker solution is big (2±0.5 GB) but works fine. Thanks !

**Comment by valeriocos** [comment]
thanks for the info @ederag ! The size of the image should be related to the issue https://github.com/chaoss/grimoirelab/issues/282
