### ISSUE TITLE
Evaluate removal of dashboards automatic upload 

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab#298]
In the current status GrimoireLab provides a feature to automatically upload a set of predefined dashboards. This feature can be enabled or disabled from the configuration file (i.e., setup.cfg). When this feature is on, the upload occurs every time grimoirelab is (re)started. 

Some of the drawbacks of this feature are:
- The complexity/maintainability of ELK (the component in charge of producing grimoirelab/enriched data) is higher since its logic has to deal with data processing and data visualization.
- Coupled evolution of the dashboards and enriched data, which prevents (for instance) to define and share different dashboards for the same enriched data.
- The automatic upload of the dashboards may wipe out custom changes. Thus, forcing the user to carefully check the setup.cfg when a restart of the platform occurs.

The goal of this issue is to evaluate the removal of this feature.

**Comment by sduenas** [comment]
This is already available.
