### ISSUE TITLE
Building docker on linux fails - expecting MacOS

### ISSUE THREAD

**Issue by arnonm-intel** [chaoss/grimoirelab#302]
Building grimoirelab dockers on linux fails, as utils/build_grimoirelab expects MacOS environment

def __init__
..
 self.system = system
        if self.system:
            self.name = "System"

Had to change last line to "/usr" to run on linux

**Comment by jgbarah** [comment]
Hmmm. Weird, as GrimoireLab developers are mainly Linux-based people. In any case, I myself am running it on Debian GNU/Linux right now, and I see no problem... Could you please let us know how you run it and what was the wrong output you got? (likely it is a command line option we don't use normally)

BTW, in which line you had to change that code? 359 maybe?

**Comment by arnonm-intel** [comment]
I ran the docker build command on the Dockerfile-installed 
docker build -f docker/Dockerfile-installed -t local-grimoirelab:installed .

**Comment by sduenas** [comment]
This is outdated, closing it.
