### ISSUE TITLE
Name of contributor should not be updated when name on Twitter changes

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab#305]
I changed my name on Twitter. I was delighted to see that the new name was correctly merged with my other identities in the chaoss.biterg.io dashboard.

I do think it is rather awkward that the "twitter name" is now shown everywhere in the dashboard. I see it common practice for someone to change their twitter name regularly to convey more information than just the name. 

This issue is about deprioritizing Twitter when selecting which name gets displayed on the dashboard. I believe other names should have higher priority.

Here is my example:
<img width="322" alt="Screen Shot 2020-03-07 at 6 47 19 AM" src="https://user-images.githubusercontent.com/8862021/76145591-86dc1d80-603f-11ea-9470-a28da5f9bda6.png">
<img width="519" alt="Screen Shot 2020-03-07 at 6 42 58 AM" src="https://user-images.githubusercontent.com/8862021/76145595-88a5e100-603f-11ea-9301-ad9e6a08bcbc.png">

**Comment by valeriocos** [comment]
GrimoireLab defines identities as tuples composed of email, name and username. If a user changes one of these attributes, the platform will consider the new tuple as a new identity (see image below).

![captura_242](https://user-images.githubusercontent.com/6515067/76201051-f0e8f400-61f2-11ea-803d-6b66a43d1d57.png)

The platform automatically merges the identities of the same user, and randomly selects a unique identity (in your case `Georg J.P. Link at Scale 18x`). The profile information is based on the unique identity data, however the profile information:
- can be modified via HatStall (I just did it) 
- add the autoprofile option (https://github.com/chaoss/grimoirelab-sirmordred#sortinghat), which allows to assign a priority on the data sources filling the profile (which is equivalent to what you are suggesting).

**Comment by GeorgLink** [comment]
> If a user changes one of these attributes, the platform will consider the new tuple as a new identity

That is a sensible behavior over all. For Twitter, this does not make sense though because of how people use the name field.

> can be modified via HatStall (I just did it)

That's what I want to avoid.

> add the autoprofile option (https://github.com/chaoss/grimoirelab-sirmordred#sortinghat), which allows to assign a priority on the data sources filling the profile (which is equivalent to what you are suggesting).

Yes, that's what I was thinking of. Twitter should have a low priority by default, in my opinion.

**Comment by valeriocos** [comment]
The priority can be set like: `autoprofile = ["github", "git", "twitter]`. In this case, twitter will be at priority 3

**Comment by GeorgLink** [comment]
awesome, thanks!
