### ISSUE TITLE
How can I set ssl_verify=false in grimoire config file for a specific perceval backend type: github?

### ISSUE THREAD

**Issue by javierjeronimo** [chaoss/grimoirelab#314]

**Comment by valeriocos** [comment]
Hi @javierjeronimo, please try

```
[github]
api-token = xxx
no-archive = true
raw_index = github_xxx
enriched_index = github_xxx_enriched
sleep-for-rate = true
no-ssl-verify = true
```

Let me know if this solves your issue, thanks!

**Comment by valeriocos** [comment]
Hi @javierjeronimo, let's close this issue, feel free to reopen it if needed.

**Comment by pilayar76** [comment]
Hi @valeriocos  - I am facing ssl certificate issue as below while calling private git.

server certificate verification failed. CAfile: none CRLfile: none
