### ISSUE TITLE
Time to close vs. Time to first close

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab#318]
Does GrimoireLab support for issues or PRs that were reopened to have the information of time to `time to close` and `time to first close`?

This was something we discussed today in the CHAOSS Common Metrics WG and I'm curious.

The [GitHub Issues](https://github.com/chaoss/grimoirelab-elk/blob/master/schema/github_issues.csv) index schema only has `time_to_close_days`. Is that the time to the final close? 🤔

**Comment by sduenas** [comment]
We only track the last date to close.
