### ISSUE TITLE
rate limit of github

### ISSUE THREAD

**Issue by Julianbaozi** [chaoss/grimoirelab#327]
When I fetch github raw data for one repository, does it send just one request to github or many requests? If there are many requests, how can I set the request proxies seperately?

**Comment by jgbarah** [comment]
It sends several requests, until it retrieves data about all issues and pull requests (the git repository is done with the git backend, which clones the repo, and therefore doesn't consume API rate.

What do you mean by "set the request proxies"?

**Comment by Julianbaozi** [comment]
How many requests per repository usually? And how can I see all the request choose what request to send?

**Comment by Julianbaozi** [comment]
What if I only want the basic information of the issue like time, and I don't care about user information.

**Comment by vchrombie** [comment]
> What if I only want the basic information of the issue like time, and I don't care about user information.

AFAIK, Perceval gets the complete log and if we need only some data in that then the better way would be storing them into JSON documents and using python/preferred language to parse the JSOC documents. 
There is another way too. You can use Perceval as a python module, retrieve the data and then parse it.

This might be useful, https://chaoss.github.io/grimoirelab-tutorial/perceval/github.html#retrieving-from-a-python-script.

**Comment by valeriocos** [comment]
To complement @vchrombie's answer, you can execute the Perceval backend with the flag `--filter-classified`. For instance:
```
perceval github chaoss grimoirelab-perceval --sleep-for-rate -t ... --no-archive --filter-classified --category issue
```
This flag will remove the fields listed here: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L110

**Comment by mafesan** [comment]
Hi @Julianbaozi, did your question get solved? Please, let us know whether you need any further help or clarification. Thank you!

**Comment by Julianbaozi** [comment]
It’s solved. Thank you!

**Comment by mafesan** [comment]
Great @Julianbaozi , thank you for confirming it! 

In that case I'm closing the issue, feel free to re-open it if needed. Best!
