### ISSUE TITLE
Unable to connect to Elasticsearch at http://elasticsearch:9200

### ISSUE THREAD

**Issue by shikha0208** [chaoss/grimoirelab#328]
Hi ,

As instructed in grimoirelab , to run with docker compose the below command:
=> clone project
=>go to docker compose folder and run "docker-compose up -d"

Issue: I do this and go to localhost:5601 and it shows below page:
![image](https://user-images.githubusercontent.com/63613092/84087925-7f843180-a9eb-11ea-8c3b-368b45dcc12c.png)

https://user-images.githubusercontent.com/63613092/84087925-7f843180-a9eb-11ea-8c3b-368b45dcc12c.png

This says "Unable to connect to Elasticsearch at http://elasticsearch:9200".
If anyone knows , kindly help me and i am using this same project.

**Comment by valeriocos** [comment]
Hi @shikha0208 ,

The problem should be solved with increasing the virtual memory of ES: https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#low-virtual-memory-

**Comment by shikha0208** [comment]
Ok Thank you for the comment 
Could you please tell , how to increase virtual memory of ES in Windows 10 cmd shell /powershell?
As i see instructions for linux.

**Comment by valeriocos** [comment]
You're welcome @shikha0208 ,

GrimoireLab is developed on Linux, so I don't have an exact answer for your question. It seems that the commands below should work in your case:
```
docker-machine ssh
sudo sysctl -w vm.max_map_count=262144
exit
```
References:
- https://github.com/elastic/elasticsearch-docker/issues/92#issuecomment-318086404
- https://stackoverflow.com/questions/42111566/elasticsearch-in-windows-docker-image-vm-max-map-count

In case this solves your issue, it would be great if you can complete the troubleshooting section at https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#low-virtual-memory-

Thanks

**Comment by shikha0208** [comment]
Hi @valeriocos

Thank you for the comments.

**Solution:** I am using Windows 10 Enterprise and i just increased the Resources in docker settings (as mentioned in docker compose for grimoirelab )and executed  "docker-compose up -d" from gitbash.

I am able to see the dashboard finally.
Thanks and hence closing the issue.
