### ISSUE TITLE
Every time server has to restarted after making changes in projects.json file 

### ISSUE THREAD

**Issue by shikha0208** [chaoss/grimoirelab#332]
Hi .
 I would like to know , why do we have to run docker compose command everytime , after any changes are made in projects.json file to display the current results in the dashboard.

Changes like , if i want to add or remove the data from the file.

Kindly let me know .
Is there any solution without running the command and updates are available in the dashboard ?

**Comment by valeriocos** [comment]
Hi @shikha0208 ,

> Thank you.

You're welcome and sorry for the late reply.

> So basically i am using only this https://github.com/chaoss/grimoirelab and i would like to know in which file i can have a look to delete the repositories from json file and make what changes to get apt results in runtime as add is already working by the existing code.

The projects.json is in the grimoirelab-settings (https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml#L53) and it is copied in the container at `/home/bitergia/conf/projects.json`. You can access the container and modify the file (`docker exec -it <container-name> bash`).

If you find it convenient, we can meet on IRC (`freenode: \#grimoirelab`) and try to advance on this issue, wdyt?

**Comment by shikha0208** [comment]
Hi @valeriocos ,

Thank you for the reply.
Yes ,accessing the container is **via**  "docker exec -it <container-name> bash".
But in docker compose yaml , how do we access the container in runtime?
As in command line , i can write this command and perform changes .But how it is done in docker compose  file accessing the container and copy it to local host for the service?

Yes we can discuss , can we do it on slack?As IRC i have not used.

**Comment by valeriocos** [comment]
> Thank you for the reply.

You're welcome.

> But in docker compose yaml , how do we access the container in runtime?

You can:
- execute `docker ps` to list the containers running (there is no difference between the containers started from a docker-compose or from docker)
- execute `docker exec -it "container-name" bash`

For instance, in my machine I have 3 containers running
```
slimbook@slimbook-KATANA:~/docker$ docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                                NAMES
aee8159c724a        bitergia/kibiter:secured-v6.8.6-2      "/docker_entrypoint.…"   47 hours ago        Up 2 seconds        127.0.0.1:5601->5601/tcp             docker_kibana_1
0f475409862b        bitergia/elasticsearch:6.8.6-secured   "/docker-entrypoint.…"   47 hours ago        Up 3 seconds        8000/tcp, 127.0.0.1:9200->9200/tcp   docker_elasticsearch_1
4e94599254b3        mariadb:10.0                           "docker-entrypoint.s…"   47 hours ago        Up About a minute   0.0.0.0:3306->3306/tcp               docker_mariadb_1
```
If I want to enter into the mariadb container, I can do the following:
```
slimbook@slimbook-KATANA:~/docker$ docker exec -it docker_mariadb_1 bash
root@4e94599254b3:/# 
```

Once inside I can modify files and/or install packages:
```
root@4e94599254b3:/# apt update && apt-get install nano
```

In order to copy a file from/to a container, you can use `docker cp` (see https://docs.docker.com/engine/reference/commandline/cp/ for more details)

> Yes we can discuss , can we do it on slack?As IRC i have not used.

Ok, perfect! Which slack instance you want to use?

**Comment by shikha0208** [comment]
Hi @valeriocos ,

Thank you , i am able to access the container and make changes.

And i saw IRC , i am available at  IRC (freenode: \#grimoirelab).
I could not see your name.

Thank you again for all the answers.

**Comment by valeriocos** [comment]
you're welcome @shikha0208
