### ISSUE TITLE
 Error Timelion: Error: in cell #1: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="github_repositories" & index_uuid="na" & index="github_repositories" }

### ISSUE THREAD

**Issue by marcofranssen** [chaoss/grimoirelab#333]
**Kibana version**:
bitergia/kibiter:community-v6.8.6-2

**Elasticsearch version**:
docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.6

**Grimoirelab version**:
grimoirelab/installed:0.2.32

I'm getting the following error in Kibiter when navigating to the Github repositories overview.

```
Error Timelion: Error: in cell chaoss/grimoirelab-kibiter#1: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="github_repositories" & index_uuid="na" & index="github_repositories" }
```

Despite I have filled out `"github"` projects in my `projects.json`.

Other github data like PRs and things are properly populated.

What is required to get the `Github Repositories Overview` working?

**Comment by valeriocos** [comment]
Hi @marcofranssen ,

In your cfg, you should add:
- `github-repos = true` to the `panels` section
- the section `github:repo` as shown at: https://github.com/chaoss/grimoirelab-sirmordred#repo

In your projects.json, you should add:
- the section `github:repo` as shown at: https://github.com/chaoss/grimoirelab-sirmordred#repo

Please note that the repo stats are calculated from the time you started tracking them with GrimoireLab, they are not based on previous historical data.

**Comment by valeriocos** [comment]
Hi @marcofranssen , I close this issue feel free to reopen it if needed

**Comment by marcofranssen** [comment]
Following those instruction I do see the 2 indexes being created.

- github-repo_enriched (aliased as `github`)
- github-repo_raw

However the Github repositories Tab in Kibiter still errors with.

```
Error Timelion: Error: in cell chaoss/grimoirelab-kibiter#1: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="github_repositories" & index_uuid="na" & index="github_repositories" }
```

**Comment by valeriocos** [comment]
Please @marcofranssen check that the aliases.json in the container is equal to https://github.com/chaoss/grimoirelab-sirmordred/blob/master/aliases.json (in particular the part of `github:repo` https://github.com/chaoss/grimoirelab-sirmordred/blob/master/aliases.json#L219).

To fix the error, you need to change the aliases for the indexes `github-repo_raw` and `github-repo_enriched`. In the dev tools (see image below), you can execute the following command (the same results can be achieved with curl):
```
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "github-repo_raw",
        "alias": "github_repositories-raw"
      }
    },
    {
      "add": {
        "index": "github-repo_enriched",
        "alias": "github_repositories"
      }
    },
    {
      "remove": {
        "index": "github-repo_enriched",
        "alias": "github"
      }
    }
  ]
}
```

![captura_496](https://user-images.githubusercontent.com/6515067/85528434-267fe480-b60c-11ea-8777-81d161a7fd38.png)

Hope this helps

**Comment by marcofranssen** [comment]
Now I got the following errors streaming continuously.

So I mounted the aliases.json in my container.

```
grimoirelab_1  | 2020-06-26 10:12:02,326 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/philips-labs/tabia): unhashable type: 'dict'
grimoirelab_1  | Traceback (most recent call last):
grimoirelab_1  |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 154, in feed_backend
grimoirelab_1  |     elastic_ocean = get_elastic(url, es_index, clean, ocean_backend, es_aliases)
grimoirelab_1  |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/utils.py", line 260, in get_elastic
grimoirelab_1  |     analyzers=analyzers, aliases=es_aliases)
grimoirelab_1  |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elastic.py", line 110, in __init__
grimoirelab_1  |     self.add_alias(alias)
grimoirelab_1  |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elastic.py", line 239, in add_alias
grimoirelab_1  |     if aliases and alias in aliases:
```

**Comment by valeriocos** [comment]
Yes @marcofranssen it's version related, the line `grimoire_elk/elastic.py", line 239` doesn't match with the one in master. That change occured on Jan 24: https://github.com/chaoss/grimoirelab-elk/commit/9fa2e8036a24984f4a14aff86d34bc5cfc223e1d. 

A dirty work-around would be to enter to the container and update the code in /usr/local/lib/python3.5/dist-packages/grimoire_elk/elastic.py with the changes at https://github.com/chaoss/grimoirelab-elk/commit/9fa2e8036a24984f4a14aff86d34bc5cfc223e1d

**Comment by marcofranssen** [comment]
@valeriocos Do you know when a new version of the container will be released?

**Comment by valeriocos** [comment]
No, I can sync with @jgbarah to check when the image can be updated. If it isn't a problem for you, I would suggest to use the docker-compose solution, which is up-to-date with the latest release.
