### ISSUE TITLE
Git only importing 77 items

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab#338]
Hi folks, we started having some problems with Git on our[ dashboard](https://dashboard.mautic.org/goto/a9c438ad64dd7c7ca9658f4824d15bf7). 

We stopped having incoming new items for a few weeks, I have tried troubleshooting and have deleted both the Github and Git indexes which did manage to get things started again, however for some reason Github is working fine but Git only imports 77 items and no more. 

I have previously been doing some work trying to incorporate sentiment analysis but I have rolled back all the changes that have been made on the setup file and rebuilt the indexes since then so I don't think that it's related to the current issue.

Appreciate any pointers!

Here are the indices in case it is helpful

![screenshot-dashboard mautic org-2020 06 25-11_28_55](https://user-images.githubusercontent.com/2930593/85704595-5b596d80-b6d8-11ea-8dfd-60f252197f0c.png)

**Comment by valeriocos** [comment]
Hi @RCheesley , in your setup.cfg within the section `git` please add the param `latest-items=false`. This will force the collection of all Git data.

Please let me know how it goes, thanks. If you find it convenient, I'm on the IRC chat (#grimoirelab channel on freenode)

**Comment by RCheesley** [comment]
Perfect - that seems to have resolved the problem!

**Comment by RCheesley** [comment]
Spoke too soon - it just imported the latest 10 items and stopped again.  Added it like this:

```
[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]
latest-items=false
```

**Comment by valeriocos** [comment]
Latest-items is repeated twice, you should have just one: `latest-items = false`

**Comment by RCheesley** [comment]
Ooooh..... Sorry, did not realise it was an existing value as the instruction was to add it - must open eyes!

**Comment by RCheesley** [comment]
Perfect, sorry for my misunderstanding that fixed it!

**Comment by valeriocos** [comment]
No worries! you're welcome!

**Comment by valeriocos** [comment]
@RCheesley if the git data is fixed, you can restore the `latest-items` to `true`. This will prevent sending to ES data that is already sotred in ES.

If you have time, it would be great if you can contribute to the troubleshooting section in [mordred](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#troubleshooting-) with a Q&A to address the issue you reported.

Thanks!
