### ISSUE TITLE
Missing "Merging Contributions" section in the CONTRIBUTING.md

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#341]
I've found that [GrimoireLab's CONTRIBUTING.md](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md) is missing content for the [Merging Contributions section](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#merging-contributions).

Wouldn't it be nice to fill it with useful information to help potential code contributors to understand how their code could end in official GrimoireLab releases?

**Comment by crazyshrut** [comment]
hey developer, can you assign this to me?
I have already contributed in such doc.md files under GSSoc and they got merged.

**Comment by sduenas** [comment]
This is already done.
