### ISSUE TITLE
Understanding GrimoireLab Roadmap

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#343]
As commented in #340, the Roadmap is in [a wiki page](https://github.com/chaoss/grimoirelab/wiki/Roadmap-2020) but also somehow in [a project board](https://github.com/chaoss/grimoirelab/projects/1). But the project board doesn't have the same items than the wiki page, and it looks almost empty.

Do all the items in the wiki page need to be open as issues in GrimoireLab repository to place them in the board? If so, I could (and I would like) to help with this.

**Comment by sduenas** [comment]
I've just updated both, wiki and board. I created the tasks that were planned for 2020 and updated the board and the wiki with them.

Sorry but I should have done this before.
