### ISSUE TITLE
Discourse datasource doesn't work

### ISSUE THREAD

**Issue by velmurugan-balasubramanian** [chaoss/grimoirelab#356]
Hi, 

I just started exploring the software and was trying to add multiple data source, I was able to configure multiple git repositories, but for some reason, I couldn't configure a discourse forum as a data source. I am not sure if I'm doing things the right way, Here are my setup.cfg and project.json files 

default-grimoirelab-settings/projects.json
https://bin.acquia.com/?be692b8e7ffa7c3d#32yEwBRmTYAMBWwFFkXG85E42rDqm8vauGhKmtYNix81

default-grimoirelab-settings/setup.cfg
https://bin.acquia.com/?cccbe1429db2711b#GzxSzPPpK19cmiZ9vJLrfjj9dUG2W33mK2nHLKi5QcN8 

Thanks in advance :)

**Comment by vchrombie** [comment]
Hi @velmurugan-balasubramanian 
I just went through the configurations

Can you remove `(suggested)` and try again
```
  [discourse]
  raw_index = discourse_raw
  enriched_index = discourse_enriched
- no-archive = true (suggested)  <------
+ no-archive = true
```

Not sure if it would solve the problem, I felt it might be a reason.
Let us know if it works.

**Comment by velmurugan-balasubramanian** [comment]
hey @vchrombie  

I did try removing the (suggested) option, unfortunately, it did not work either! is there anything else that I might be doing wrong? 

discourse config wasn't available by default in setup.cfg. so, I copied it from here https://github.com/chaoss/grimoirelab-sirmordred#discourse-  maybe I just copied a wrong config?

**Comment by vchrombie** [comment]
Hi @velmurugan-balasubramanian 
I have tried this and I couldn't replicate any problem. Everything seems to work fine.

setup.cfg
```
[discourse]
raw_index = discourse_raw
enriched_index = discourse_enriched
no-archive = true
```
projects.json
```
{
    "potioncraft" : {
          "discourse": [
            "https://community.developers.freshworks.com/"
        ]
    }
}
```
log
```
/home/p0tt3r/chaoss/sources/VENV_DIR/bin/python /home/p0tt3r/chaoss/sources/grimoirelab-sirmordred/utils/micro.py --raw --enrich --panels --cfg ./setup.cfg --backends discourse
  2020-07-04 23:37:14,180 Reading projects data from  ./projects.json 
  2020-07-04 23:37:14,198 [discourse] collection phase starts
  2020-07-04 23:37:14,198 [discourse] collection starts for https://community.developers.freshworks.com/
Collection for discourse: starting...
...
...
  2020-07-04 23:39:45,492 Fetch process completed: 228 topics fetched
  2020-07-04 23:39:46,415 [discourse] Done collection for https://community.developers.freshworks.com/
  2020-07-04 23:39:46,417 [discourse] collection finished for https://community.developers.freshworks.com/
  2020-07-04 23:39:46,418 [discourse] collection phase finished in 00:02:32
Collection for discourse: finished after 00:02:32 hours
  2020-07-04 23:39:46,575 Loading raw data finished!
  2020-07-04 23:39:46,576 Reading projects data from  ./projects.json 
  2020-07-04 23:39:58,585 [discourse] enrichment phase starts
  2020-07-04 23:40:01,418 Created index https://localhost:9200/discourse_enriched
...
...
  2020-07-04 23:40:50,360 Loading enriched data finished!
  2020-07-04 23:40:55,299 Kibiter settings configured!
  2020-07-04 23:40:55,300 Dashboard panels, visualizations: uploading...
  ...
  ...
  2020-07-04 23:41:00,156 Dashboard bff9e0c0-fe16-11e8-8aac-ef7fd4d8cbad not imported from /home/p0tt3r/chaoss/sources/grimoirelab-sigils/panels/json/gitlab_merge_requests_efficiency.json. Newer or equal version found in Kibana.
  2020-07-04 23:41:00,203 Index Pattern 4381a740-bc0c-11e8-8aac-ef7fd4d8cbad not imported from /home/p0tt3r/chaoss/sources/grimoirelab-sigils/panels/json/gitlab_merge_requests-index-pattern.json. Newer or equal version found in Kibana.
  2020-07-04 23:41:00,203 Dashboard panels, visualizations: uploaded!
  2020-07-04 23:41:00,313 Dashboard menu: uploading for 6 ...
  2020-07-04 23:41:00,563 Removing old dashboard menu, if any
  2020-07-04 23:41:00,730 Adding dashboard menu
  2020-07-04 23:41:00,818 Dashboard menu: uploaded!
  2020-07-04 23:41:00,819 Panels creation finished!

Process finished with exit code 0
```
dashboard
![Screenshot_20200704_234422](https://user-images.githubusercontent.com/25265451/86518611-4dca8300-be50-11ea-817b-cd4f5e4b1f11.png)

**Comment by vchrombie** [comment]
@velmurugan-balasubramanian, would be interested to share some more info of any error or procedure you have followed?

**Comment by velmurugan-balasubramanian** [comment]
@vchrombie 
I followed the steps given in the README, cloned this repo and ran the following docker run command
![Screenshot 2020-07-05 at 1 57 34 AM](https://user-images.githubusercontent.com/16268887/86520517-e7029500-be62-11ea-8463-5d80c528b4d1.png)

Dashboard
![image](https://user-images.githubusercontent.com/16268887/86520531-0ef1f880-be63-11ea-9992-d4b12506f8fc.png)

setup.cfg 
`
[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = mariadb
user = root
password =
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown`
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
gitlab-issues = true
gitlab-merges = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

#[bugzillarest]
#raw_index = bugzillarest_demo_raw
#enriched_index = bugzillarest_demo_enriched
#no-archive = true

#[confluence]
#no-archive = true
#raw_index = confluence_demo_raw
#enriched_index = confluence_demo_enriched

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]


[discourse]
raw_index = discourse_raw
enriched_index = discourse_enriched
no-archive = true

# [github]
# api-token = 
# enterprise-url = 
# raw_index = github_demo_raw
# sleep-for-rate = true
# sleep-time = "300"
# enriched_index = github_demo_enriched

#[gitlab:issues]
#api-token = <YOUR_API_TOKEN_HERE>
#raw_index = gitlab_issues_demo_raw
#enriched_index = gitlab_issues_demo_enriched
#no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
#sleep-for-rate = true

#[gitlab:merge]
#api-token = <YOUR_API_TOKEN_HERE>
#raw_index = gitlab_merges_demo_raw
#enriched_index = gitlab_merges_demo_enriched
#no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
#category = merge_request
#sleep-for-rate = true

#[jira]
#raw_index = jira_demo_raw
#enriched_index = jira_demo_enriched
#no-archive = true

#[pipermail]
#raw_index = pipermail_demo_raw
#enriched_index = pipermail_demo_enriched
#no-verify = true

#[mediawiki]
#raw_index = mediawiki_demo_raw
#enriched_index = mediawiki_demo_enriched
#no-archive = true

#[meetup]
#raw_index = meetup_demo_raw
#enriched_index = meetup_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = "300"

#[stackexchange]
#raw_index = stackexchange_demo_raw
#enriched_index = stackexchange_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[slack]
#raw_index = slack_demo_raw
#enriched_index = slack_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[supybot]
#raw_index = supybot_demo_raw
#enriched_index = supybot_demo_enriched

#[twitter]
#raw_index = twitter_demo_raw
#enriched_index = twitter_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = 300

## studies based on enriched indexes

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git-aoc_demo_enriched
out_index = git-onion_demo_enriched
contribs_field = hash
`

project.json 

`{
  "dev_platform": {
    "meta": {
      "title": "Freshworks Developer Platform"
    },
    "discourse": [
      "https://community.developers.freshworks.com/"
    ]
  }
}
`

are the only files I modified in the folder. 

Do I need to follow any additional steps?

**Comment by vchrombie** [comment]
Hi @velmurugan-balasubramanian 
I'm trying the docker solution. I will get back to you if I find something informative.

Also, on another note sometimes it might take some time to load the data and to display on the dashboard (can be up to 10 to 15 minutes). It would be great if you can check that case too, in case if you haven't.
Thanks.

**Comment by vchrombie** [comment]
Hi @velmurugan-balasubramanian 
Based on issue #242, I have found this hackaround for the problem.

define a project.json and dashboard.cfg in the grimoirelab repo folder

projects.json
```
{
  "dev_platform": {
    "meta": {
      "title": "Freshworks Developer Platform"
    },
    "git": [
      "https://github.com/freshdesk/crayons"
    ],
    "discourse": [
      "https://community.developers.freshworks.com/"
    ]
  }
}
```

dashboard.cfg
```
[general]
# Update incrementally, forever
update = true
# Don't start a new update earlier than (since last update, seconds)
min_update_delay = 300
# Produce debugging data for the logs
debug = true

[es_enrichment]
# Refresh identities and projects for all items after enrichment
autorefresh = true

[sortinghat]
# Run affilation
affiliate = True
# How to match to unify
matching = [email]
# How long to sleep before running again, for identities tasks
sleep_for = 100

[panels]
# Dashboard: default time frame
kibiter_time_from = "now-1y"
# Dashboard: default index pattern
kibiter_default_index = "git"

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
# Names for raw and enriched indexes
raw_index = git_freshworks-raw
enriched_index = git_freshworks
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
# Names for raw and enriched indexes
raw_index = github_freshworks-raw
enriched_index = github_freshworks
no-archive = true
# Sleep it GitHub API rate is exhausted, waited until it is recovered
sleep-for-rate = true

[github:prs]
# Names for raw and enriched indexes
raw_index = prs-github_freshworks-raw
enriched_index = prs-github_freshworks   
no-archive = true
# Sleep it GitHub API rate is exhausted, waited until it is recovered
sleep-for-rate = true
category = pull_request

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_freshworks-raw
out_index = git_aoc_freshworks-enriched

[enrich_onion:git]
in_index = git_sunbird
out_index = git_onion_freshworks-enriched

[discourse]
raw_index = discourse_freshworks-raw
enriched_index = discourse_freshworks-enriched
no-archive = true
```
now run the docker run command
```
$ docker run -p 5601:5601 -p 9000:9200 -v $(pwd)/projects.json:/projects.json -v $(pwd)/dashboard.cfg:/dashboard.cfg -t grimoirelab/full
```

Now, grimoirelab should be running and you can access kibiter at http://localhost:5601
```
p0tt3r@wand ~/chaoss/dump/grimoirelab            [4:01:42] 
> $ curl -XGET http://localhost:9000/_cat/indices
yellow open git_aoc_freshworks-enriched   gmX0JL6QQXK0Tby9pmp01Q 5 1 1668 0   5.5mb   5.5mb
yellow open git_freshworks-raw            G74j1krHQcSxGPMZK6ggzw 5 1  288 1 558.2kb 558.2kb
yellow open git_freshworks                0Jiwz2xmSBapj8SW7oYeSQ 5 1  288 0   2.8mb   2.8mb
yellow open discourse_freshworks-raw      xjtbWiKdS8WpEgQrMRlUTQ 5 1  228 1   3.4mb   3.4mb
yellow open .kibana                       sabH_BTvQti9SgNL0dezfQ 1 1  190 9 269.8kb 269.8kb
yellow open discourse_freshworks-enriched tZMJzmGMQWGD3nlaG-Wfjg 5 1 1186 6   4.3mb   4.3mb
```

![Screenshot_20200705_040648](https://user-images.githubusercontent.com/25265451/86522015-77e26c00-be75-11ea-8db3-8ae7084edb1f.png)
![Screenshot_20200705_040712](https://user-images.githubusercontent.com/25265451/86522017-79139900-be75-11ea-8c56-5cb2cc57a80c.png)

**Comment by velmurugan-balasubramanian** [comment]
hey @vchrombie 

your suggestion worked, thanks for your help, appreciate it :) 
also, what is the other way you were trying to start the application instead of docker, just curious!

**Comment by vchrombie** [comment]
Hi @velmurugan-balasubramanian 

> your suggestion worked, thanks for your help, appreciate it :)

Awesome, thanks for clarifying. :smile: 

> also, what is the other way you were trying to start the application instead of docker, just curious!

I assume you were asking about this, https://github.com/chaoss/grimoirelab/issues/356#issuecomment-653797357. There is another way to setup grimoirelab. We completely don't avoid in this case. We use docker for elasticsearch, kibiter, and mariadb but use the source code to build the grimoirelab. You can read more about it from here, [Getting-Started.md](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#source-code-and-docker-).

I also have another resource if you want to read about the docker solution, [SirMordred in a container](https://chaoss.github.io/grimoirelab-tutorial/sirmordred/container.html).

Let us know if you need any more information. :slightly_smiling_face:

**Comment by vchrombie** [comment]
Hi @valeriocos 
Do you want to add anything more, else we can close the issue?

**Comment by valeriocos** [comment]
Hi @vchrombie, thank you for helping on this issue. Feel free to close this issue.

If you find it useful, we could improve the sentence "your dashboard will be ready after a while" (I understand that the delay on the collection/enrichment phase was one of the problems) in the sections https://github.com/chaoss/grimoirelab#using-docker-compose and https://github.com/chaoss/grimoirelab#using-docker-run, wdyt?

**Comment by vchrombie** [comment]
> Hi @vchrombie, thank you for helping on this issue. Feel free to close this issue.

The maintainers or the author can close, so you can close it. ^^

> If you find it useful, we could improve the sentence "your dashboard will be ready after a while" (I understand that the delay on the collection/enrichment phase was one of the problems) in the sections https://github.com/chaoss/grimoirelab#using-docker-compose and https://github.com/chaoss/grimoirelab#using-docker-run, wdyt?

The current sentence looks good enough.
> Your dashboard will be ready after a while in `http://localhost:5601`

@valeriocos, do you have any more suggestions to add to make it more appropriate?

**Comment by valeriocos** [comment]
your dashboard will be ready after a while. The waiting time depends on the amount of data to fetch from a repo, for small repos you can expect your data to be visible in the dashboard after 10-15 minutes. wdyt?

**Comment by vchrombie** [comment]
> your dashboard will be ready after a while. The waiting time depends on the amount of data to fetch from a repo, for small repos you can expect your data to be visible in the dashboard after 10-15 minutes. wdyt?

I have opened a PR regarding this. How does it look?
