### ISSUE TITLE
Managing indexes and visualizations while data is loading

### ISSUE THREAD

**Issue by connorlindsey** [chaoss/grimoirelab#359]
Hi, 

For context, I'm running GrimoireLab via Mordred with `docker-compose-secured` and am using Git and GitHub data sources for around 15 repositories. 

Currently, to get the dashboards I want, I have to start up the docker containers with docker-compose and wait (sometimes it takes several hours if I'm including all the repos we want to watch) before the github_enriched index can be created from the management panel in Kibiter. With the index pattern created, I can then import my visualizations from json I previously saved. 

My goal is to automatically include the index patterns and visualizations in the config files so that there is no manual work required to get the dashboards running beyond running docker-compose and letting the data get collected. 

I have a few points I'm confused on and would love some clarification.

1. How can I automatically create the github index patterns? They're included in the setup.cfg file, but still need to be created in Kibiter when enough data has been collected. 
2. What happens to dashboards I've imported (say with a volume in docker-compose) when the index pattern they use isn't available? From what I've seen, it breaks some visualizations and requires re-making them once the index pattern is created. 

Any recommendations on how to automate this process would be greatly appreciated. Also, is it normal for it to take that long for the enriched github index to appear? Is there anything I can do to speed up that process? Thanks!

**Comment by zhquan** [comment]
Hi @connorlindsey,

The index patterns and the visualizations are created automatically if you activate `panels` in the section `phases` on the `setup.cfg`. They will be imported from [Sigils](https://github.com/chaoss/grimoirelab-sigils/tree/master/json)
```
[phases]
collection = true
identities = true
enrichment = true
panels = true
```
In the very first execution, you have to wait for the enriched indexes. 

If you created your own index patterns and visualization and you want to upload it you have to deactivate `panels` and using [Kidash](https://github.com/chaoss/grimoirelab-kidash) to export your current dashboard and then import to your new dashboard.

But if you want some visualizations but not all you have to activate the `panels` in the first execution, then deactivate it and restart the mordred container to avoid overwrite your changes.

The speed of the enrichment phase depends on the size of the repositories and the number of repositories.

>1. How can I automatically create the github index patterns? They're included in the setup.cfg file, but still need to be created in Kibiter when enough data has been collected.

The index patterns will be created automatically if you activate `panels`

>2. What happens to dashboards I've imported (say with a volume in docker-compose) when the index pattern they use isn't available? From what I've seen, it breaks some visualizations and requires re-making them once the index pattern is created.

The visualizations must be imported by [Kidash](https://github.com/chaoss/grimoirelab-kidash) to ensure they have the right format.

I hope it helps you.

Best,
Quan

**Comment by zhquan** [comment]
Did you have time to look at this issue @connorlindsey?

**Comment by zhquan** [comment]
Hi @connorlindsey,

I close the issue due to inactivity.

Reopen it if needed.

Best,
Quan
