### ISSUE TITLE
Kibana Readonly User Role

### ISSUE THREAD

**Issue by connorlindsey** [chaoss/grimoirelab#360]
Hi, I'm struggling to add a view only role to search guard (User should be able to view dashboards but not make any edits). I copied the sgconfig and added a user to `sg_internal_users` but I'm not sure which permissions would be required. 

I tried assigning the `readall` role which gives read access to all indexes. I think this is required to view data, but the user can still edit data. I also tried adding `sg_kibana_user` and only giving READ access like so

```
# sg_roles.yml
sg_kibana_readonly:
  readonly: true
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    "?kibana":
      "*":
        - READ
    "?kibana-6":
      "*":
        - READ
    "?kibana_*":
      "*":
        - READ
    "?tasks":
      "*":
        - INDICES_ALL
    "?management-beats":
      "*":
        - INDICES_ALL
    "*":
      "*":
        - indices:data/read/field_caps*
        - indices:data/read/xpack/rollup*
        - indices:admin/mappings/get*
        - indices:admin/get
```

I also tried adding a kibana.yml file to the sgconfig folder as described [Search Guard Docs](https://docs.search-guard.com/latest/kibana-read-only) without any success. 
`searchguard.readonly_mode.roles: ["sg_readonly"]`

Which roles / permissions should I give to create a readonly user? Thanks for the help!

**Comment by zhquan** [comment]
Hi @connorlindsey,

The role of only read permission is `readall`. You have to change the file `sgconfig/sg_internal_users.yml`.

i.e.
```
#password is: connor
connor:
  readonly: true
  hash: $2y$12$vabYJuIFm3kTRE2fLC5qIuHwCnenXXTXF3/S792hMjg7R1DltuMMm
  roles:
    - readall
```

I hope it helps you.

Best,
Quan

**Comment by connorlindsey** [comment]
Thanks Quan, I updated internal_users and restarted my containers. After logging in with the `readall` user, I can still edit dashboards. Are there other changes I need to make to reduce permissions?

**Comment by zhquan** [comment]
Hi @connorlindsey,

Yes, you can edit but you can't save the changes.

**Comment by connorlindsey** [comment]
Not sure what I messed up when I first tried this, but it's working. Thank you!
