### ISSUE TITLE
Missing GitHub related stats like GitHub issues,GitHub Pull request submitter's in the dashboard after using grimoirelab/full image

### ISSUE THREAD

**Issue by shikha0208** [chaoss/grimoirelab#361]
Hi Folks,

I am using grimoirelab/full docker image for the dashboard visualizations and given my token as per the format in credentails.cfg.
And ran this command, 
**`docker run -p 127.0.0.1:5601:5601 -v C:\test\credentials.cfg:/override.cfg -v C:\test\projects.json:/projects.json -t grimoirelab/full`**

I am able to see only git data in 5601 but the results not found for github data.

Kindly tell me , where i am not following the document.

Image link:
https://user-images.githubusercontent.com/63613092/86927709-f5d39b00-c133-11ea-8072-ef2e1389ab23.png

**Comment by jgbarah** [comment]
@shikha0208 sorry for the delay.

Did you wait for some time? GitHub data is retrieved via the GitHub API, which is much slower, and subject to token limits, than GitHub. For the standard data that is retrieved by the container by default, it may take at least 10 min, and likely more (maybe much more). You can see the progress in the log produced by the container.

If that doesn't work, please share the log shown by the container in your console.

**Comment by shikha0208** [comment]
Hi @jgbarah ,

Thank you .
Ya it is showing data but it takes a bit of longer time.
But i noticed that , i edited overview dashboard and saved it as new dashboard with different name which is with my changes.
And next time when i did docker-compose down and then docker-compose up -d.

1.I could not see my dashboard which i created with my changes.I could just see  the defaulted "OVERVIEW DASHBOARD"
I searched also but it was not present.
Kindly check this.

2.I am not able to see the data such as (forks,stars,subscribers) inside the Github Repositories heading , i get this error on the page.
PFA

https://user-images.githubusercontent.com/63613092/87170381-8eebe880-c2d1-11ea-92dc-0010d4edc0bb.png

Kindly have a look.

**Comment by shikha0208** [comment]
Issue is resolved Thank you
