### ISSUE TITLE
Managing Docker Image versions

### ISSUE THREAD

**Issue by connorlindsey** [chaoss/grimoirelab#363]
Hi, I'm running the full toolset with Docker-Compose and had two questions. 

1. Is there a release schedule or some recommended way to stay up to date with the latest images for Kibiter, Hatstall, Mordred, etc?
2. How does the bitergia/elastichsearch-secured image (in docker-compose-secured.yml) differ from the open source elasticsearch image? I'm assuming it just includes Search Guard, but is there anything else to keep in mind. 

Thanks!

**Comment by sduenas** [comment]
Hi @connorlindsey,

> Hi, I'm running the full toolset with Docker-Compose and had two questions.
> 
>     1. Is there a release schedule or some recommended way to stay up to date with the latest images for Kibiter, Hatstall, Mordred, etc?
> 

No, we don't have any official schedule but usually we generate new releases every two weeks. However, we are trying to improve it and have a better scheduling. During the next months we're going to work on #240 actively. 

>     2. How does the bitergia/elastichsearch-secured image (in docker-compose-secured.yml) differ from the open source elasticsearch image? I'm assuming it just includes Search Guard, but is there anything else to keep in mind.
> 

You are right, it only includes Search Guard.

Hope that helped.

**Comment by connorlindsey** [comment]
Awesome, thanks for the info. I'll watch that issue. Thanks!
