### ISSUE TITLE
Can we customize `Visaulize`?

### ISSUE THREAD

**Issue by Alanscut** [chaoss/grimoirelab#369]
the current Visualize has offered more than 200 data view, such as  `git_commits_timezone` data table, can I get a Visualize `git_additions_timezone`? and other cutomized data view?

**Comment by GeorgLink** [comment]
Hi @Alanscut,

Yes. When you are logged in to the dashboard, you should have the permission to create new or modify existing visualizations and save under a new name.

The visualizations that come with GrimoireLab are the default visualizations to get you up and running faster.

Out of curiosity, how did you deploy GrimoireLab? Did you use the Docker-Compose solution?

**Comment by Alanscut** [comment]
Thanks! I have got what I need, and I found that `visualize` is powerful, I can make many different types of charts.
Yes, `docker-compose` is quite convinient, I just need to config `projects.json` and `setup.cfg`, then it works well.
