### ISSUE TITLE
dockerhub images need refresh

### ISSUE THREAD

**Issue by hogepodge** [chaoss/grimoirelab#372]
The grimoirelab images in dockerhub are several months out of date, leading to various issues when using current configurations. For example, elk was updated to process more advanced aliases.json files, and grimoirelab/full will fail on processing them because it is using a version prior to that change.

**Comment by cakiki** [comment]
I second @hogepodge's concern. Has the docker route been de-prioritized?

**Comment by sduenas** [comment]
Images are updated everytime a new tag is created.
