### ISSUE TITLE
Error trying to get information from github (github_demo_raw index)

### ISSUE THREAD

**Issue by flopezag** [chaoss/grimoirelab#376]
I have configured the setup.cfg to get information from github:
`
[github]
api-token = xxxx
enterprise-url = https://github.com
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched
`

And configured the corresponding projects to add the data:
`
      "github": [
          "https:/github.com/telefonicaid/fiware-orion"
          ],
`

Besides I add the corresponding menu.yaml content to show the information about the GitHub:
`
- name: GitHub PRs
  source: github
  icon: default.png
  index-patterns:
  - panels/json/github_issues-index-pattern.json
  menu:
  - name: Overview
    panel: panels/json/github_pull_requests.json
  - name: Backlog
    panel: panels/json/github_pull_requests_backlog.json
  - name: Timing
    panel: panels/json/github_pull_requests_timing.json
  - name: Efficiency
    panel: panels/json/github_pull_requests_efficiency.json

- name: GitHub Issues
  source: github
  icon: default.png
  index-patterns:
  - panels/json/github_issues-index-pattern.json
  menu:
  - name: Overview
    panel: panels/json/github_issues.json
  - name: Backlog
    panel: panels/json/github_issues_backlog.json
  - name: Timing
    panel: panels/json/github_issues_timing.json
  - name: Efficiency
    panel: panels/json/github_issues_efficiency.json
`

When I execute the docker-compose, mordred produce an error with the following information:
`
mordred_1        | 2020-08-26 08:56:52,854 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/telefonicaid/fiware-orion): 404 Client Error: Not Found for url: https://github.com/api/v3/repos/telefonicaid/fiware-orion/issues?per_page=100&sort=updated&state=all&since=1970-01-01T00%3A00%3A00%2B00%3A00&direction=asc
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 162, in feed_backend
mordred_1        |     ocean_backend.feed(**params)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 228, in feed
mordred_1        |     self.feed_items(items)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 244, in feed_items
mordred_1        |     for item in items:
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 226, in fetch
mordred_1        |     for item in self.fetch_items(category, **kwargs):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 300, in __fetch_issues
mordred_1        |     for raw_issues in issues_groups:
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 882, in fetch_items
mordred_1        |     response = self.fetch(url_next, payload=payload)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 864, in fetch
mordred_1        |     response = super().fetch(url, payload, headers, method, stream, auth)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 143, in fetch
mordred_1        |     response = self._fetch_from_remote(url, payload, headers, method, stream, auth)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 186, in _fetch_from_remote
mordred_1        |     raise e
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 181, in _fetch_from_remote
mordred_1        |     response.raise_for_status()
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
mordred_1        |     raise HTTPError(http_error_msg, response=self)
mordred_1        | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/api/v3/repos/telefonicaid/fiware-orion/issues?per_page=100&sort=updated&state=all&since=1970-01-01T00%3A00%3A00%2B00%3A00&direction=asc
`

And the elasticsearch instance produce as well an error, related to the github_demo_raw index:
`
elasticsearch_1  | [2020-08-26T08:57:03,155][DEBUG][o.e.a.s.TransportSearchAction] [QtwYi6f] [github_demo_raw][0], node[QtwYi6fwSHO9kyG-q7Zuyw], [P], s[STARTED], a[id=Fc1fKqrGRh2SIvIePMM0XQ]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[github_demo_raw], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=Scroll{keepAlive=10m}, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, source={"size":100,"query":{"bool":{"filter":[{"term":{"origin":{"value":"https://github.com/telefonicaid/fiware-orion","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},"sort":[{"metadata__timestamp":{"order":"asc"}}]}}] lastShard [true]
`

How can I get the information about the github? what is wrong in the configuration of the tools?

**Comment by sduenas** [comment]
If you are analyzing data from `github` you don't need to set `enterprise-url` parameter. Can you remove it and try it again?

**Comment by flopezag** [comment]
Ok, now there is no error (apparently) or I could not find it but the content in GitHub Issues and GitHub PRs are empty. Additionally, the portal show me an error in the option GitHub Repositories

Error: in cell #1: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="github_repositories" & index_uuid="_na_" & index="github_repositories" }

**Comment by sduenas** [comment]
Not sure what's going on. I guess you are trying to use the `grimoirelab` with the docker image. If that's the case, can you remove the image and recreate it again. You will start with a clean container and we can trace the problem better.

**Comment by flopezag** [comment]
After docker-compose down and up again, the problem with the GitHub Repositories persists.

The message that I obtained is:

`Timelion: Error: in cell #1: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="github_repositories" & index_uuid="na" & index="github_repositories" }`

And the following error in visualization:

`Error in visualization

Error: in cell #1: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="github_repositories" & index_uuid="_na_" & index="github_repositories" }`

Kibiter produces the following error:

`kibiter_1        | {"type":"log","@timestamp":"2020-08-31T19:13:20Z","tags":["timelion","error"],"pid":1,"message":"Error:  in cell #1: [index_not_found_exception] no such index, with { resource.type=\"index_or_alias\" & resource.id=\"github_repositories\" & index_uuid=\"_na_\" & index=\"github_repositories\" }: Error:  in cell #1: [index_not_found_exception] no such index, with { resource.type=\"index_or_alias\" & resource.id=\"github_repositories\" & index_uuid=\"_na_\" & index=\"github_repositories\" }\n    at throwWithCell (/opt/kibana/src/legacy/core_plugins/timelion/server/handlers/chain_runner.js:50:11)\n    at /opt/kibana/src/legacy/core_plugins/timelion/server/handlers/chain_runner.js:185:13\n    at arrayEach (/opt/kibana/node_modules/lodash/index.js:1315:13)\n    at Function.<anonymous> (/opt/kibana/node_modules/lodash/index.js:3393:13)\n    at /opt/kibana/src/legacy/core_plugins/timelion/server/handlers/chain_runner.js:177:24\n    at tryCatcher (/opt/kibana/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/opt/kibana/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/opt/kibana/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/opt/kibana/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/opt/kibana/node_modules/bluebird/js/release/promise.js:694:18)\n    at Promise._fulfill (/opt/kibana/node_modules/bluebird/js/release/promise.js:638:18)\n    at SettledPromiseArray.PromiseArray._resolve (/opt/kibana/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at SettledPromiseArray._promiseResolved (/opt/kibana/node_modules/bluebird/js/release/settle.js:16:14)\n    at SettledPromiseArray._promiseRejected (/opt/kibana/node_modules/bluebird/js/release/settle.js:32:17)\n    at Promise._settlePromise (/opt/kibana/node_modules/bluebird/js/release/promise.js:576:26)\n    at Promise._settlePromise0 (/opt/kibana/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/opt/kibana/node_modules/bluebird/js/release/promise.js:690:18)\n    at _drainQueueStep (/opt/kibana/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/opt/kibana/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/opt/kibana/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)"}
`

**Comment by sduenas** [comment]
After restarting the container, did you get data from issues and PRs? From your last comment is not clear to me. If it didn't work, 
would you mind to paste your configuration and projects files?

If you want to configure the platform to retrieve repositories info from GitHub you need to add this to the configuration file:
```
[github:repo]
raw_index = github_pulls_chaoss
enriched_index = github_repo_enriched
category = repository
no-archive = true
```

And add repositories to the `projects.json` file adding the next entry

```
    "github:repo": [
            "https://github.com/chaoss/grimoirelab-perceval"
    ]
```

**Comment by vchrombie** [comment]
Also, adding to @sduenas's comment, I would suggest you wait for some time (at least 10-15 min) for mordred to start the fetching process. It might take time depending on the size.
Please ignore, if you have already done it.

Thanks.

**Comment by flopezag** [comment]
I can confirm that it is working now. The github:repo information was produced due to a mistake in the configuration of the setup.cfg. The correct values are:

```
  [github:repo]
  raw_index = github_repo_raw
  enriched_index = github_repo_enriched
  api-token = {{github_api_token}}
  category = repository
  sleep-for-rate = true
  no-archive = true
```
My mistake was that I used ```raw_index = github-repo_raw``` and ```enriched_index = github-repo_enriched```.

Now I have information about GitHub Repositories, GitHub PRs and GitHub Issues.

**Comment by sduenas** [comment]
Good to hear that! I'm closing this ticket.
