### ISSUE TITLE
Strange user aggregation rules

### ISSUE THREAD

**Issue by Alanscut** [chaoss/grimoirelab#377]
Hi all,

This tools help me a lot, but I have some questions about the rule of author aggregation.
this is my test repo: [https://github.com/Alanscut/test_commit](https://github.com/Alanscut/test_commit),
I used different usernames and emails to submit the code, and some were submitted online. However, the author of the aggregation seems to be somewhat different from the actual situation. Is there any description of the aggregation rules?

I totally used 3 accounts:
account | name | email
-- | -- | --
[Alanscut](https://github.com/Alanscut)|name:Alan Wang | 948467222@qq.com(primary) / wp_scut@163.com
[Alanwang2015](https://github.com/Alanwang2015) | Alan Wang | alanwang.sdu@gmail.com
[AlanWang996](https://github.com/AlanWang996) | null | wangpenglion@foxmail.com

but the aggregation result only show me 2 authors, some commits of `Alanwang2015` and `AlanWang996` are attributed to `Alanscut`, I'm very curious about this logic, but I didn't find any introduction of it.

author_name | author_domain | committer_name | hash | commit_date | account | username | email | commit online
-- | -- | -- | -- | -- | -- | -- | -- | --
Alan Wang | qq.com | GitHub | 61bfeb | August 10th 2020,   17:56:22.000 | Alanscut | Alan Wang(github   account name) | 948467222@qq.com | YES
Alan Wang | 163.com | Alanscut | b9041c | August 10th 2020,   19:11:05.000 | Alanscut | Alanscut | wp_scut@163.com |  
Alan Wang | 163.com | Alan_scut | a45428 | August 10th 2020,   19:12:55.000 | Alanscut | Alan_scut | wp_scut@163.com |  
Alan Wang | qq.com | Alanscut | 14f3fa | August 10th 2020,   19:16:06.000 | Alanscut | Alanscut | 948467222@qq.com |  
Alan Wang | foxmail.com | Alanscut | 1ea8d5 | August 10th 2020,   19:17:15.000 | AlanWang996 | Alanscut | wangpenglion@foxmail.com |  
Alan Wang | foxmail.com | Alan Wang | 7fa030 | August 10th 2020,   22:45:04.000 | AlanWang996 | Alan Wang | wangpenglion@foxmail.com |  
Alanwang2015 | gmail.com | Alanwang2015 | 23cb7c | August 18th 2020,   00:26:35.000 | Alanwang2015 | Alanwang2015 | alanwang.sdu@gmail.com |  
Alanwang2015 | gmail.com | Alan Wang | 480346 | August 18th 2020,   00:31:50.000 | Alanwang2015 | Alan Wang | alanwang.sdu@gmail.com |  
Alanwang2015 | gmail.com | Alan Wang | 6184b1 | August 18th 2020,   01:28:31.000 | Alanwang2015 | Alan Wang | alanwang.sdu@gmail.com |  
Alan Wang | 163.com | Alanscut | 9a2eb3 | August 18th 2020,   01:30:34.000 | Alanscut | Alanscut | wp_scut@163.com |  
Alan Wang | users.noreply.github.com | GitHub | 0fe50f | August 18th 2020,   07:21:24.000 | Alanwang2015 | Alan Wang(github   account name) | 67811626+Alanwang2015@users.noreply.github.com | YES
Alan Wang | 163.com | GitHub | 1b03cd | August 18th 2020,   07:23:48.000 | Alanscut | Alan Wang | wp_scut@163.com |  
Alan Wang | 163.com | unknown | 976fb9 | August 18th 2020,   17:01:36.000 | Alanscut | unknown(not set   user.name) | wp_scut@163.com |  
Alanwang2015 | gmail.com | unknown | caaa07 | August 18th 2020,   17:03:45.000 | Alanwang2015 | unknown(not set   user.name) | alanwang.sdu@gmail.com |  
Alan Wang | users.noreply.github.com | GitHub | 5db042 | August 18th 2020,   22:51:53.000 | Alanwang2015 | Alan Wang | 67811626+Alanwang2015@users.noreply.github.com | YES
Alan Wang | foxmail.com | unknown | 802cae | August 19th 2020,   00:18:04.000 | AlanWang996 | unknown(not set   user.name) | wangpenglion@foxmail.com |  
Alan Wang | foxmail.com | unknown | ff70f8 | August 19th 2020,   00:20:08.000 | AlanWang996 | unknown(not set   user.name) | wangpenglion@foxmail.com |  

Best Regards,
Alan

**Comment by zhquan** [comment]
Hi @Alanscut,

The logic depends on your configuration (`setup.cfg`) there are several [ matching rules ](https://gitlab.com/Bitergia/c/FAQ/-/blob/master/how-to-identities/README.md#how-many-types-of-matching-do-exist). Check your parameter `matching` on the section `sortinghat`.

I hope it helps you.

Best,
Quan

**Comment by Alanscut** [comment]
@zhquan Thanks! It helps me a lot.
