### ISSUE TITLE
Grimoirelab Discourse: Incorrect url parameter (api_key instead of api-key), causes 403 forbidden url

### ISSUE THREAD

**Issue by dai-mk** [chaoss/grimoirelab#378]
In perceval 0.12.24 the url to access the discourse api is incorrect.

Perceval produces ` https://<snip>/latest.json?page=0&api_key=<snip>`

But it should be api-key, not api_key. 

Source: https://meta.discourse.org/t/403-error-during-multiple-api-calls/148346/4

Doesn't need to be a header field, though.

**Comment by sduenas** [comment]
Thanks for reporting this. They should have updated the API. I need to do some tests to confirm it.

**Comment by sduenas** [comment]
Can you try the latest version? I've been testing it against `discourse 2.6.0.beta1` and works fine:

```
perceval discourse --api-username <user> -t <token> <url>
```

**Comment by sduenas** [comment]
> I see that we are using 2.5.0.beta3, we will update and I'll get back to you on the results.

I don't think that's the real problem. I think you should use a newer version of Perceval.

**Comment by dai-mk** [comment]
Sure I can try a newer version of Perceval. Where can I find it? Is it in the current master branch of https://github.com/chaoss/grimoirelab-perceval ?

**Comment by sduenas** [comment]
Yes, you can use that one. Unfortunately we don't have an updated version of the pip package yet. We are changing the way we create releases, so I hope by the end of the next week, all the packages are updated.

**Comment by dai-mk** [comment]
Yes, the version from the git repo works (0.17.0). Seems like the version in docker image (0.12.24) is too outdated to work.

**Comment by sduenas** [comment]
Yes, I know. I'll generate a new updated version during the next week. I personally don't use that image and in Bitergia we don't use it either.

**Comment by dai-mk** [comment]
Hi @sduenas did you find some time to update the docker images on Dockerhub? I tried to build the latest images myself but it failed (https://github.com/chaoss/grimoirelab/issues/373)

**Comment by dai-mk** [comment]
> I personally don't use that image and in Bitergia we don't use it either.

May I ask how you run grimoirelab instead, what is the best practices for running it?
