### ISSUE TITLE
Dockerhub: How do you query official images?

### ISSUE THREAD

**Issue by dai-mk** [chaoss/grimoirelab#380]
For normale repos like 

`https://hub.docker.com/r/bitergia/kibiter`

this works fine

```
       "dockerhub": [
           "bitergia kibiter"
       ]
```

But what do you put into the setup.cfg for official Docker images like postgres.

`https://hub.docker.com/_/postgres`

because these don't work

       "dockerhub": [
           "_ postgres",
           " postgres"
       ]

Official repos have different URLs on dockerhub, the /r/ is missing and they have _ as owner.

**Comment by sduenas** [comment]
It should be:

```
"dockerhub": ["_ postgres"]
```
Tell me if that works for you.

**Comment by dai-mk** [comment]
Strange, now it works.
