### ISSUE TITLE
Update GL description on CHAOSS website

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab#381]
The [CHAOSS Software website](https://chaoss.community/software/) is evolving and we are asked to update the GrimoireLab section (chaoss/website#388).

I can work on this but I'm also happy if someone else wants to jump in and help.

**Comment by anajsana** [comment]
I'm currently working on Grimoirelab website, updating some content. I'm happy to take this issue and add new content to CHAOSS website :)

**Comment by msrijita18** [comment]
Hello, I'm a first time contributor. I would like to take this issue. Is it fine for me to assign it to myself?

**Comment by b-thebest** [comment]
Can I take up this issue

**Comment by vchrombie** [comment]
Hi @b-thebest

> Can I take up this issue

Thanks for popping in but I think the website is updated https://github.com/chaoss/website/pull/446 and I think we don't need anything more as of now.

@GeorgLink, can you close this issue for now? We can open a new one incase if we need something else. WDYT?

**Comment by b-thebest** [comment]
Okay,  I will contribute to other issues in future @vchrombie

**Comment by GeorgLink** [comment]
Yes, this issue is resolved. Thanks everyone!
