### ISSUE TITLE
Participate in Hacktoberfest 2020?

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab#382]
Do we want to participate in [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/)?

Basically, we would need to have well-defined issues (always a good idea) and apply a "Hacktoberfest" label to them so people can start working on them during Hacktoberfest. We need a good CONTRIBUTING.md (✅) and a Code of Conduct (maybe link to CHAOSS CoC?).

**Comment by sduenas** [comment]
Sure. I think we can do it. We are also participating on the GHC Open Source Day this year. We will need to create some guidelines and tag some issues for that event, so we can reuse them for this one too.

**Comment by GeorgLink** [comment]
👍

**Comment by y-martinez** [comment]
Hi @GeorgLink, I will participate in the GHC Open Source Day and I would like to contribute to this project but in the description of GHC form says that the participants should be comfortable using Kibana and ElasticSearch, so my question is, is really need it to contribute into this project?

**Comment by GeorgLink** [comment]
Hi @y-martinez. Yes, GrimoireLab builds on the Elasticsearch/Kibana stack and will not work without. There are parts of the project that can be improved without knowledge about Elasticsearch/Kibana.

**Comment by germonprez** [comment]
@sgoggins would you want to do this with Augur as well?
