### ISSUE TITLE
how to deploy this project in distributed mode?

### ISSUE THREAD

**Issue by Alanscut** [chaoss/grimoirelab#383]
hi all, 

If I configure thousands of projects, the ES will have performance problems when it is deployed in a single-node system. Does this project support distributed deployment? Is there any guidance? Thanks!

**Comment by sduenas** [comment]
There shouldn't be problems. Bitergia has been doing this for years. They provide a toolkit to deploy their platform in GCP:
https://github.com/bitergia-analytics/bap-deployment-toolkit
