### ISSUE TITLE
Install & Use

### ISSUE THREAD

**Issue by krushith7207** [chaoss/grimoirelab#385]
Hello Thanks for the GrimoireLab tool.
I am student working on thesis "Selection criteria for OSS projects".
As part of my thesis, I have developed a criteria for evaluating oss projects. In this process, I need to evaluate community metrics also. I tried using evaluating manually but it did not went well. I have found this amazing tool which evaluates community metrics. Unfortunately, I cannot run it on Mac. Could you please help me in this regard.
Thanks in advance.

**Comment by vchrombie** [comment]
Hi @krushith7207 
Thanks for your interest in GrimoireLab.

Our community member @GeorgLink has written a blog post for setting up GrimoireLab using docker. I feel that would be much helpful. https://chaoss.community/blog-post/2019/10/08/simplifying-how-to-install-grimoirelab/

Please check it and let us know how it goes.

Also, as we are active and discussing over this in the mailing list, would it make sense to close this issue?

**Comment by krushith7207** [comment]
Hi venu
Thanks for your reply.
I have tried using GeorgLink. I have not been successful.
As we are discussing, close the issue.
Thanks for your help.

**Comment by GeorgLink** [comment]
The instructions should also work on other platforms, not just Mac.

What stage in the instructions do you get stuck with?

**Comment by krushith7207** [comment]
Hi Georg
Thanks for your reply.
I have changed projects.json file & setup.cfg file .
Eventhough, I have not got any results showing the new projects.
Could you please help me out.
Regards
Kiran

**Comment by GeorgLink** [comment]
Can you share the files for us to take a look and try?

Did you restart the container after making the change?

**Comment by krushith7207** [comment]
https://gist.github.com/krushith7207/cfb1450055a30ca196146bec0dd2ed1a

**Comment by krushith7207** [comment]
Issue resolved

**Comment by GeorgLink** [comment]
Thanks for the update. What was the issue?
