### ISSUE TITLE
Can't get GitHub data, error `401 Client Error: Unauthorized for url`

### ISSUE THREAD

**Issue by nul800sebastiaan** [chaoss/grimoirelab#386]
I've been looking around this tracker, blog posts, docs etc. but I can't find the winning combination of getting GitHub data pulled in. 

`projects.json` 
```js
{
    "Umbraco": {
      "meta": {
        "title": "Umbraco-CMS"
      },
      "git": [
          "https://github.com/umbraco/Umbraco-CMS"
        ],
	  "github": [
          "https://github.com/umbraco/Umbraco-CMS"
	  ]
    }
  }
```

I also tried with `github:repo`, that never even did anything.

`setup.cfg`
```
[git]
raw_index = git_umbraco_raw
enriched_index = git_umbraco_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
api-token = xxxxxxxxxxxx
raw_index = github-repo_raw
enriched_index = github-repo_enriched
sleep-for-rate = true
category = repository
no-archive = true
```

As noted above, this used to say `[github:repo]` and nothing happened, changing to `[github]` at least it gave me an error when starting up.

I've generated an API key from 2 different accounts, but always immediately get rate limited, it seems. However, this also seems to happen before even getting any data at all:

![image](https://user-images.githubusercontent.com/304656/94142736-0829bf00-fe6f-11ea-8601-77c93e08cc47.png)

The error is as follows. What am I missing?

```
Collection for github: starting...

2020-09-24 11:59:32,216 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/umbraco/Umbraco-CMS): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit

Traceback (most recent call last):

File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend

ocean_backend.feed(**params)

File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 230, in feed

self.feed_items(items)

File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 246, in feed_items

for item in items:

File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 213, in fetch

self.client = self._init_client()

File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 285, in _init_client

self.archive, from_archive)

File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 609, in __init__

self._choose_best_api_token()

File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 908, in _choose_best_api_token

self._update_current_rate_limit()

File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 953, in _update_current_rate_limit

raise error

File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 945, in _update_current_rate_limit

response = super().fetch(url)

File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch

response = self._fetch_from_remote(url, payload, headers, method, stream, verify, auth)

File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote

raise e

File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote

response.raise_for_status()

File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status

raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit

Collection for github: finished after 00:00:01 hours
```

**Comment by sduenas** [comment]
Can you try to run `perceval` to get data from that repository using your token? Try with:

`perceval github -t <TOKEN> umbraco Umbraco-CMS`

**Comment by nul800sebastiaan** [comment]
@sduenas Thanks for your reply! I tried, but I need you to really spell it out for me please, as I don't understand how the syntax works.. I keep getting errors 🙈 

`perceval: error: the following arguments are required: owner, repository`

![image](https://user-images.githubusercontent.com/304656/94250266-48e21080-ff21-11ea-8366-61850cab93db.png)

**Comment by nul800sebastiaan** [comment]
Aha! It's the other way around `perceval github umbraco Umbraco-CMS -t xxxx` - this gives me results just fine! 

![image](https://user-images.githubusercontent.com/304656/94250722-e3daea80-ff21-11ea-838b-82447eb86682.png)

Not sure how to debug this further then..?

**Comment by sduenas** [comment]
Cool. That means that your token works, so it must be a problem with the configuration file. The configuration file should contains a setup for GitHub similar to the one below. Set your token in `api-token` parameter and change `raw_index`, `enriched_index` as you wish.

```
[github]
raw_index = github_issues_raw
enriched_index = github_issues_enriched
api-token = xxxx
sleep-for-rate = true
no-archive = true
category = issue
sleep-time = 300

[github:pull]
raw_index = github_pulls_raw
enriched_index = github_pulls_enriched
api-token = xxxx
sleep-for-rate = true
no-archive = true
category = pull_request
sleep-time = 300

[github:repo]
raw_index = github_repo_raw
enriched_index = github_repo_enriched
api-token = xxxx
category = repository
no-archive = true
```

**Comment by nul800sebastiaan** [comment]
Thanks @sduenas I have tried so many different combinations and still get the same errors, so I just copied yours here exactly (replacing the tokens indeed) and my `project.json` looks like this now:

```js
{
	"Umbraco": {
		"meta": {
			"title": "Umbraco-CMS"
		},
		"git": [
			"https://github.com/umbraco/Umbraco-CMS"
		],
		"github": [
			"https://github.com/umbraco/Umbraco-CMS"
		],
		"github:pull": [
			"https://github.com/umbraco/Umbraco-CMS"
		],
		"github:repo": [
			"https://github.com/umbraco/Umbraco-CMS"
		]
	}
}
```

I did a restart and then I'm stuck again. I feel like I'm so close and just missing one little thing, but no idea what it is haha!

![image](https://user-images.githubusercontent.com/304656/94260696-ec86ed00-ff30-11ea-8b60-aa14962bb5d6.png)

**Comment by sduenas** [comment]
@nul800sebastiaan I tested my version of GrimoireLab with your projects list and your configuration and works without problems. I think it is a problem related with an older version of a package inside the docker image. I would like to update the docker image during this week (I'm very late with that).

**Comment by nul800sebastiaan** [comment]
@sduenas Aha! That sounds great! Happy it's not me! I am absolutely unfamiliar with all the tech used in this software so I figured I was probably doing something wrong. Any nightlies I could try out in the mean time?

**Comment by choiwany** [comment]
> @nul800sebastiaan I tested my version of GrimoireLab with your projects list and your configuration and works without problems. I think it is a problem related with an older version of a package inside the docker image. I would like to update the docker image during this week (I'm very late with that).

Did you fix this problem? I also encountered the same problem.
and how can i do it myself,which image i need replace.

**Comment by vchrombie** [comment]
Hi, @nul800sebastiaan @choiwany. We had released a new version of GrimoireLab (0.2.52) almost a month ago.
Do you still find this issue, with the latest version?
Can you try this and let us know about it?

Thanks.

**Comment by fernanda-ordonez** [comment]
Hello, I've been finding the same issue. I'm using the latest version 0.2.69 and the following configuration files: 

{
    “BigDataBiology”: {
      "meta": {
        "title": "BigDataBiology"
      },
	  "github": [
          "https://github.com/BigDataBiology"
	  ]
    }
  }

[github]
api-token = xxxxxxxxxxxx
raw_index = github-repo_raw
enriched_index = github-repo_enriched
sleep-for-rate = true
category = repository
no-archive = true

I'm not sure what is going wrong...

**Comment by zhquan** [comment]
Hi @fernanda-ordonez 

Your projects.json is not correct due to the https://github.com/BigDataBiology is not a repository, try again but use a repository as https://github.com/BigDataBiology/SemiBin

```
{
    “BigDataBiology”: {
        "meta": {
            "title": "BigDataBiology"
        },
        "github": [
            "https://github.com/BigDataBiology/SemiBin"
        ]
    }
}
```

I see you are using `category = repository` which means you will have the number of forks, stars, and subscribers in the repository. More info about [categories](https://github.com/chaoss/grimoirelab-sirmordred#github-)

I hope it helps you.

**Comment by vchrombie** [comment]
@fernanda-ordonez were you able to fix the issue? If not, please feel free to open a new one.

**Comment by vchrombie** [comment]
Closing this issue since everything works fine. It was prolly a problem with an old docker image.
It is suggested to use the docker-compose solution for to use the latest version of GrimoireLab.
