### ISSUE TITLE
Cannot visualize github data on dashboard

### ISSUE THREAD

**Issue by krushith7207** [chaoss/grimoirelab#388]
Hi
As , I have seen issues before opening this issue. I came to know that github API is slow so I have been trying since two days. I cannot get data from github. Regarding gitlab , I can get data. 
projects.json
{
   "hector_slam":{
        "git":[
           "https://github.com/tu-darmstadt-ros-pkg/hector_slam"
        ],
        "github:issue":[
           "https://github.com/tu-darmstadt-ros-pkg/hector_slam"
        ],
        "github:pull":[
           "https://github.com/tu-darmstadt-ros-pkg/hector_slam"
        ]
     }
}
Setup.cfg
[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = mariadb
user = root
password =
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
gitlab-issues = true
gitlab-merges = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github:repo]
raw_index = github_repo_raw
enriched_index = github_repo_enriched
api-token = xxxx
category = repository
sleep-for-rate = true
no-archive = true

[github]
raw_index = github_issues_raw
enriched_index = github_issues_enriched
api-token = xxxx
sleep-for-rate = true
no-archive = true
category = issue
sleep-time = 300

[github:pull]
raw_index = github-pull_raw
enriched_index = github-pull_enriched
api-token = xxxx
category = pull_request
sleep-for-rate = true
no-archive = true

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash.

Please help me out, do I need to change any?
I am running on Mac using docker for desktop.

**Comment by vchrombie** [comment]
Hi @krushith7207, thanks for your interest in GrimoireLab.

I can see a few mistakes in the configurations. So, I feel the issue is because of that.

The config in setup.cfg should match the ones in the projects.json, I see that `github` and `github:issue` might be conflicting. I would suggest to have anything one. Also, I can see you have defined the `github:repo` configurations in the setup.cfg but haven't mentioned any data source in projects.json, please add an entry related to it if you are looking for repository results. Also make sure, you declare the repository config that in `[panels]` too.

projects.json
```
{
    "hector_slam":{
       "git":[
          "https://github.com/tu-darmstadt-ros-pkg/hector_slam"
       ],
-      "github:issue":[
+      "github":[
          "https://github.com/tu-darmstadt-ros-pkg/hector_slam"
       ],
       "github:pull":[
          "https://github.com/tu-darmstadt-ros-pkg/hector_slam"
+      ],
+      "github:repo":[
+         "https://github.com/tu-darmstadt-ros-pkg/hector_slam"
       ]
    }
}
```

setup.cfg
```
[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
gitlab-issues = true
gitlab-merges = true
github-repos = true <--------
```

Let us know how it goes for you.

**Comment by krushith7207** [comment]
Thanks for the reply.
As i have added in [panels]
github-repos = true .
I can visualise github data also.
Thanks for the help
