### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit    - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/apache/commons-io) & JIRA visualisation

### ISSUE THREAD

**Issue by krushith7207** [chaoss/grimoirelab#389]
Hi 
I am trying to fetch data from github & i got error HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit. | 2020-09-27 14:23:50,185 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/apache/commons-io): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit.

To track the issues of library , I have used https://issues.apache.org/jira/ in projects.json folder but I cannot visualise in dashboard. 
I am updating my projects.json & setup.cfg files. 
Kindly, help me out to proceed further.
Thanks in advance.

 {
     "commons-io":{
      "git":[
         "https://github.com/apache/commons-io"
      ],
      "github:pull":[
         "https://github.com/apache/commons-io"
      ],
      "github:repo":[
         "https://github.com/apache/commons-io"
      ],
      "jira":[
      "https://issues.apache.org/jira/"]
   }
}

Setup.cfg 

[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = mariadb
user = root
password =
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
gitlab-issues = true
gitlab-merges = true
github-repos = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github:repo]
raw_index = github_repo_raw
enriched_index = github_repo_enriched
api-token = xxxx
category = repository
sleep-for-rate = true
no-archive = true

[github:pull]
raw_index = github-pull_raw
enriched_index = github-pull_enriched
api-token = xxxx
category = pull_request
sleep-for-rate = true
no-archive = true

[jira]
raw_index = jira_raw
enriched_index = jira_enriched
no-archive = true
#backend-user = xxxx
#backend-password = xxxx

[pipermail]
raw_index = pipermail_demo_raw
enriched_index = pipermail_demo_enriched
no-verify = true

## studies based on enriched indexes

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash

Screenshot of dev tools
![image](https://user-images.githubusercontent.com/33978241/94368431-454ab700-00e4-11eb-9809-d5b0cb330f0c.png)

**Comment by vchrombie** [comment]
Hi @krushith7207 

> I am trying to fetch data from github & i got error HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit. | 2020-09-27 14:23:50,185 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/apache/commons-io): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit.

I think this is probably because the token might be expired. In that case, it take some time to restore. Either way, you can try this with the same token and test it once.

```
p0tt3r@wand ~ $ perceval github apache commons-io -t xxxx
```

It works fine for me.

> To track the issues of library , I have used https://issues.apache.org/jira/ in projects.json folder but I cannot visualise in dashboard.

The configurations look fine and there is nothing much to add WRT jira data source. I believe that the jira repo is too big, so it might take some really good time to fetch the raw data and then it has to enrich and finally the dashboard will be visible.

**Comment by sduenas** [comment]
@vchrombie The same error is reported in #386. @nul800sebastiaan checked the token with `perceval` but it worked. I guess there's something wrong with the docker image or similar.

**Comment by vchrombie** [comment]
Hi @krushith7207, we had released a new version of GrimoireLab (0.2.52) almost a month ago.
Do you still find this issue, with the latest version?
Can you try this and let us know about it?

Thanks.

**Comment by vchrombie** [comment]
The docker versions should probably be updated. It is advised to use the [docker-compose](https://github.com/chaoss/grimoirelab/tree/master/docker-compose) method to use the latest version of GrimoireLab.

Closing this issue since we don't have any updates about the problem.
Thank you everyone for participating in the discussion. Please open a new issue in case you have any issues.
