### ISSUE TITLE
GitHub team, members and repositories

### ISSUE THREAD

**Issue by marcofranssen** [chaoss/grimoirelab#396]
Is it possible to get Github Teams in Grimoirelab?

The idea would be to get an overview the teams, their members and the repositories they own.

Using that information I think it is possible to visualize cross-team boundary contributions to a repository.

Maybe there is already an equivalent feature available which I can use in the meantime to get such data. Would be great if this can be considered as a new feature.

**Comment by GeorgLink** [comment]
Hi Marco,

How do you plan to deal with members who are in multiple teams?

We’ve discussed this feature in the past and I don’t know whether or how much we support it yet.

A work-around could be to manually assign members to teams with SortingHat/Hatstall; only feasible for small teams.

Best,
Georg

**Comment by marcofranssen** [comment]
I think that could be handled similar like a developer who has contributed to several repositories. It just gives additional filtering/grouping capabilties.

E.g. show all repositories connected to TEAM-A. Or show all contributions in REPOSITORY-A not done by members of TEAM-A. I think that doesn't differ that much from the organization vs identities vs repositories functionality today.

I might need an extension on sirmordred/sortinghat/hatstall to get those Github teams automatically populated. 
A next step could be to add some dashboards in kibiter that ship out of the box.

I'm to unfamiliar with the codebase to judge feasibility or go more in detail. Looking forward to any thoughts and input from this great community.

**Comment by sduenas** [comment]
This issue is related to https://github.com/chaoss/grimoirelab/issues/211. Closing this in favor of the other one.
