### ISSUE TITLE
docker-compose_elasticsearch  crash too frequently！

### ISSUE THREAD

**Issue by ZHANG-SHINE** [chaoss/grimoirelab#398]
When I use grimoirelab to analysis 2000+ project, I found that the ES crash too frequently. My hardware has 8 CPUs, 32G memory RAM. What should I do? Thank you very much!
BTW when I open the dashboard website, the ES used CPU max to 600% and used the memory 2.9G.

**Comment by zhquan** [comment]
Hi @ZHANG-SHINE,

According to the specification that you shared, the maximum you can set to ES memory is 16G. What is your ES memory?

You can check the ES container log to get more information.

Best,
Quan

**Comment by ZHANG-SHINE** [comment]
Hi quan @zhquan,
 
I have followed the official guide to edit  jvm.options file to set heap size to 16g. However it seems doesn't work. Could you please say more detail? Thank you very much!

Best,
Zhang Shine

**Comment by zhquan** [comment]
@ZHANG-SHINE - Could you share your elasticsearch's docker-compose.yml file? and did you check the ES container logs?

**Comment by ZHANG-SHINE** [comment]
below is my docker-compose.yml.
```version: '2.2'

services:
    mariadb:
      image: mariadb:10.0
      expose:
        - "3306"
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      ports:
        - 3308:3306

    hatstall:
      image: grimoirelab/hatstall:latest
      environment:
        - DATABASE_DIR=/db/
        - ADMIN_USER=admin
        - ADMIN_PASS=admin
      ports:
        - 8000:80
      links:
        - mariadb
      volumes:
        - ../default-grimoirelab-settings/apache-hatstall.conf:/home/grimoirelab/apache-hatstall.conf
        - ../default-grimoirelab-settings/shdb.cfg:/home/grimoirelab/shdb.cfg

    elasticsearch:
      # image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.6
      image: elastic/elasticsearch:6.8.6
      command: elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
      ports:
        - 9200:9200
      environment:
        - ES_JAVA_OPTS=-Xms16g -Xmx16g
        - ANONYMOUS_USER=true

    kibiter:
      restart: on-failure:5
      image: bitergia/kibiter:community-v6.8.6-3
      environment:
        - PROJECT_NAME=Demo
        - NODE_OPTIONS=--max-old-space-size=1000
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      links:
        - elasticsearch
      ports:
        - 5601:5601

    mordred:
      restart: on-failure:5
      image: bitergia/mordred:latest
      volumes:
        - ../default-grimoirelab-settings/setup.cfg:/home/bitergia/conf/setup.cfg
        - ../default-grimoirelab-settings/aliases.json:/home/bitergia/conf/aliases.json
        - ../default-grimoirelab-settings/projects.json:/home/bitergia/conf/projects.json
        - ../default-grimoirelab-settings/organizations.json:/home/bitergia/conf/organizations.json
        - ../default-grimoirelab-settings/identities.yml:/home/bitergia/conf/identities.yml
        - ../default-grimoirelab-settings/.gitconfig:/home/bitergia/.gitconfig
        - /tmp/:/home/bitergia/logs
      mem_limit: 4g
```

**Comment by ZHANG-SHINE** [comment]
I have set the `ES_JAVA_OPTS=-Xms16g -Xmx16g` after deploying. Then I run the commond `docker-compose up --no-deps -d elasticsearch`. However I could not see any data in the website. My colleague told me that if I changed the yml, the data will be lost, and I have to recollect the data. 
Collecting data may use 1 week, so I can only check whether the problem is solved or not at one week later.

Another question,  why must I recollect the data after redeploy(changed the yml file) elastic search service?

**Comment by zhquan** [comment]
Hi @ZHANG-SHINE,

If you change the `docker-compose.yml` and when you execute `docker-compose up -d` it will recreate the containers so you will lose the data stored in the indexes. If you want your data stored permanently follow these steps https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#save-changes-made-in-dashboard-by-mounting-the-volume-in-es-.

I hope the error is fixed setting `ES_JAVA_OPTS=-Xms16g -Xmx16g`.

If you have any other questions, please open a new issue. This way it will be easier to find for anyone having the same question or problem in the future.

Best,
Quan

**Comment by ZHANG-SHINE** [comment]
Hi @zhquan ,

After changing docker setting, this problem has been solved. And this issue can be closed. Thank you very much!

Best,
ZhangShine
