### ISSUE TITLE
Discussion about CI

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab#400]
This issue is opened to initiate a discussion on the recent changes to Travis CI and their plans.

Recently, Travis CI has come up with some changes with their pricing plans. You can read more about it from here, [The Travis CI Blog: The new pricing model for travis-ci.com](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

TL;DR (some of the main points that might effect us from the blog posts)
- For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment). *(AFAIK, this is just one time)*
- When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
- We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
  - Your account name and VCS provider (like travis-ci.com/github/[your account name] )
  - How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)
- Usage will be tracked under your account information so that you can better understand how many credits/minutes are being used

Right now, the grimoirelab repositories are still under https://travis-ci.org but it has been greatly affecting the performance so far. The build time sometimes takes upto 2 hours to complete. The builds are comparitively fast in https://travis-ci.com, but it looks like we are already in the negative credit balance [CHAOSS - Travis CI](https://travis-ci.com/github/chaoss/).

Now that we are having a limitation for the builds, I think it is the best time to think and evaluate the different CI services like github actions, gitlab ci, travis-ci.com and make plans to move to the new service.

**Comment by GeorgLink** [comment]
Will Augur and GrimoireLab share the same minutes since both are part of github.com/chaoss ?
We might need to discuss this together CHAOSS-wide.

/cc @sgoggins @ccarterlandis @gabe-heim @ElizabethN

**Comment by sgoggins** [comment]
@GeorgLink  @ElizabethN : You should check my twitter account at @sgoggins  ... I am ... well ... SUPER pissed because not only is it not good community stewardship, they offer no way to fix the problem.

**Comment by sgoggins** [comment]
We ran out of credits 7 days ago.  The links they give you to resolve things are DEAD!!!

**Comment by ccarterlandis** [comment]
@GeorgLink yes, I believe we'd have to share minutes. The negative credits are Augur's fault, as I had absolutely no idea this pricing change even happened until we ran out of credits - sorry about that! I am strongly in favor of moving away from Travis for a variety of reasons, some (but not all) of which are related to this change. +1 to discussing this CHAOSS-wide, as it will likely have ramifications across the whole org. 

Also, @vchrombie you may have seen this already, but travis-ci.org will be deprecated entirely on December 31st - I believe this is why they started throttling performance

**Comment by vchrombie** [comment]
> Will Augur and GrimoireLab share the same minutes since both are part of github.com/chaoss ?
> We might need to discuss this together CHAOSS-wide.

Yes @GeorgLink, travis-ci is configured as per org level. So, all the repos who enabled travis-ci under CHAOSS share the credits.

> We ran out of credits 7 days ago. The links they give you to resolve things are DEAD!!!

True that @sgoggins. Even I had faced the same issue. :confused: 

We share the same feeling @ccarterlandis. It looks like a roadblock for travis-ci.

> Also, @vchrombie you may have seen this already, but travis-ci.org will be deprecated entirely on December 31st - I believe this is why they started throttling performance

Yeah, I read about it. I talked with @sduenas and right now evaluating other services like github actions but it doesn't seem too easy to move from a perfectly well-organized thing to a completely new service. :slightly_frowning_face: 

Also, I would like to add this extra point. I think we might need to re-think if we want to move to GitLab. I remember the last time we had a discussion around in May about this and we decided not to move. We had everything configured so well at that time and we were not really ready to take that step (I remember this was one of the many reasons). WDYT?

**Comment by ElizabethN** [comment]
It doesn't seem like there are very many options here, does it. It looks like we will either have to bite the bullet and migrate to GitHub Actions or bite a bigger bullet and move the whole org to GitLab & GitLab CI. Either option is going to be tedious, but my only question is how can the community help make this happen, whatever we decide? Is this something we can recruit volunteers to help with?

**Comment by GeorgLink** [comment]
> bite a bigger bullet and move the whole org to GitLab & GitLab CI

Related conversation from earlier this year: [Proposal: CHAOSS migration to GitLab](https://docs.google.com/document/d/1a5_mRWmWBE0yRm8lgBi0myEW7YwfRSgF9pQGR1_IPK0/edit#heading=h.zh5jrsxyxlxa) -- the proposal was rejected before, but maybe we can revisit now that the GitHub+Travis solution we were on is going away.

**Comment by vchrombie** [comment]
Hi everyone, a small update on this. I was working on adding GitHub Actions support to the existing GrimoireLab toolset so that we have the CI for the time being till we decide on the GitLab migration. And about the migration, I think we need to bring this topic to the next community call (I guess after the holidays).

I have completed adding the support for Perceval and Toolkit but I have all the others pending. I'm working on adding[ support for ELK](https://github.com/vchrombie/elk-test/actions), but it doesn't seem too easy, trying to fix the issues for more than a week. Hope to complete them soon before we end up with no CI.

**Comment by ElizabethN** [comment]
>I think we need to bring this topic to the next community call (I guess after the holidays).

@vchrombie I added this to the agenda for that meeting (January 5. 2021).

**Comment by Silona** [comment]
We would also love to host you at saopen.ieee.org ! If you would like a free option that is gitlab based.

**Comment by GeorgLink** [comment]
Hi @Silona, 

Interesting option. The integration with other tools like Big Blue Button and Mattermost is also tempting. 

* Would saopen.ieee.org limit the CD/CI pipeline resources? 
* Could we use saopen.ieee.org GitLab for repositories only, without changing governance, changing licenses, or other changes to the project? 
*  Would CHAOSS and therefore the Linux Foundation need to make a contract with IEEE?

Feel free to send me an email (georg@chaoss.community) so we don't distract from the original topic of this issue.

**Comment by sgoggins** [comment]
Update: For Augur the Travis-CI issues ended up being a hickup of Travis-CI's clunky execution, but right now things are working again. It seems as though our worst case scenario is paying $60/month to keep the testing and verification apparatus we wrote up and running. Right now it seems like that is significantly less costly than a platform change for Augur at least.

**Comment by vchrombie** [comment]
Hi everyone, I have another update on this.

> I have completed adding the support for Perceval and Toolkit but I have all the others pending. I'm working on adding[ support for ELK](https://github.com/vchrombie/elk-test/actions), but it doesn't seem too easy, trying to fix the issues for more than a week. Hope to complete them soon before we end up with no CI.

I have found the workaround for it and now we have github actions setup for almost all the GrimoireLab components. We are just one PR away. :rocket: 

Sorry, I couldn't attend the community call yesterday but I checked the minutes. :slightly_smiling_face:

**Comment by sduenas** [comment]
> We would also love to host you at saopen.ieee.org ! If you would like a free option that is gitlab based.

I'd like to hear also about it.

**Comment by sduenas** [comment]
Hi all,

after discussing with Venu and evaluating all the options, we're going to move to GitHub actions. The reasons are that GitHub actions - as it's obvious - is fully integrated with GitHub, the syntax is very similar to Travis, and there's a growing community around it.

In the future we can consider other options like Gitlab, but as the plans are to stay in GitHub, we prefer to keep using tools that fully integrated with it.

**Comment by vchrombie** [comment]
Hi all, a small update on this topic.

All the GrimoireLab components are successfully ported from Travis CI to GitHub Actions, which is now the new CI service. You can find more details from here, https://github.com/chaoss/grimoirelab/issues/405.

Thanks to everyone, who posted their valuable comments and suggestions. :slightly_smiling_face:
