### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab#405]
We have decided to move all the GrimoireLab components, at least for now, from Travis CI to GitHub Actions (https://github.com/chaoss/grimoirelab/issues/400#issuecomment-756022308).

Opening this issue to track the status of migration of all the components. We will be following this order. :slightly_smiling_face: 
- [x] toolkit https://github.com/chaoss/grimoirelab-toolkit/pull/31
- [x] perceval https://github.com/chaoss/grimoirelab-perceval/pull/711
- [x] perceval-*
  - https://github.com/chaoss/grimoirelab-perceval-opnfv/pull/32
  - https://github.com/chaoss/grimoirelab-perceval-mozilla/pull/55
  - https://github.com/chaoss/grimoirelab-perceval-puppet/pull/27
  - https://github.com/Bitergia/grimoirelab-perceval-finos/pull/18
  - https://github.com/chaoss/grimoirelab-perceval-weblate/pull/3
- [x] graal https://github.com/chaoss/grimoirelab-graal/pull/99
- [x] elk https://github.com/chaoss/grimoirelab-elk/pull/956
- [x] sortinghat https://github.com/chaoss/grimoirelab-sortinghat/pull/428
- [x] sirmordred https://github.com/chaoss/grimoirelab-sirmordred/pull/499
- [x] kingarthur https://github.com/chaoss/grimoirelab-kingarthur/pull/112
- [x] kidash https://github.com/chaoss/grimoirelab-kidash/pull/42
- [x] cereslib https://github.com/chaoss/grimoirelab-cereslib/pull/35
- [x] manuscripts https://github.com/chaoss/grimoirelab-manuscripts/pull/138
- [x] bestiary https://github.com/chaoss/grimoirelab-bestiary/pull/48
- [x] hatstall https://github.com/chaoss/grimoirelab-hatstall/pull/113

**Comment by sduenas** [comment]
@vchrombie can you confirm every component is already migrated to github actions?

**Comment by vchrombie** [comment]
> @vchrombie can you confirm every component is already migrated to github actions?

Hi @sduenas, we didn't have any recent development activities in manuscripts, bestiary, and hatstall. But, they are still dependent on Travis CI and it would be a problem in the future if we didn't move them now. So, I worked on their builds and opened the PRs respectively.

Once if you are done reviewing the existing PRs, we will be completely away from Travis CI and successfully moved GrimoireLab CI to GitHub Actions.

Please let me know your comments if any.
Thanks.

**Comment by sduenas** [comment]
I reviewed and merged those PRs. I think we can close this task.

**Comment by vchrombie** [comment]
> I reviewed and merged those PRs. I think we can close this task.

Thanks @sduenas! :slightly_smiling_face:
