### ISSUE TITLE
Docker releases are not doing consisent tagging

### ISSUE THREAD

**Issue by marcofranssen** [chaoss/grimoirelab#409]
It seems releases of grimoirelab components are not properly tagged.

E.g.

The `latest` tag has a different digest then the currently latest `grimoirelab-0.5.52` tag.

```
latest
Last pushed2 months agobybitergia
digest bb008bb5e9d5
```

```
grimoirelab-0.5.52
Last pushed2 months agobybitergia
digest cee48dae3189
```

Probably this is caused by rebuilding the image for every tag.

Similarly I also notice other releases have also been repushed 2 months ago. This makes the releases very unreliable for consumers.

In practice a new release should do something similar like this.

```
docker build . bitergia/mordred:latest
docker tag bitergia/mordred:latest bitergia/mordred:grimoirelab-0.5.52
docker tag bitergia/mordred:latest bitergia/mordred:grimoirelab-0.5

docker push bitergia/mordred:latest
docker push bitergia/mordred:grimoirelab-0.5.52
docker push bitergia/mordred:grimoirelab-0.5
```

This ensures all tags point to the same image layer digest. This also allows people to lock at the minor version number.

The next release you would do as following.

```
docker build . bitergia/mordred:latest
docker tag bitergia/mordred:latest bitergia/mordred:grimoirelab-0.5.53
docker tag bitergia/mordred:latest bitergia/mordred:grimoirelab-0.5

docker push bitergia/mordred:latest
docker push bitergia/mordred:grimoirelab-0.5.53
docker push bitergia/mordred:grimoirelab-0.5
```

This will cause the `latest` and `grimoirelab-0.5` tag to move its pointer to the new image layer digest and add a new tag `grimoirelab-0.5.53`. The existing `grimoirelab-0.5.52` tag will remain at the previous tag.

This will make the release strategy more transparent and reliable for consumers. 

similarly you would be able to do tagging in a sense of latest alpha release etc.

**Comment by sduenas** [comment]
The current releases tag the images properly. Closing this ticket as resolved.
