### ISSUE TITLE
mordred is not able to connect to Elasticsearch

### ISSUE THREAD

**Issue by Saif-Shines** [chaoss/grimoirelab#411]
Firstly, Thank you for the team working on this great project and maintainers for all the efforts you folks put in every now and then.

I am trying to run Gremorelab in my local machine. It worked fine until yesterday. I haven't updated anything. For some strange reason **modred** is not able to connect _elasticsearch_

I can confirm that _elasticsearch_ is up and running
<details>
 <summary>success response from elasticsearch</summary>
 <pre>
{
  "name" : "7ZDCoQQ",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "GI_JmvU0Tceh1cxwbfrf5Q",
  "version" : {
    "number" : "6.8.6",
    "build_flavor" : "oss",
    "build_type" : "docker",
    "build_hash" : "3d9f765",
    "build_date" : "2019-12-13T17:11:52.013738Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.2",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
</pre>
</details>

But but when I see `docker log`

Following is what I noticed,
```sh
mordred_1        | 2021-01-20 12:34:55,964 - sirmordred.sirmordred - ERROR - Cannot connect to Elasticsearch:
mordred_1        | Can not access Elasticsearch service. Exiting sirmordred ...
docker-compose_mordred_1 exited with code 1
```

Can someone please help in advising on this issue?

**Comment by vchrombie** [comment]
Hi @Saif-Shines, thanks for opening the issue. I need some more information to help you out. It would be great if you can answer these questions.

1. It would be great if you can share the setup.cfg configuration file. The elasticsearch endpoint URL should be correctly set in the setup.cfg, mainly during two places [setup.cfg#L13](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/setup.cfg#L13) and [setup.cfg#L16](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/setup.cfg#L16).
2. Could you execute `GET _cat/indices` in the [Kibana console](https://www.elastic.co/guide/en/kibana/current/console-kibana.html) and share the results? You can use `curl` and `wget` for the same.
```
curl <elasticsearch-endpoint>/_cat/indices
curl http://localhost:9200/_cat/indices
```
3. Can you try restarting the docker container and see if things better? I hope you are using the docker-compose method, you can refer to this [link](https://github.com/chaoss/grimoirelab/tree/master/docker-compose#common-questions) if needed.
```
docker-compose restart
```

Thanks.

**Comment by Saif-Shines** [comment]
@vchrombie , your suggestions really helped.

**Ask 1:**
I have update L13 and L6 as follows, (should that be `localhost:9200` ?)
```cfg
[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true
```

But this time instead of seeing not able to connect to elastic search error, I see a lot of errors throw by python packages as follows
<details>
<summary>logs of failed python errors thrown by modred</summary>
<pre>
mordred_1        | 2021-01-21T01:59:28.607364800Z     self.run()
mordred_1        | 2021-01-21T01:59:28.607407000Z   File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_manager.py", line 81, in run
mordred_1        | 2021-01-21T01:59:28.607424900Z     task = tc(self.config)
mordred_1        | 2021-01-21T01:59:28.607455400Z   File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_enrich.py", line 67, in __init__
mordred_1        | 2021-01-21T01:59:28.607482700Z     self.db = Database(**self.sh_kwargs)
mordred_1        | 2021-01-21T01:59:28.607500200Z   File "/usr/local/lib/python3.7/dist-packages/sortinghat/db/database.py", line 54, in __init__
mordred_1        | 2021-01-21T01:59:28.607517300Z     self._engine = self.build_engine(user, password, database, host, port)
mordred_1        | 2021-01-21T01:59:28.607533900Z   File "/usr/local/lib/python3.7/dist-packages/sortinghat/db/database.py", line 113, in build_engine
mordred_1        | 2021-01-21T01:59:28.607577300Z     raise DatabaseError(error=e.orig.args[1], code=e.orig.args[0])
mordred_1        | 2021-01-21T01:59:28.607595300Z sortinghat.exceptions.DatabaseError: Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address) (err: 2003)
mordred_1        | 2021-01-21T01:59:28.607625300Z
mordred_1        | 2021-01-21T01:59:28.607642900Z Exception in thread Global tasks:
mordred_1        | 2021-01-21T01:59:28.607659800Z Traceback (most recent call last):
mordred_1        | 2021-01-21T01:59:28.607676400Z   File "/usr/local/lib/python3.7/dist-packages/pymysql/connections.py", line 583, in connect
mordred_1        | 2021-01-21T01:59:28.607693300Z     **kwargs)
mordred_1        | 2021-01-21T01:59:28.607709900Z   File "/usr/lib/python3.7/socket.py", line 727, in create_connection
mordred_1        | 2021-01-21T01:59:28.607748100Z     raise err
mordred_1        | 2021-01-21T01:59:28.607765700Z   File "/usr/lib/python3.7/socket.py", line 716, in create_connection
mordred_1        | 2021-01-21T01:59:28.607783500Z     sock.connect(sa)
mordred_1        | 2021-01-21T01:59:28.607796200Z OSError: [Errno 99] Cannot assign requested address
mordred_1        | 2021-01-21T01:59:28.607813900Z
mordred_1        | 2021-01-21T01:59:28.607831900Z During handling of the above exception, another exception occurred:
mordred_1        | 2021-01-21T01:59:28.607849800Z
mordred_1        | 2021-01-21T01:59:28.607923500Z Traceback (most recent call last):
mordred_1        | 2021-01-21T01:59:28.60794
</pre>
</details>

So I doubt, if ELK is getting data from Data Sources.

**Ask 2**

```sh
~/[path]/docker-compose 4m 30s
❯ curl http://localhost:9200/_cat/indices
yellow open .grimoirelab-sigils QuQNn3cFRSy1t-xHW6jS4Q 5 1  34  0  78.3kb  78.3kb
green  open .kibana_2           n4unlNA9T6uEwTuF3XWnng 1 0 222  3 284.6kb 284.6kb
green  open .kibana_1           mG391W4RSWe4q8wlm-nV2w 1 0 222 33 362.4kb 362.4kb
```

**Ask 3**

Sure, we made some progress. The _setup.cfg_ had url pointing to elasticsearch to be empty. I filled them up as per _Ask 1_, then it began to throw errors from python modules as described above. Do you by any chance know what could be the reason behind?

**Comment by vchrombie** [comment]
Hi @Saif-Shines

> But this time instead of seeing not able to connect to elastic search error, I see a lot of errors throw by python packages as follows

Sorry for the inconvenience caused.

>  I have update L13 and L6 as follows, (should that be localhost:9200 ?)

If you are using the elasticsearch service provided in the docker-compose solution, then it can be `http://localhost:9200`. If you are using any other service, you need to put the ES endpoint link.

> logs of failed python errors thrown by modred

I see one error from the log which you have posted about sortinghat, I guess there is some configuration issue with it.

> mordred_1        | 2021-01-21T01:59:28.607595300Z sortinghat.exceptions.DatabaseError: Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address) (err: 2003)

Can you check if the setup.cfg has correct sortinghat configurations? [setup.cfg#L19](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/setup.cfg#L19)
If you have MySQL or mariadb configured locally (not docker) then you need to make sure the username and password are correct in the setup.cfg file.

It would be great if you can share the setup.cfg to see if you have any configuration mistakes.

> Sure, we made some progress. The _setup.cfg_ had url pointing to elasticsearch to be empty. I filled them up as per _Ask 1_, then it began to throw errors from python modules as described above. Do you by any chance know what could be the reason behind?

The ES configuration is correctly pointed. I guess there are some other configuration issues that might be responsible for the errors.

**Comment by zhquan** [comment]
Hi @Saif-Shines,

To complete @vchrombie's info:
log
> mordred_1        | 2021-01-20 12:34:55,964 - sirmordred.sirmordred - ERROR - Cannot connect to Elasticsearch:
> mordred_1        | Can not access Elasticsearch service. Exiting sirmordred ...
> docker-compose_mordred_1 exited with code 1

setup.cfg
> [es_collection]
> url = http://elasticsearch:9200
>
> [es_enrichment]
> url = http://elasticsearch:9200

Make sure that on your mordred `docker-compose.yml` has this:
- elastic_elasticsearch_1: The name of your elasticsearch mordred
```
    external_links:
      - elastic_elasticsearch_1:elasticsearch
```
If you don't have this you can use your elasticsearch URL `http://localhost:9200`

> mordred_1 | 2021-01-21T01:59:28.607595300Z sortinghat.exceptions.DatabaseError: Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address) (err: 2003)

The same here, you have to add this on the mordred docker-compose.yml to use `mariadb` as host.
```
    external_links:
      - mariadb_mariadb_1:mariadb
```
Or you can put your mariadb IP directly at [setup.cfg#L20](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/setup.cfg#L20)

Easy check.
Enter into your mordred container and try to connect to your elasticsearch using the same URL that you set on the `setup.cfg` and the same way to your mariadb:
1. `$ docker exec -it MORDRED_CONTAINER /bin/bash`
2. `curl ES_URL`
3. `mysql --host HOST --user USER --password PASS`

If you cannot connect to your elasticsearch or mariadb using the `setup.cfg` values try others. And when you can connect both of them, use those values on your `setup.cfg`.

I hope it helps you.

Best,
Quan

**Comment by Saif-Shines** [comment]
@vchrombie - Is you rightly assumed, I did a rookie configuration mistake. I read your instructions and fixed them. Now ES on my system is working as described.
<details>
<summary>Just in case you'd want to see my <code>setup.cfg</code></summary>
<pre>
[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = mariadb
user = root
password =
database = grimiore
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
# gitlab-issues = true
# gitlab-merges = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

#[bugzillarest]
#raw_index = bugzillarest_demo_raw
#enriched_index = bugzillarest_demo_enriched
#no-archive = true

#[confluence]
#no-archive = true
#raw_index = confluence_demo_raw
#enriched_index = confluence_demo_enriched

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[discourse]
raw_index = discourse_freshworks-raw
enriched_index = discourse_freshworks-enriched
no-archive = true

[github]
# Names for raw and enriched indexes
raw_index = github_freshworks-raw
enriched_index = github_freshworks
no-archive = true
# Sleep it GitHub API rate is exhausted, waited until it is recovered
sleep-for-rate = true

[github:prs]
# Names for raw and enriched indexes
raw_index = prs-github_freshworks-raw
enriched_index = prs-github_freshworks
no-archive = true
# Sleep it GitHub API rate is exhausted, waited until it is recovered
sleep-for-rate = true
category = pull_request

#[github]
#api-token = <YOUR_API_TOKEN_WHERE>
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
#raw_index = github_demo_raw
#sleep-for-rate = true
#sleep-time = "300"
#enriched_index = github_demo_enriched

#[gitlab:issues]
#api-token = <YOUR_API_TOKEN_HERE>
#raw_index = gitlab_issues_demo_raw
#enriched_index = gitlab_issues_demo_enriched
#no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
#sleep-for-rate = true

#[gitlab:merge]
#api-token = <YOUR_API_TOKEN_HERE>
#raw_index = gitlab_merges_demo_raw
#enriched_index = gitlab_merges_demo_enriched
#no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
#category = merge_request
#sleep-for-rate = true

#[jira]
#raw_index = jira_demo_raw
#enriched_index = jira_demo_enriched
#no-archive = true

#[pipermail]
#raw_index = pipermail_demo_raw
#enriched_index = pipermail_demo_enriched
#no-verify = true

#[mediawiki]
#raw_index = mediawiki_demo_raw
#enriched_index = mediawiki_demo_enriched
#no-archive = true

#[meetup]
#raw_index = meetup_demo_raw
#enriched_index = meetup_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = "300"

#[stackexchange]
#raw_index = stackexchange_demo_raw
#enriched_index = stackexchange_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[slack]
#raw_index = slack_demo_raw
#enriched_index = slack_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[supybot]
#raw_index = supybot_demo_raw
#enriched_index = supybot_demo_enriched

#[twitter]
#raw_index = twitter_demo_raw
#enriched_index = twitter_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = 300

## studies based on enriched indexes

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash
</pre>
</details>

@zhquan , 
Appreciate you chiming in. I would have tried connecting to ES after entering into modred container as suggested, but fortunately `setup.cfg` worked. Your troubleshooting steps were insightful.

**Comment by vchrombie** [comment]
Thanks @zhquan for helping. :slightly_smiling_face: 

That's good news @Saif-Shines. :tada: 
If your issue is resolved, please feel free to close the issue.
