### ISSUE TITLE
author_org_name not being populated

### ISSUE THREAD

**Issue by sventiffe** [chaoss/grimoirelab#412]
I've started evaluating a dashboard based on the grimoirelab/full image and was able to configure it and start to customize it. So far, results are really promising!

I've noticed however that author_org_name is not set by default (in my configuration). I've tried to figure out how to enable it but could not find much (or did not search in the right places or used the wrong keywords). Any hints how to get it running would be appreciated.

**Comment by vchrombie** [comment]
Hi @sventiffe, thanks for your interest in GrimoireLab and sorry for the late reply.

The `grimoirelab/full` image is quite outdated [link](https://hub.docker.com/r/grimoirelab/full/tags?page=1&ordering=last_updated). It would be better if you can try the latest mordred image and see if you can reproduce the same issue.

The latest version of mordred is `bitergia/mordred:grimoirelab-0.2.53` [link](https://hub.docker.com/r/bitergia/mordred/tags?page=1&ordering=last_updated). But, it doesn't have ES, Kibiter and mariadb. You might need to pull them too from [bitergia dockerhub](https://hub.docker.com/r/bitergia/kibiter) again.

So, I would suggest you try the [docker-compose solution](https://github.com/chaoss/grimoirelab/tree/master/docker-compose) which is quite straight forward and similar to the docker solution.

Please let us know if you have any more issues.
Thanks.

**Comment by sventiffe** [comment]
Hi @vchrombie, thank you for the reply! I will try docker-compose. 

As I am fairly new to Docker: given that I have an container running on an (outdated) image, can I run the same container on a newly created image without losing the data (i.e. imported GitHub information) and without losing the customization that I did via the UI (i.e. new graphs, saved searches, etc)? 

The instructions that I found (or, the instructions that I believe to have understood so far) suggest that updating the image requires to remove the container and restart the container.

**Comment by vchrombie** [comment]
Hi @sventiffe, sorry but I'm really not sure if this is possible.

But, I have some suggestions which can reduce the loss. If you have developed some panels of your own, you can export them to JSON files and later import them using [Kidash](https://github.com/chaoss/grimoirelab-kidash#usage). Let us know if you need any help with this.

> can I run the same container on a newly created image without losing the data (i.e. imported GitHub information)

I'm not really sure but as far as I understand it is not possible. If it's not an issue, you can schedule the mordred to fetch the data again.

@sduenas @zhquan, do you have any comments?

**Comment by zhquan** [comment]
Hi @sventiffe,

If you want your data persistent, you have to do this https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#save-changes-made-in-dashboard-by-mounting-the-volume-in-es-. But if you don't have it, you can copy that directory using [docker cp](https://docs.docker.com/engine/reference/commandline/cp/).

I hope it helps you.

Best,
Quan

**Comment by sventiffe** [comment]
Thanks for the suggestions, running a new container now based on docker-compose and initial results are looking promising!
