### ISSUE TITLE
Update Tutorial link to an example dashboard

### ISSUE THREAD

**Issue by HousewifeHacker** [chaoss/grimoirelab#420]
The Tutorial includes an example dashboard image with a link for [OPNFV Development Dashboard](https://opnfv.biterg.io/). When clicking the link, the dashboard is not available.

**Comment by vchrombie** [comment]
Hi @HousewifeHacker, thanks for opening the issue. We have identified this and we have a PR https://github.com/chaoss/grimoirelab-tutorial/pull/153 which fixes it.

You can visit [CHAOSS Dashboard](https://chaoss.biterg.io) if you are interested to have a look at GrimoireLab.
Thanks.

**Comment by sduenas** [comment]
Fixed by https://github.com/chaoss/grimoirelab-tutorial/pull/153
