### ISSUE TITLE
In the column of gitlab merge, only front has data; but in git, all three projects have data

### ISSUE THREAD

**Issue by No6-start** [chaoss/grimoirelab#421]
{
    "front": {
      "meta:": {
        "title": "front"
      },
      "git":[
            "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/front/owss.git",
	    "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/front/webchat.git",
	    "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/front/acti.git",
	    "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/front/ccbsweb.git",
	    "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/front/ccbs.git"
        ],
        "gitlab:merge":[
            "http://xxx.xx.com/front/owss",
			"http://xxx.xx.com/front/webchat",
			"http://xxx.xx.com/front/acti",
			"http://xxx.xx.com/front/ccbsweb",
			"http://xxx.xx.com/front/ccbs"
        ]
    },
    "core": {
      "meta:": {
        "title": "core"
      },
      "git":[
            "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/cms.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/reins.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/nfin.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/cif.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/sso.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/qry.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/npcs.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/tmdatasvr.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/tmanage.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/itm.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/nepolicy.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/epolicy.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/vc.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/um.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/nbz.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/exweb.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/uprocess.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/necif.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/aml.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/eclmweb.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/its.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/eclm.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/uprocess-rest.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/nsales.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/nclm.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/cem.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/core/timeserver.git"
        ],
        "gitlab:merge":[
            "http://xxx.xx.com/core/cms.git",
			"http://xxx.xx.com/core/reins.git",
			"http://xxx.xx.com/core/nfin.git",
			"http://xxx.xx.com/core/cif.git",
			"http://xxx.xx.com/core/sso.git",
			"http://xxx.xx.com/core/qry.git",
			"http://xxx.xx.com/core/npcs.git",
			"http://xxx.xx.com/core/tmdatasvr.git",
			"http://xxx.xx.com/core/tmanage.git",
			"http://xxx.xx.com/core/itm.git",
			"http://xxx.xx.com/core/nepolicy.git",
			"http://xxx.xx.com/core/epolicy.git",
			"http://xxx.xx.com/core/vc.git",
			"http://xxx.xx.com/core/um.git",
			"http://xxx.xx.com/core/nbz.git",
			"http://xxx.xx.com/core/exweb.git",
			"http://xxx.xx.com/core/uprocess.git",
			"http://xxx.xx.com/core/necif.git",
			"http://xxx.xx.com/core/aml.git",
			"http://xxx.xx.com/core/eclmweb.git",
			"http://xxx.xx.com/core/its.git",
			"http://xxx.xx.com/core/eclm.git",
			"http://xxx.xx.com/core/uprocess-rest.git",
			"http://xxx.xx.com/core/nsales.git",
			"http://xxx.xx.com/core/nclm.git",
			"http://xxx.xx.com/core/cem.git",
			"http://xxx.xx.com/core/timeserver.git"
        ]
    },	
    "midl": {
      "meta": {
        "title": "midl"
      },
      "git":[
            "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/skyeyeview.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/ics.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/pdmsapi.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/pdms.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/quotms.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/npas.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/pas.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/coupon.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/cgi.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/portal.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/issweb.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/bdyz.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/skyeye.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/qunar.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/ors.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/mview.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/diplomat.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/policy.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/necifsvr.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/issueplat.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/proposal.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/wsprdt.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/dysub.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/order.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/task.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/trans.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/tongcheng.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/ctrip.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/open.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/user.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/callback.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/pubs.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/mailserver.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/eanpay.git",
			"http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/outerpay.git"
        ],
        "gitlab:merge":[
            "http://xxx.xx.com/midl/skyeyeview.git",
			"http://xxx.xx.com/midl/ics.git",
			"http://xxx.xx.com/midl/pdmsapi.git",
			"http://xxx.xx.com/midl/pdms.git",
			"http://xxx.xx.com/midl/quotms.git",
			"http://xxx.xx.com/midl/npas.git",
			"http://xxx.xx.com/midl/pas.git",
			"http://xxx.xx.com/midl/coupon.git",
			"http://xxx.xx.com/midl/cgi.git",
			"http://xxx.xx.com/midl/portal.git",
			"http://xxx.xx.com/midl/issweb.git",
			"http://xxx.xx.com/midl/bdyz.git",
			"http://xxx.xx.com/midl/skyeye.git",
			"http://xxx.xx.com/midl/qunar.git",
			"http://xxx.xx.com/midl/ors.git",
			"http://xxx.xx.com/midl/mview.git",
			"http://xxx.xx.com/midl/diplomat.git",
			"http://xxx.xx.com/midl/policy.git",
			"http://xxx.xx.com/midl/necifsvr.git",
			"http://xxx.xx.com/midl/issueplat.git",
			"http://xxx.xx.com/midl/proposal.git",
			"http://xxx.xx.com/midl/wsprdt.git",
			"http://xxx.xx.com/midl/dysub.git",
			"http://xxx.xx.com/midl/order.git",
			"http://xxx.xx.com/midl/task.git",
			"http://xxx.xx.com/midl/trans.git",
			"http://xxx.xx.com/midl/tongcheng.git",
			"http://xxx.xx.com/midl/ctrip.git",
			"http://xxx.xx.com/midl/open.git",
			"http://xxx.xx.com/midl/user.git",
			"http://xxx.xx.com/midl/callback.git",
			"http://xxx.xx.com/midl/pubs.git",
			"http://xxx.xx.com/midl/mailserver.git",
			"http://xxx.xx.com/midl/eanpay.git",
			"http://xxx.xx.com/midl/outerpay.git"
        ]
    }
}

**Comment by vchrombie** [comment]
Hi @No6-start, thanks for opening the issue.

The `projects.json` file is valid but I see there are a lot of projects. So, make sure you have sufficient memory. Also, it would definitely take a lot of time to fetch the data.

> In the column of gitlab merge, only front has data; but in git, all three projects have data

If you see the gitlab merge data, I'm sure there is no other issue. I guess it should be taking a lot of time for fetching the data. Either way, it would be great if you can check the logs for any errors.

**Comment by No6-start** [comment]
How to configure my memory

**Comment by zhquan** [comment]
Hi @No6-start 

Only the sources on `gitlab:merge` from the project `front` are correct.

You have to remove the `.git` extension from `gitlab:merge`. This extension only works for `git`.

Best,
Quan

**Comment by vchrombie** [comment]
> Only the sources on `gitlab:merge` from the project `front` are correct.
> You have to remove the `.git` extension from `gitlab:merge`. This extension only works for `git`.

Ah, that's right. I missed it, my bad. Thanks for correcting @zhquan.

**Comment by No6-start** [comment]
I rewrote my example, should I?

{
    "front": {
      "meta:": {
        "title": "front"
      },
      "git":[
        "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/front/owss.git",
        ],
        "gitlab:merge":[
            "http://xxx.xx.com/front/owss",
        ]
    },
    "core": {
      "meta:": {
        "title": "core"
      },
      "git":[
        ],
        "gitlab:merge":[
            "http://xxx.xx.com/core/cms.git",
        ]
    },	
    "midl": {
      "meta:": {
        "title": "midl"
      },
      "git":[
            "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/skyeyeview.git",
        ],
        "gitlab:merge":[
            "http://xxx.xx.com/midl/skyeyeview.git",
        ]
    }
}

**Comment by vchrombie** [comment]
@No6-start
As @zhquan suggested, you have to remove _`.git`_ from the `gitlab:merge` items. You can add _`.git`_ to only `git` items.
```
     "git":[
         "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/skyeyeview.git"
     ],
     "gitlab:merge":[
-        "http://xxx.xx.com/midl/skyeyeview.git"
+        "http://xxx.xx.com/midl/skyeyeview"
     ]
```

Using the configuration of https://github.com/chaoss/grimoirelab/issues/421#issuecomment-816503407
```
{
    "front":{
        "meta:":{
            "title":"front"
        },
        "git":[
            "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/front/owss.git"
        ],
        "gitlab:merge":[
            "http://xxx.xx.com/front/owss"
        ]
    },
    "core":{
        "meta:":{
            "title":"core"
        },
        "git":[
            
        ],
        "gitlab:merge":[
            "http://xxx.xx.com/core/cms"
        ]
    },
    "midl":{
        "meta:":{
            "title":"midl"
        },
        "git":[
            "http://phU-DaG9zSKGTvsz5BH4:phU-DaG9zSKGTvsz5BH4@xxx.xx.com/midl/skyeyeview.git"
        ],
        "gitlab:merge":[
            "http://xxx.xx.com/midl/skyeyeview"
        ]
    }
}
```

**Comment by No6-start** [comment]
Thank you. I just found this problem
