### ISSUE TITLE
Filter only for "own" code?

### ISSUE THREAD

**Issue by martinweihrauch** [chaoss/grimoirelab#427]
Thank you for this great project! We have now successfully installed and connected to our Git repos.
One question: 
We would like to **only** count e. g. lines of code and committed files of files, which were really written by us and are not some "3rd party" files. 
In our dev team, the devs could e. g. put a comment into each file, which e. g. contains a keyword. So, is it possible to only count files, which contain a certain keyword?
Thx
Martin

**Comment by dicortazar** [comment]
Hi @martinweihrauch, thanks a lot for this comment indeed!

There are several ways to gather the information you're interested in. Two indexes contain this information you're looking for: "git" and "git_areas_of_code". The first one works at the granularity of commits while the latter can drill down to files and lines of code. 
While "git" displays an aggregation of the total number of added, removed, and modified lines for a given commit, "git_areas_of_code" displays this info by file.

Both indexes offer the information about the author of the commit ([git schema](https://github.com/chaoss/grimoirelab-elk/blob/master/schema/git.csv) and [git_areas_of_code schema](https://github.com/chaoss/grimoirelab-elk/blob/master/schema/areas_of_code.csv)) and some attributes as the organization and others.

With this in mind, there are some ways to have this data:
* If you have polished the affiliations information, this is a matter of applying the info of the organizations you're interested in.
* An alternative (if the number of developers is not too high) is to add a filter in the dashboard adding each of them.
* If you have not polished the affiliations, but you have that info, then you can at least start working on this. There are direct links to Hatstall the UI interface if you access the Community => Affiliations dashboard.
* Finally, you can do what you suggest and this is adding a keyword in the commit. However, this may be prone to be buggy, and developers may forget about that from time to time. In any case the short answer is yes, you can filter by a keyword. In this case you should use the field message_analyzed or message (please check the data models I provided above) and you'll have a tokenize version of the log messages left by developers.

Hope this helps!

**Comment by martinweihrauch** [comment]
Thank you very much for your detailed answer!
I get it! 
However, analyzing lines of code is of little use, if you cannot exclude certain files and paths like gitignore. E. g. one of our devs updated all "NPM" packages and thus added 8,000 lines of code in 1 week. 
A dream would be a treeview of the project and to be able to "include/exclude" whole folders and / or single files.
A simpler, not so comfortable version would be to be able to at least add a kind of "gitignore"-like file as a filter so that we can exclude 3rd-party files, etc?
Else, I think that I may rather write a software, where I first pull a repo to the local disk and then to the git log commands plus I can show a treeview, where developers can include/exclude paths and files.
Again, I really appreciate your support!!
