### ISSUE TITLE
data problem

### ISSUE THREAD

**Issue by No6-start** [chaoss/grimoirelab#429]
After a period of use, I set the data to be obtained in 2021, but one month later, my data is still incomplete. For example, there were 10 mergers yesterday, but only 3 were displayed. How can I adjust this

**Comment by No6-start** [comment]
GitHub can't upload files to issue, so I can't provide configuration for the time being

**Comment by zhquan** [comment]
Hi @No6-start 

Without log and configuration, I cannot help you. You can copy the `github` section from your `setup.cfg` file. 

And please check your logs if there are any errors.

Best,
Quan

**Comment by No6-start** [comment]
[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = mariadb
user = root
password =
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
gitlab-issues = true
gitlab-merges = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = false
studies = [enrich_demography:git, enrich_git_branches:git, enrich_areas_of_code:git, enrich_onion:git]
from-date = 2021-01-01

[gitlab:merge]
category = merge_request
api-token = phU-DaG9zSKGTvsz5BH4
enterprise-url = http://192.168.144.93/
raw_index = gitlab_merges_demo_raw
enriched_index = gitlab_merges_demo_enriched
no-archive = true
sleep-for-rate = true
from-date = 2021-01-01

## studies based on enriched indexes

[enrich_demography:git]

[enrich_git_branches:git]
run_month_days = [12]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash

**Comment by No6-start** [comment]
I can't upload my blog

**Comment by zhquan** [comment]
Hi @No6-start 

When you activate `from-date` it will start the collection always from that date (2021-01-01). So my recommendation is to execute the first time with `from-date` and when you have data remove it and `sirmoredred` will execute it incrementally.

1. Execute with `from-date` (already done in your case, so skip this step)
2. Remove `from-date` and restart only the `sirmordred` docker container.
3. Check on your logs that you can see something like this: `Incremental from: 2021-02-24 01:01:34+00:00`
```
2021-04-14 08:00:46,594 - grimoire_elk.raw.elastic - INFO - [gitlab] Incremental from: 2021-02-17 02:03:19+00:00 for http://192.168.144.93/core/eclmweb
2021-04-14 08:00:47,327 - grimoire_elk.raw.elastic - INFO - [gitlab] Incremental from: 2021-02-24 01:01:34+00:00 for http://192.168.144.93/core/epolicy
2021-04-14 08:00:48,590 - grimoire_elk.raw.elastic - INFO - [gitlab] Incremental from: 2021-03-10 09:52:13+00:00 for http://192.168.144.93/core/its 
```

I hope it helps you.

Best,
Quan

**Comment by No6-start** [comment]
Can I understand that after executing from date, delete and restart the sirordered component. How do I restart the sirordred component

**Comment by zhquan** [comment]
@No6-start  - `docker restart SIRMORDRED_CONTAINER_NAME`

**Comment by No6-start** [comment]
CONTAINER ID   IMAGE                                                     COMMAND                  CREATED      STATUS                PORTS                              NAMES
c35f0eac681a   grimoirelab/hatstall:latest                               "/bin/sh -c ${DEPLOY…"   4 days ago   Up 4 days             0.0.0.0:8000->80/tcp               dockercompose_hatstall_1
ea20fecf555f   bitergia/mordred:latest                                   "/bin/sh -c ${DEPLOY…"   4 days ago   Up 4 days (healthy)                                      dockercompose_mordred_1
b2a9ffe62c21   bitergia/kibiter:community-v6.8.6-3                       "/docker_entrypoint.…"   4 days ago   Up 4 days             0.0.0.0:5601->5601/tcp             dockercompose_kibiter_1
03c433fb0a0d   mariadb:10.0                                              "docker-entrypoint.s…"   4 days ago   Up 4 days             3306/tcp                           dockercompose_mariadb_1
ee1812e0c64f   docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.6   "/usr/local/bin/dock…"   4 days ago   Up 4 days             0.0.0.0:9200->9200/tcp, 9300/tcp   dockercompose_elasticsearch_1

**Comment by zhquan** [comment]
@No6-start - `docker restart bitergia/mordred:latest`

**Comment by No6-start** [comment]
I restarted the bitergia component, but it didn't seem to change much

**Comment by zhquan** [comment]
@No6-start - Could you share your logs? Maybe we can get more info

**Comment by vchrombie** [comment]
@No6-start, were you able to resolve the issue?
Please let us know if you need any help.

**Comment by vchrombie** [comment]
Closing this issue assuming it is resolved.

@No6-start, please feel free to open a new one for any other doubts.
