### ISSUE TITLE
[Require] to update installation process of README.md

### ISSUE THREAD

**Issue by Aju100** [chaoss/grimoirelab#434]
Hi grimoirelab maintainer,

As a newcomer, we might face issues when we follow the Getting started guideline to install grimoire on our system using the docker process. 
![gl](https://user-images.githubusercontent.com/29862610/120459043-8869d200-c3b7-11eb-8abb-06c0f87aab4c.png)

Solutions:
- remove out the user foo@bar: one in instruction one

Code in following issues one :
```bash
git clone https://github.com/chaoss/grimoirelab
```
Reference:
- https://github.com/chaoss/grimoirelab/tree/master/docker-compose
- https://github.com/chaoss/grimoirelab-kidash

**Comment by vchrombie** [comment]
NACK :slightly_frowning_face::-1: 

I would keep the instructions in the existing format as it shows the current directory path, virtual environment (if applies) and mainly to maintain consistency for all the commands. I'm really not sure removing this would have a huge impact.

**Comment by Aju100** [comment]
hi @vchrombie  
Thank you for your feedbacks. I will disclose this issue
