### ISSUE TITLE
GitLab Issues/MRs not displayed in Kibiter/Kibana

### ISSUE THREAD

**Issue by Alch-Emi** [chaoss/grimoirelab#435]
Howdy!

I'm having some troubles getting Kibana to work with GitLab.  Despite appearing to have successfully scraped the GitLab instance, no issues appear in the Kibiter dashboard.  However, upon inspection, the ElasticSearch database does contain the appropriate records, both raw and enriched.  This happens, in my experience, both with Kibiter and Kibana.  Git commits do appear in the database, so I'm not sure what the problem is.

I am running grimoirelab docker, and have tested with both the current dockerhub build and a fresh docker build from this repository, which is what is currently running.

If you'd like to poke around at the data yourself, I've exposed

* [The Kibiter instance](https://alchemi.dev:5502)
* The ElasticSearch database at https://alchemi.dev:5503/
* And, for convenience, an elasticsearch frontend at https://alchemi.dev:5501/

All of these are a testing setup with test data, so no changes are permanent of course, and I'll close the ports shortly after resolving this issue.

My [override.cfg](https://bin.disroot.org/?3f1578bf848c47f7#8ZGpJKvSUwHNQaYbiGR7mz5XUgsKhzs24ur2cfbhw7Hm) and my [projects.json](https://bin.disroot.org/?5b24c02ecb9b451a#FfMEdSfwbYRW5GVZ1Heu89TKPa8seDBNwMPJ1YHMZiga) are both here.  It's worth noting that while it is currently configured to use a selfhost instance of GitLab, I've observed this behavior with the flagship GitLab instance as well.

If you have any idea what the problem might be, advice would be greatly appreciated.

**Comment by zhquan** [comment]
Hi @Alch-Emi 

I checked your Kibiter instance and your GitLab repo:
- [1 issue](https://opensource.ieee.org/rit/mystic/-/issues)
- [0 merge request](https://opensource.ieee.org/rit/mystic/-/merge_requests).

And in your indexes I see 1 issue and 0 merge requests. So the indexes are created correctly.
```
GET _cat/indices

yellow open gitlab-mrs_raw                 -fP20qBvRAu2Z7D0r5o_8A 5 1   0 0   1.2kb   1.2kb
yellow open gitlab-mrs_enriched            XDqVfH2bQReeHQ5gfbhtDg 5 1   0 0   1.2kb   1.2kb

yellow open gitlab-issues_raw              8SuJuk3AQnWwiexgBPAsvg 5 1   1 0  43.2kb  43.2kb
yellow open gitlab-issues_enriched         18hzSHA8R4aiJGK1EwpTBQ 5 1   1 0  40.4kb  40.4kb
```

**Then what is the issue?**
After checking the aliases I miss `gitlab` aliases.
- `gitlab_issues`
- `gitlab_merge_requests`
```
GET _cat/aliases

gitlab-raw        gitlab-mrs_raw                 - - -
affiliations      git_grimoirelab                - - -
demographics      git_grimoirelab                - - -
git               git_grimoirelab                - - -
git_author        git_grimoirelab                - - -
git_enrich        git_grimoirelab                - - -
git-raw           git_grimoirelab-raw            - - -
all_onion         gitlab-issues-onion_enriched   - - -
gitlab            gitlab-issues_enriched         - - -
git_areas_of_code git_aoc_grimoirelab-enriched   - - -
gitlab-raw        gitlab-issues_raw              - - -
all_onion         git_onion_grimoirelab-enriched - - -
```
You have to create those aliases and add the corresponding indexes.
Run this query and check again your `GitLab Issues` panel. It does not have any merge requests, so the `GitLab Merge Requests` panel will still be empty
```
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "gitlab-mrs_enriched", "alias": "gitlab_merge_requests"
      }
    },
    {
      "add": {
        "index": "gitlab-issues_enriched", "alias": "gitlab_issues"
      }
    }
  ]
}
```

I hope it helps you.

Best,
Quan

**Comment by Alch-Emi** [comment]
Thank you very much, I will give this a try! <3

**Comment by sduenas** [comment]
@Alch-Emi could you make it work?

**Comment by zhquan** [comment]
@Alch-Emi I close the issue feel free to reopen it if needed.
