### ISSUE TITLE
docker-compose: docker-compose_mordred_1 fails, UI shows "Couldn't find any Elasticsearch data"

### ISSUE THREAD

**Issue by fweikert** [chaoss/grimoirelab#436]
I've been following the instructions from https://github.com/chaoss/grimoirelab/tree/master/docker-compose (without changing any configuration file). Commit: 5826bb8383ed6bb721e04f911ac431807596cea9.

However, when I open http://localhost:5601/ I get "Couldn't find any Elasticsearch data"

Running `docker-compose ps` shows that mordred crashed:

```
             Name                           Command               State                 Ports              
-----------------------------------------------------------------------------------------------------------
docker-compose_elasticsearch_1   /usr/local/bin/docker-entr ...   Up       0.0.0.0:9200->9200/tcp, 9300/tcp
docker-compose_hatstall_1        /bin/sh -c ${DEPLOY_USER_D ...   Up       0.0.0.0:8000->80/tcp            
docker-compose_kibiter_1         /docker_entrypoint.sh kibana     Up       0.0.0.0:5601->5601/tcp          
docker-compose_mariadb_1         docker-entrypoint.sh mysqld      Up       3306/tcp                        
docker-compose_mordred_1         /bin/sh -c ${DEPLOY_USER_D ...   Exit 1   
```

`docker-compose logs` contains the likely reason (multiple times):

```
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/local/bin/sirmordred", line 116, in <module>
mordred_1        |     logs_dir = config_dict['general']['logs_dir']
mordred_1        | KeyError: 'general'
```

Again, I haven't modified any configuration files, so I was surprised to see this problem.

Note: Not sure if this is related or a separate error, but the connection to Elasticsearch seems to have dropped temporarily:

```
[32mkibiter_1        |[0m {"type":"log","@timestamp":"2021-06-17T19:04:41Z","tags":["error","elasticsearch","admin"],"pid":1,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 172.22.0.2:9200"}
[32mkibiter_1        |[0m {"type":"log","@timestamp":"2021-06-17T19:04:41Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
[32mkibiter_1        |[0m {"type":"log","@timestamp":"2021-06-17T19:04:41Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
[32mkibiter_1        |[0m {"type":"log","@timestamp":"2021-06-17T19:04:41Z","tags":["status","plugin:elasticsearch@6.8.6","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elasticsearch.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
[32mkibiter_1        |[0m {"type":"log","@timestamp":"2021-06-17T19:04:44Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
[32mkibiter_1        |[0m {"type":"log","@timestamp":"2021-06-17T19:04:44Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
[32mkibiter_1        |[0m {"type":"log","@timestamp":"2021-06-17T19:04:47Z","tags":["status","plugin:elasticsearch@6.8.6","info"],"pid":1,"state":"green","message":"Status changed from red to green - Ready","prevState":"red","prevMsg":"Unable to connect to Elasticsearch."}
```

**Comment by fweikert** [comment]
There's also `[33mhatstall_1       |[0m cp: cannot open 'shdb.cfg' for reading: Permission denied`

**Comment by vchrombie** [comment]
Hi @fweikert, thanks for reporting the issue and sort for the inconvenience.

1. > Note: Not sure if this is related or a separate error, but the connection to Elasticsearch seems to have dropped temporarily:

Yes, it looks like the elasticsearch service is not running. It would be great if you can check the logs of `elasticsearch_1` for any possible errors.

If you find any error similar to this
```
elasticsearch_1  | ERROR: bootstrap checks failed
elasticsearch_1  | max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```
This can be resolved by [increasing the virtual memory for ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html)
```
$ sysctl -w vm.max_map_count=262144
```

2. > There's also �[33mhatstall_1 |�[0m cp: cannot open 'shdb.cfg' for reading: Permission denied

It seems the permission of the file is incorrect.

Make sure the user `docker` has `read` and `write` permission on `shdb.cfg` file.

This might be helpful.
```
$ chmod 666 ../default-grimoirelab-settings/shdb.cfg
$ docker-compose up
```

Please let us know how it goes.
Thanks,
Venu

**Comment by fweikert** [comment]
Thank you for the answer!

Elasticsearch seems to be running - the last message indicates status "green", and "curl localhost:9200" returns

```
{
  "name" : "Pl5sJ3k",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "JcikiaoYRyKCH1-e4aH2Bg",
  "version" : {
    "number" : "6.8.6",
    "build_flavor" : "oss",
    "build_type" : "docker",
    "build_hash" : "3d9f765",
    "build_date" : "2019-12-13T17:11:52.013738Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.2",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
I still think the major problem is that mordred crashes due to the missing key in the Python dictionary, but the script doesn't seem to come from this repository (probably another container).

**Comment by fweikert** [comment]
I forgot to add that I already ran `$ sysctl -w vm.max_map_count=262144` before my failed attempts.

**Comment by vchrombie** [comment]
Hi @fweikert 

> I still think the major problem is that mordred crashes due to the missing key in the Python dictionary, but the script doesn't seem to come from this repository (probably another container).

Sorry, I overlooked the error log which you have provided.

I was looking at this earlier.
```
�[32mkibiter_1        |�[0m {"type":"log","@timestamp":"2021-06-17T19:04:41Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
```

I see the actual error now
```
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/local/bin/sirmordred", line 116, in <module>
mordred_1        |     logs_dir = config_dict['general']['logs_dir']
mordred_1        | KeyError: 'general'
```
and also, you are right. The error doesn't come from here, it comes from [sirmordred script](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/bin/sirmordred#L116). It is trying to extract the value from [setup.cfg#L6](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/setup.cfg#L6) file.

I see you haven't changed any configuration files.
> Again, I haven't modified any configuration files, so I was surprised to see this problem.

So, I'm suspecting the docker might not have sufficient permissions to this [default-grimoirelab-settings](https://github.com/chaoss/grimoirelab/tree/master/default-grimoirelab-settings) folder. I see you have reported something similar problem in the starting.
> There's also �[33mhatstall_1 |�[0m cp: cannot open 'shdb.cfg' for reading: Permission denied

Can you please see if docker has the necessary permissions similar to that mentioned in the [2nd point of comment](https://github.com/chaoss/grimoirelab/issues/436#issuecomment-863519889)?

This might be helpful.
```
$ chmod 666 ../default-grimoirelab-settings/
$ docker-compose up
```

Again, sorry for the inconvenience. Please let us know how it went.
Best,
Venu

**Comment by fweikert** [comment]
Ok, so it turns out that our custom Linux distro blocks access to /home completely. I replaced all paths to point at a different directory, which didn't work. I then moved Grimoire to my MacBook, and now it works (except that 100% of people have an unknown organization, but I guess I can solve that with hatstall). 

Thank you for the help!

**Comment by vchrombie** [comment]
Hello @fweikert 

> Ok, so it turns out that our custom Linux distro blocks access to /home completely. I replaced all paths to point at a different directory, which didn't work. I then moved Grimoire to my MacBook, and now it works.

That is great to hear! Thanks for confirming the error. 

> Thank you for the help!

You are welcome, and thanks for trying GrimoireLab. 

> I might have to file a separate issue for this, but is there a way to see the status of a data import and potential errors?

As of now, we entirely depend upon the logs for checking the data import status and errors. You can check the logs to see the raw and enrichment phases' progress. You can look in the `mordred_1` logs for such information.
```
[git] collection phase starts
[git] collection starts for https://github.com/chaoss/grimoirelab-perceval
...
...
Fetch process completed: 104 commits fetched
[git] collection phase finished in 00:00:01
Loading raw data finished!
Reading projects data from  ./projects.json 
[git] enrichment phase starts
[git] enrichment starts for https://github.com/chaoss/grimoirelab-perceval
```

Tip: If you are looking to analyze only a few data sources like git, github/gitlab, etc.; you should be interested in [cauldron.io](https://cauldron.io/). It is a SaaS software development analytics solution that uses GrimoireLab technology. You might find something useful.

> I went to Dashboard > Data Status, and after waiting I could see that the number of items in the Git panel increased over time. However, I've also set up GitHub projects, and their item number remains at 0. Am I missing something here?

I'm assuming you have added your projects and configurations in the respective files i.e, [projects.json](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/projects.json) and [setup.cfg](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/setup.cfg) in the [default-grimoirelab-settings](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/) folder. If not, it is required to add them. Please check the [supported-data-sources](https://github.com/chaoss/grimoirelab-sirmordred#supported-data-sources-) section to know more. Let us know if you need any help, I can help you with the configurations.

It might take 10-15 minutes or more, depending on the size of the project.
 
If you have done this step and still the data is not visible, please share your configurations and logs (if any), so that we can look more closely at what might be wrong.

Hope this helps.
Best,
Venu

**Comment by fweikert** [comment]
Hey Venu, thank you again! Here is my config and the logs: https://drive.google.com/drive/folders/1xOHeTlUrBxPtMMgNRcOgfXEwpxE-D8Iz?resourcekey=0-MAQtIn8yyMch3H05e2cmVA&usp=sharing (I gave your gmail address permission to access the folder).

I started again from scratch by running the commands from https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#others: `docker-compose down --remove-orphans`  and  `docker system prune -a --volumes`

I then added only a single GitHub project to the config from the README and ran `docker-compose up -d`.

Note: I could NOT run `screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty` since it failed with "No such file or directory". (MacBook Pro, Big Sur 11.4).

After some time I could see the first commits in the dashboard, but still no issues nor PRs. This time the logs shows a relevant error:

```
mordred_1        | 2021-06-22 17:36:22,095 - sirmordred.task_enrich - ERROR - Missing config for study 
mordred_1        | enrich_geolocation:user:
mordred_1        | 2021-06-22 17:36:22,097 - sirmordred.task_manager - ERROR - [github] Exception in Task Manager Missing config for study 
mordred_1        | enrich_geolocation:user:
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_manager.py", line 97, in run
mordred_1        |     task.execute()
mordred_1        |   File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_enrich.py", line 436, in execute
mordred_1        |     raise e
mordred_1        |   File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_enrich.py", line 403, in execute
mordred_1        |     self.__enrich_items()
mordred_1        |   File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_enrich.py", line 166, in __enrich_items
mordred_1        |     studies_args = self.__load_studies()
mordred_1        |   File "/usr/local/lib/python3.7/dist-packages/sirmordred/task_enrich.py", line 103, in __load_studies
mordred_1        |     raise DataEnrichmentError(msg)
mordred_1        | sirmordred.error.DataEnrichmentError: Missing config for study 
mordred_1        | enrich_geolocation:user:
```

I copied the relevant parts from the README, without any changes, i.e. the "enrich_geolocation:user" section exists.

The UI stills shows 0 GitHub issues and PRs.

Note: As in my first attempt I can see that the raw index actually contains GitHub issues: I went to Dev Tools and ran `GET github_raw/_search`, which showed several issues.
However, if I run `GET github_enriched/_search` I only get this text:

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

I guess at this point the best path forward is to remove the study?

**Comment by fweikert** [comment]
Note: I didn't get this particular error during my first attempt, but I could also see that the raw index contained GitHub issues and PRs.

**Comment by vchrombie** [comment]
Hi @fweikert, thanks for taking your time and providing the configs and the detailed information. The configs you have provided seem to be correct but I couldn't figure out the error you are facing. I have some doubts but I'm not entirely confident if that could be the issue.

> Note: I didn't get this particular error during my first attempt, but I could also see that the raw index contained GitHub issues and PRs.

The `github` backend collects issues and prs information but they are handled in different indexes in ELK. But, I see the configurations are not explicitly mentioned in the `setup.cfg` and `projects.json` files. We use `category = issue` and `category = pull_request` for differentiating the data. This might be the reason why there is an enrichment error.

I'm slightly changing the configurations, it would be great if you can try it.

projects.json
```
{
  "Bazel": {
    "git": [
      "https://github.com/bazelbuild/continuous-integration"
    ],
    "github:issue": [
      "https://github.com/bazelbuild/continuous-integration"
    ],
    "github:pull": [
      "https://github.com/bazelbuild/continuous-integration"
    ]
  }
}
```

setup,cfg (I have changed only the relevant, rest all configurations should be the same)
```
[phases]
...
panels = true

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash

[github:issue]
raw_index = github-issue_raw
enriched_index = github-issue_enriched
category = issue
api-token = xxx
sleep-for-rate = true
no-archive = true
studies = [enrich_onion:github, 
           enrich_geolocation:user, 
           enrich_geolocation:assignee, 
           enrich_demography:github]

[github:pull]
raw_index = github-pull_raw
enriched_index = github-pull_enriched
category = pull_request
api-token = xxx
sleep-for-rate = true
no-archive = true
studies = [enrich_onion:github, 
           enrich_geolocation:user, 
           enrich_geolocation:assignee, 
           enrich_demography:github]

[enrich_onion:github]
in_index_iss = github_issues_onion-src
in_index_prs = github_prs_onion-src
out_index_iss = github-issues-onion_enriched
out_index_prs = github-prs-onion_enriched

[enrich_geolocation:user]
location_field = user_location
geolocation_field = user_geolocation

[enrich_geolocation:assignee]
location_field = assignee_location
geolocation_field = assignee_geolocation

[enrich_demography:github]
```

If you still see the same error, you can try removing the studies which are causing the error. If it works in that case, we can check if there is anything wrong with the study. You can remove the study by simply not calling it.
```
studies = [enrich_onion:github, 
           enrich_demography:github]
```

@zhquan, it would be great if you can check it too if you have some time. I'm requesting @fweikert to share the folder with you too on the google drive.

**Comment by zhquan** [comment]
Hi @fweikert 

Could you write all studies in one line the same as `git` and try again?
```
[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
raw_index = github_raw
enriched_index = github_enriched
api-token = <redacted>
sleep-for-rate = true
no-archive = true
studies = [enrich_onion:github, enrich_geolocation:user, enrich_geolocation:assignee, enrich_demography:github]
```
We have to change this in the DOC.

I hope it helps you.

Best,
Quan

**Comment by fweikert** [comment]
Thank you - the single-line approach fixed the problem :) I can see the issues now. Again, thank you so much!

**Comment by fweikert** [comment]
Ok, based on https://github.com/chaoss/grimoirelab-elk/blob/master/doc/studies.md#requirements-1 I guess I need to separate "github" into "github:issues" and "github:pull" for studies to work. I had tried that previously, but then the "GitHub Issues" and "GitHub PRs" entries disappeared from the top menu in the dashboard UI.

**Comment by vchrombie** [comment]
Hello @fweikert 

> Ok, based on https://github.com/chaoss/grimoirelab-elk/blob/master/doc/studies.md#requirements-1 I guess I need to separate "github" into "github:issues" and "github:pull" for studies to work. I had tried that previously, but then the "GitHub Issues" and "GitHub PRs" entries disappeared from the top menu in the dashboard UI.

Well, that could be the reason. You can use the configuration in this https://github.com/chaoss/grimoirelab/issues/436#issuecomment-866268200 and try again. I have already edited it as per @zhquan's suggestion.

Please let us know how it goes.

**Comment by zhquan** [comment]
Hi @fweikert 

> Ok, based on https://github.com/chaoss/grimoirelab-elk/blob/master/doc/studies.md#requirements-1 I guess I need to separate "github" into "github:issues" and "github:pull" for studies to work. I had tried that previously, but then the "GitHub Issues" and "GitHub PRs" entries disappeared from the top menu in the dashboard UI.

You don't have to separate it, but you have to create those aliases `github_issues_onion-src` and `github_prs_onion-src`, considering that both are using the same index pattern `github_issues`. 

As @vchrombie said the menu is updated in the panels task, so you can activate/deactivate it on the section `[phases]` 
```
[phases]
...
panels = true/false
```

Try again removing the section `[github:pull]` and rename the section `[github:issue]`  to `[github]` (to still seeing the menu).

Best,
Quan

**Comment by fweikert** [comment]
I forgot to follow up, but we decided to deprecate our manual installation in favour of a hosted solution. Thank you for your help!

**Comment by vchrombie** [comment]
Thanks for closing the issue @fweikert. Feel free to open a new one in case of any other doubts.
