### ISSUE TITLE
[Feature Request] Support Gitee as data source in Grimoirelab

### ISSUE THREAD

**Issue by eyehwan** [chaoss/grimoirelab#439]
Initial dicussion thread from slack grimoirelab channel:

During CHAOSS Beijing Meetup on July 8 2021,  Venu introduced the Grimoirelab through the [Youtube  ](https://youtu.be/dm1iamz-RKA)and I also gave a live demo.  
I used forked branch of Grimoirelab to introduce the usage of Grimoirelab upon the data source from [Gitee](https://gitee.com/), and how to insight data upon the CHAOSS metrics.
We received lots of interests about how to use Grimoirelab in their communities, especially from Gitee users. 
Because lots of OpenSource communites (180,000 enterprises, 15,000,000 repos，6,000,000 users) have been using Gitee as the provider of Internet hosting for software development and version control using Git and SVN, similaly like Github and Gitlab.

So I would like to lanuch a dicussion here, to see how to support Gitee as data source in Grimoirelab. 
And I would like to work with CHAOSS/Grimoirelab community together on it!

Thanks,
BR//Yehui.

**Comment by vchrombie** [comment]
Hi @eyehwan, thanks for bringing this topic.

If we want to add support of a new data source to the GrimoireLab, first we start with adding a backend to [grimoirelab-perceval](https://github.com/chaoss/grimoirelab-perceval), next adding the raw-collector & enricher to [grimoirelab-elk](https://github.com/chaoss/grimoirelab-perceval), then add the configurations to the [grimoirelab-sirmordred](https://github.com/chaoss/grimoirelab-sirmordred) and finish by adding the visualizations & dashboards to the [grimoirelab-sigils](https://github.com/chaoss/grimoirelab-sigils). This is the whole workflow.

Coming to adding support for gitee, I remember this feature was already proposed. There was a discussion around this topic last year. It started from https://github.com/chaoss/grimoirelab-perceval/pull/645.

_Quoting @sduenas comment_
> The main problem is to maintain this backend (and others through time), if we add it, that means that any other change we make will be supported by this backend. Also, if nobody uses it, it might get deprecated fast.







I remember @heming6666 and @WillemJiang
https://github.com/heming6666/grimoirelab-project-tracker

**Comment by eyehwan** [comment]
@vchrombie 

> Coming to adding support for gitee, I remember this feature was already proposed. There was a discussion around this topic last year. It started from chaoss/grimoirelab-perceval#645.

Yes, you are right. We don't have to start from scratch, as we already have these conbributions more or less. I have disucssed with @WillemJiang and @heming6666 earlier actually. 

The reason I want to pop up this proposal again is that I would like to contribute my effort to mantain those components(perceval, raw-collector, grimoirelab-elk etc) to support gitee as data source of grimoirelab. 
I hope this would solve the concerns from @sduenas.

**Comment by vchrombie** [comment]
> Yes, you are right. We don't have to start from scratch, as we already have these conbributions more or less. I have disucssed with @WillemJiang and @heming6666 earlier actually.

That's great, again thanks for bringing this topic again. I hope to receive more comments from the community members.

Also, @WillemJiang @heming6666, would you be interested to work again on the existing PRs once we come to a conclusion on this topic?

As a sidenote, adding the link to the roadmap for the GrimoireLab.
https://github.com/chaoss/grimoirelab/projects/1

We are currently actively working on sortinghat, bestiary and creating a release system for grimoirelab. So, this discussion might take some time to conclude. I hope you all stay with us along the way. I would be helping to move the discussion forward.

Best,
Venu

**Comment by sduenas** [comment]
@eyehwan Thanks for raising this topic again and for your interest on GrimoireLab.

As I said in other comments, we would be so happy to expand GrimoireLab to support as much datasources as possible. However, we are concerned about the maintenance of these data sources in the mid/long term. In fact, we should consider soon to drop the support of some of the backends that we already have.

For that reason, my proposal has been that someone that wants to add support for a new datasource, should start creating a `perceval` backend and the other components of the chain in their own repositories. We'll be more than happy to publicize it on GrimoireLab documentation as a third-party datasource.

With this approach, we won't add more dependencies to the core of the platform and we'll reduce the uncertainty of having code that, us, as maintainers and users, don't use normally. If at some point the maintainers of that datasource wantsto integrate it with the core of GrimoireLab, we will discuss it and we will decide if it makes sense to include it.

What do you think @eyehwan? Does it work for you?

What do you think @eyehwan? Does it w

**Comment by WillemJiang** [comment]
> 
> 
> @vchrombie
> 
> > Coming to adding support for gitee, I remember this feature was already proposed. There was a discussion around this topic last year. It started from [chaoss/grimoirelab-perceval#645](https://github.com/chaoss/grimoirelab-perceval/pull/645).
> 
> Yes, you are right. We don't have to start from scratch, as we already have these conbributions more or less. I have disucssed with @WillemJiang and @heming6666 earlier actually.
> 

Few month ago, I had long conversation with @eyehwan and provide all the information about gitee backend to him.
It could be great if @eyehwan can keep working on it, as Gitee is quite popluar in China.

> The reason I want to pop up this proposal again is that I would like to contribute my effort to mantain those components(perceval, raw-collector, grimoirelab-elk etc) to support gitee as data source of grimoirelab.
> I hope this would solve the concerns from @sduenas.

Beside of gitee backend of perceval, we also need to add some components to grimorielab-elk. It could be greate if grimorielab-elk provides pulgin support, so we can install the extensions from another repos.

**Comment by eyehwan** [comment]
> For that reason, my proposal has been that someone that wants to add support for a new datasource, should start creating a perceval backend and the other components of the chain in their own repositories. We'll be more than happy to publicize it on GrimoireLab documentation as a third-party datasource.

 Hi @sduenas @vchrombie , 
Thanks for your suggestions. 
Do we already have any similar cases to put data source outside of core of GrimoireLab? Any guildelines to follow?

**Comment by sduenas** [comment]
In Bitergia we have some backends in other repositories. For example: https://github.com/Bitergia/grimoirelab-perceval-finos
But you can also follow the same approach of https://github.com/chaoss/grimoirelab-perceval-mozilla/ or https://github.com/chaoss/grimoirelab-perceval-puppet.

The only problem we have right now is, as @WillemJiang commented, to give plugin support to `grimoirelab-elk`. That will be a really great contribution if someone of you can implement it. We can help you we that if you need it.

Also, a good starting point to create a new backend is [the documentation](https://github.com/chaoss/grimoirelab-perceval/pull/738) @Alch-Emi created.

**Comment by WillemJiang** [comment]
> In Bitergia we have some backends in other repositories. For example: https://github.com/Bitergia/grimoirelab-perceval-finos
> But you can also follow the same approach of https://github.com/chaoss/grimoirelab-perceval-mozilla/ or https://github.com/chaoss/grimoirelab-perceval-puppet.
> 

Yeah, I'm thinking maybe we can move the gitee repo to the Github chaoss group as grimoirelab-perceval-gitee and we would be happy to maintain this repo. 

> The only problem we have right now is, as @WillemJiang commented, to give plugin support to `grimoirelab-elk`. That will be a really great contribution if someone of you can implement it. We can help you we that if you need it.
> 

@heming6666  made [a proposal](https://github.com/chaoss/grimoirelab-elk/issues/880). Maybe it's the time that we can revisit it again.
  
> Also, a good starting point to create a new backend is [the documentation](https://github.com/chaoss/grimoirelab-perceval/pull/738) @Alch-Emi created.

**Comment by eyehwan** [comment]
> > In Bitergia we have some backends in other repositories. For example: https://github.com/Bitergia/grimoirelab-perceval-finos
> > But you can also follow the same approach of https://github.com/chaoss/grimoirelab-perceval-mozilla/ or https://github.com/chaoss/grimoirelab-perceval-puppet.
> 
> Yeah, I'm thinking maybe we can move the gitee repo to the Github chaoss group as grimoirelab-perceval-gitee and we would be happy to maintain this repo.

Yes, I also share the same idea! I am wondering its possibilities.

**Comment by sduenas** [comment]
> > > In Bitergia we have some backends in other repositories. For example: https://github.com/Bitergia/grimoirelab-perceval-finos
> > > But you can also follow the same approach of https://github.com/chaoss/grimoirelab-perceval-mozilla/ or https://github.com/chaoss/grimoirelab-perceval-puppet.
> > 
> > 
> > Yeah, I'm thinking maybe we can move the gitee repo to the Github chaoss group as grimoirelab-perceval-gitee and we would be happy to maintain this repo.
> 
> Yes, I also share the same idea! I am wondering its possibilities.

Sorry but I think we can't do that right now. We're very happy that you want to participate but we're interested in the project in the long term. There are many people that join communities and left after few days or months. It's not that we don't trust you, it's just that you need to show you're active maintaining your backend and that people are using it. After that, we can consider at some point to have it in GrimorieLab.

For now, the best we can offer is add a link your repos in the documentation.

Hope you can understand our point.

**Comment by eyehwan** [comment]
> We're very happy that you want to participate but we're interested in the project in the long term. 

> it's just that you need to show you're active maintaining your backend and that people are using it. After that, we can consider at some point to have it in GrimorieLab.

Thanks @sduenas, I totally understand your concern, then I will discuss with @WillemJiang to create a repo group and maintain our Gitee solutions at first.

**Comment by sduenas** [comment]
Thanks for understanding. I'm going to close this ticket but keep us posted about your decisions and progress.

**Comment by vchrombie** [comment]
Thanks to everyone who was involved in this work. The Gitee support is implemented and is being maintained in [github.com/grimoirelab-gitee](https://github.com/grimoirelab-gitee) organization.

We have added references to the grimoirelab repositories too. Thanks to @eyehwan for opening the PRs.
- https://github.com/chaoss/grimoirelab/blob/master/community_components.md#other-data-sources
- https://github.com/chaoss/grimoirelab-perceval#community-backends

Again, thanks for all your efforts. Without the community support, it wouldn't be possible.

We are working on revamping the tutorial, I think we can add some documentation on adding support for new data sources taking inspiration from [grimoirelab-gitee](https://github.com/grimoirelab-gitee).

cc @WillemJiang @heming6666 @shanchenqi.
