### ISSUE TITLE
No data and visualization error

### ISSUE THREAD

**Issue by yodayuuki55** [chaoss/grimoirelab#444]
Hi~
![_AG2T18 UX76MYJASGTU5OG](https://user-images.githubusercontent.com/87411538/130391399-1226fc4a-198f-47b5-a795-510c9cfe5771.png)
Now i can open http://localhost:5601 but i cant see any data and there is a error in visualization.

**Comment by zhquan** [comment]
Hi @yodayuuki55 

Go to `Dev Tools` and execute `GET _cat/indices` and check if you have `git_demo_enriched` and `github_demo_enriched` indexes. If not you have to wait until Mordred creates them due to the index pattern `affiliations` use these enriched indexes.

Best,
Quan

**Comment by yodayuuki55** [comment]
> Hi @yodayuuki55
> 
> Go to `Dev Tools` and execute `GET _cat/indices` and check if you have `git_demo_enriched` and `github_demo_enriched` indexes. If not you have to wait until Mordred creates them due to the index pattern `affiliations` use these enriched indexes.
> 
> Best,
> Quan

Thanks for reply!
The follwing is `GET _cat/indices`
![X3S6)}R%SVH28S_ KG(E}@3](https://user-images.githubusercontent.com/87411538/130421069-2493167f-4eec-4922-b51c-20966ffad7f4.png)

I have `git_demo_enriched` and `github_demo_enriched`  but there are only "- - -" after them

**Comment by zhquan** [comment]
@yodayuuki55 - You executed `GET _cat/aliases` instead of `GET _cat/indices`.
Could you execute `GET _cat/indices` to know if there are items in the enriched indexes?

**Comment by yodayuuki55** [comment]
I'm so sry @zhquan 
The following is `GET _cat/indices`
![2$BI M NO_RF5})YIIN_@`K](https://user-images.githubusercontent.com/87411538/130427552-9dba52e3-e7c3-43bc-aa54-ebaf18ee2bae.png)

**Comment by zhquan** [comment]
@yodayuuki55 - You don't have any items in your indexes. That means your `projects.json` is empty or not configured correctly.

Have a look your `all.log` to check if there are errors.

**Comment by yodayuuki55** [comment]
I can only find one error that ` grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/chaoss/grimoirelab): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit`
There is too much information in `all.log`

> 2021-08-23 06:44:55,489 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/chaoss/grimoirelab): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/elk.py", line 162, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/raw/elastic.py", line 228, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/raw/elastic.py", line 244, in feed_items
    for item in items:
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 224, in fetch
    self.client = self._init_client()
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 293, in _init_client
    self.archive, from_archive, self.ssl_verify)
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 653, in __init__
    self._choose_best_api_token()
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 954, in _choose_best_api_token
    self._update_current_rate_limit()
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 999, in _update_current_rate_limit
    raise error
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 991, in _update_current_rate_limit
    response = super().fetch(url)
  File "/usr/local/lib/python3.7/dist-packages/perceval/client.py", line 143, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, auth)
  File "/usr/local/lib/python3.7/dist-packages/perceval/client.py", line 186, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.7/dist-packages/perceval/client.py", line 181, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
2021-08-23 06:44:55,491 - grimoire_elk.elk - INFO - [github] Done collection for https://github.com/chaoss/grimoirelab
2021-08-23 06:44:55,491 - sirmordred.task_collection - INFO - [github] collection finished for https://github.com/chaoss/grimoirelab
2021-08-23 06:44:55,491 - sirmordred.task_collection - INFO - [github] collection phase finished in 00:00:00
2021-08-23 06:45:05,506 - sirmordred.task_enrich - INFO - [github] enrichment phase starts

**Comment by vchrombie** [comment]
Hi @yodayuuki55, sorry for the inconvenience caused.

Can you check if the github token is working?
```
$ perceval github chaoss grimoirelab --sleep-for-rate  -t TOKEN
```

> grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/chaoss/grimoirelab): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit

> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit

It looks like there is some problem with the token.

Please let us know.

**Comment by zhquan** [comment]
@yodayuuki55 - It seems the problem is the `setup.cfg`. Check if your `GitHub-TOKEN` is working correctly and make sure the  `sleep-for-rate = true` is activated.

You can check your token with [Perceval](https://github.com/chaoss/grimoirelab-perceval) as @vchrombie said. Or you can execute it into your Mordred container
```
$ docker exec -it MORDRED_CONTAINER_NAME /bin/bash
$ perceval github chaoss grimoirelab -t TOKEN --sleep-for-rate
```

Your `setup.cfg` should have at least this:
```
[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = false

[github]
raw_index = github_demo_raw
enriched_index = github_demo_enriched
api-token = TOKEN
sleep-for-rate = true
no-archive = true
```
`projects.json`
```
{
    "GrimoireLab": {
        "git": [
            "https://github.com/chaoss/grimoirelab.git"
        ],
        "github": [
            "https://github.com/chaoss/grimoirelab"
        ]
    }
}
```

**Comment by yodayuuki55** [comment]
Hi @vchrombie @zhquan I find that my machine not having perceval and when i tried to install it ,i got a new problem:

> ERROR: Could not find a version that satisfies the requirement grimoirelab-toolkit (unavailable) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.12, 0.2.0)
ERROR: No matching distribution found for grimoirelab-toolkit (unavailable)

My grimoirelab-toolkit version is 0.2.0 
![FR%A$Y3IV5CNVQJJUR03JYA](https://user-images.githubusercontent.com/87411538/130456275-169c0c05-e442-4e73-9f47-0d255b617393.png)
installed from `https://github.com/vchrombie/grimoirelab-toolkit`

So,i cannot use `$ perceval github chaoss grimoirelab --sleep-for-rate  -t TOKEN` now

**Comment by yodayuuki55** [comment]
> @yodayuuki55 - It seems the problem is the `setup.cfg`. Check if your `GitHub-TOKEN` is working correctly and make sure the `sleep-for-rate = true` is activated.
> 
> You can check your token with [Perceval](https://github.com/chaoss/grimoirelab-perceval) as @vchrombie said. Or you can execute it into your Mordred container
> 
> ```
> $ docker exec -it MORDRED_CONTAINER_NAME /bin/bash
> $ perceval github chaoss grimoirelab -t TOKEN --sleep-for-rate
> ```
> 
> Your `setup.cfg` should have at least this:
> 
> ```
> [git]
> raw_index = git_demo_raw
> enriched_index = git_demo_enriched
> latest-items = false
> 
> [github]
> raw_index = github_demo_raw
> enriched_index = github_demo_enriched
> api-token = TOKEN
> sleep-for-rate = true
> no-archive = true
> ```
> 
> `projects.json`
> 
> ```
> {
>     "GrimoireLab": {
>         "git": [
>             "https://github.com/chaoss/grimoirelab.git"
>         ],
>         "github": [
>             "https://github.com/chaoss/grimoirelab"
>         ]
>     }
> }
> ```

I can make sure that my `setup.cfg` and `projects.json` have this.

**Comment by yodayuuki55** [comment]
@zhquan @vchrombie I still cannot install `perceval` but now i can use `perceval github chaoss grimoirelab -t TOKEN --sleep-for-rate` and there is a error:

> [2021-08-23 22:13:24,511] - Sir Perceval is on his quest.
[2021-08-23 22:13:25,222] - Error!: expected str, bytes or os.PathLike object, not NoneType
[2021-08-23 22:13:25,223] - Sir Perceval completed his quest.

**Comment by zhquan** [comment]
@yodayuuki55  - I can reproduce your error. Your GitHub Token is not valid.
```
$ perceval github chaoss grimoirelab -t TOKEN --sleep-for-rate > /dev/null
[2021-08-23 16:57:24,124] - Sir Perceval is on his quest.
[2021-08-23 16:57:24,443] - Error!: expected str, bytes or os.PathLike object, not NoneType
[2021-08-23 16:57:24,445] - Sir Perceval completed his quest.
```

I can install Perceval without any issue.

Please follow these steps:
```
$ python3 -m venv ~/perceval-env

$ source ~/perceval-env/bin/activate

$ pip install --upgrade pip setuptools wheel

$ git clone https://github.com/chaoss/grimoirelab-perceval.git

$ cd grimoirelab-perceval

$ python3 setup.py install

$ perceval github chaoss grimoirelab -t TOKEN --sleep-for-rate > /dev/null
[2021-08-23 16:47:20,184] - Sir Perceval is on his quest.
[2021-08-23 16:52:57,475] - Summary of results

	   Total items: 	443
	Items produced: 	443
	 Items skipped: 	0

	Last item UUID: 	810622cdbfe43ec00cc3d9e80a23e3c3b027de86
	Last item date: 	2021-08-23 14:17:03+00:00

	Min. item date: 	2017-10-04 08:02:32+00:00
	Max. item date: 	2021-08-23 14:17:03+00:00

	Min. offset: 	-	Max. offset: 	-	Last offset: 	-


[2021-08-23 16:52:57,479] - Sir Perceval completed his quest.
```

The GitHub token needs **READ** permissions.

**Comment by yodayuuki55** [comment]
> @yodayuuki55 - I can reproduce your error. Your GitHub Token is not valid.
> 
> ```
> $ perceval github chaoss grimoirelab -t NOT-VALID-TOKEN --sleep-for-rate > /dev/null
> [2021-08-23 16:57:24,124] - Sir Perceval is on his quest.
> [2021-08-23 16:57:24,443] - Error!: expected str, bytes or os.PathLike object, not NoneType
> [2021-08-23 16:57:24,445] - Sir Perceval completed his quest.
> ```
> 
> I can install Perceval without any issue.
> 
> Please follow these steps:
> 
> ```
> $ python3 -m venv ~/perceval-env
> 
> $ source ~/perceval-env/bin/activate
> 
> $ pip install --upgrade pip setuptools wheel
> 
> $ git clone https://github.com/chaoss/grimoirelab-perceval.git
> 
> $ cd grimoirelab-perceval
> 
> $ python3 setup.py install
> 
> $ perceval github chaoss grimoirelab -t VALID-TOKEN --sleep-for-rate > /dev/null
> [2021-08-23 16:47:20,184] - Sir Perceval is on his quest.
> [2021-08-23 16:52:57,475] - Summary of results
> 
> 	   Total items: 	443
> 	Items produced: 	443
> 	 Items skipped: 	0
> 
> 	Last item UUID: 	810622cdbfe43ec00cc3d9e80a23e3c3b027de86
> 	Last item date: 	2021-08-23 14:17:03+00:00
> 
> 	Min. item date: 	2017-10-04 08:02:32+00:00
> 	Max. item date: 	2021-08-23 14:17:03+00:00
> 
> 	Min. offset: 	-	Max. offset: 	-	Last offset: 	-
> 
> 
> [2021-08-23 16:52:57,479] - Sir Perceval completed his quest.
> ```
> 
> The GitHub token needs **READ** permissions.

Now I can successfully installed `perceval`:
`Finished processing dependencies for perceval==0.17.10`
But when use `$ perceval github chaoss grimoirelab -t VALID-TOKEN --sleep-for-rate > /dev/null`, i got the same error:

> (perceval-env) root@hs-v-osssc-dev-01:~/grimoirelab-perceval# perceval github chaoss grimoirelab -t VALID-TOKEN --sleep-for-rate > /dev/null
[2021-08-23 23:49:43,504] - Sir Perceval is on his quest.
[2021-08-23 23:49:44,169] - Error!: expected str, bytes or os.PathLike object, not NoneType
[2021-08-23 23:49:44,170] - Sir Perceval completed his quest.

And this is my `setup.cfg`:

> [git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = false
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

> [github]
api-token = TOKEN
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched
no-archive = true


>

**Comment by zhquan** [comment]
@yodayuuki55 - You have to replace `VALID-TOKEN` or `TOKEN` with your own personal GitHub token.

Click [here](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) to know how to create a GitHub token. Remember that the GitHub token needs **READ** permissions.

**Comment by yodayuuki55** [comment]
> @yodayuuki55 - You have to replace `VALID-TOKEN` or `TOKEN` with your own personal GitHub token.
> 
> Click [here](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) to know how to create a GitHub token. Remember that the GitHub token needs **READ** permissions.

Sorry for delay.
The following is result of `$ perceval github chaoss grimoirelab -t VALID-TOKEN --sleep-for-rate` :

>  [2021-08-24 09:20:54,619] - Summary of results

           Total items:         443
        Items produced:         443
         Items skipped:         0

        Last item UUID:         810622cdbfe43ec00cc3d9e80a23e3c3b027de86
        Last item date:         2021-08-23 17:10:30+00:00

        Min. item date:         2017-10-04 08:02:32+00:00
        Max. item date:         2021-08-23 17:10:30+00:00

        Min. offset:    -       Max. offset:    -       Last offset:    -

**Comment by vchrombie** [comment]
Thanks for clarifying @yodayuuki55.

>  (perceval-env) root@hs-v-osssc-dev-01:~/grimoirelab-perceval# perceval github chaoss grimoirelab -t VALID-TOKEN --sleep-for-rate > /dev/null
    [2021-08-23 23:49:43,504] - Sir Perceval is on his quest.
    [2021-08-23 23:49:44,169] - Error!: expected str, bytes or os.PathLike object, not NoneType
    [2021-08-23 23:49:44,170] - Sir Perceval completed his quest.

It looks like you are on a Windows machine. I think this error comes because of this ` > /dev/null` [error](https://stackoverflow.com/a/56898950). However, for clarifying, almost all the development for GrimoireLab is done in Linux-based systems. That means that using Linux for development is certainly more friendly, and we can provide much more support.

Anyways this isn't our concern right now.

> ```
>    [2021-08-24 09:20:54,619] - Summary of results
> 
>            Total items:         443

The token seems to be working fine. Can you use this token for the configurations mentioned in the https://github.com/chaoss/grimoirelab/issues/444#issuecomment-903725480.


`setup.cfg` should have
```
[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = false

[github]
raw_index = github_demo_raw
enriched_index = github_demo_enriched
api-token = TOKEN
sleep-for-rate = true
no-archive = true
```

`projects.json`
```
{
    "GrimoireLab": {
        "git": [
            "https://github.com/chaoss/grimoirelab.git"
        ],
        "github": [
            "https://github.com/chaoss/grimoirelab"
        ]
    }
}
```

It would be great if you can restart the docker/docker-compose method of installation. Please check the [docker-compose common questions](https://github.com/chaoss/grimoirelab/tree/master/docker-compose#common-questions).

If you still face any errors, please let us know the installation method you have used and also share the full version of the `setup.cfg` and `projects.json` files.

Hope this helps. Best,
Venu

**Comment by yodayuuki55** [comment]
Hi@vchrombie
Thanks for reply!

Due to my job demand, i have to use my PC (WINDOWS) connecting to a VM (Ubuntu) by SSH.

**I have just used `docker-compose restart` to restart the platform,but there is no change on my dashboard,maybe i need to wait for minutes?**

The follwing is my `setup.cfg` and `projects.json`: 

`setup.cfg` :
> [general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

> [projects]
projects_file = /home/bitergia/conf/projects.json

> [es_collection]
url = http://elasticsearch:9200

> [es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

> [sortinghat]
host = mariadb
user = root
password =
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

> [panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
gitlab-issues = true
gitlab-merges = true
github-repos = true

> [phases]
collection = true
identities = true
enrichment = true
panels = true

> #[bugzillarest]
#raw_index = bugzillarest_demo_raw
#enriched_index = bugzillarest_demo_enriched
#no-archive = true

> #[confluence]
#no-archive = true
#raw_index = confluence_demo_raw
#enriched_index = confluence_demo_enriched

> #[discourse]
#raw_index = discourse_demo_raw
#enriched_index = discourse_demo_enriched
#no-archive = true

> [git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = false
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

> [github]
api-token = ghp_.......
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched
no-archive = true

> [gitlab:issues]
api-token = ghp_.......
raw_index = gitlab_issues_demo_raw
enriched_index = gitlab_issues_demo_enriched
no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
sleep-for-rate = true

> [gitlab:merge]
api-token = ghp_.......
raw_index = gitlab_merges_demo_raw
enriched_index = gitlab_merges_demo_enriched
no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
category = merge_request
sleep-for-rate = true

> #[jira]
#raw_index = jira_demo_raw
#enriched_index = jira_demo_enriched
#no-archive = true

> #[pipermail]
#raw_index = pipermail_demo_raw
#enriched_index = pipermail_demo_enriched
#no-verify = true

> #[mediawiki]
#raw_index = mediawiki_demo_raw
#enriched_index = mediawiki_demo_enriched
#no-archive = true

> #[meetup]
#raw_index = meetup_demo_raw
#enriched_index = meetup_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = "300"

> #[stackexchange]
#raw_index = stackexchange_demo_raw
#enriched_index = stackexchange_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

> #[slack]
#raw_index = slack_demo_raw
#enriched_index = slack_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

> #[supybot]
#raw_index = supybot_demo_raw
#enriched_index = supybot_demo_enriched

> #[twitter]
#raw_index = twitter_demo_raw
#enriched_index = twitter_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = 300

> ##studies based on enriched indexes

> [enrich_demography:git]

> [enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

> [enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash

`projects.json`: 

> {
    "Grimoirelab": {
      "git": [
          "https://github.com/chaoss/grimoirelab.git"
      ],
      "github": [
          "https://github.com/chaoss/grimoirelab"
      ]
    }
  }

**Comment by vchrombie** [comment]
> Due to my job demand, i have to use my PC (WINDOWS) connecting to a VM (Ubuntu) by SSH.

No problem, we completely understand the requirement. :slightly_smiling_face: 

> **I have just used `docker-compose restart` to restart the platform,but there is no change on my dashboard,maybe i need to wait for minutes?**

Please see that you need to wait at least for 10-15 minutes to see the data. It might take more time depending on the size of the project. Please keep us updated.

**Comment by yodayuuki55** [comment]
> > Due to my job demand, i have to use my PC (WINDOWS) connecting to a VM (Ubuntu) by SSH.
> 
> No problem, we completely understand the requirement. 🙂
> 
> > **I have just used `docker-compose restart` to restart the platform,but there is no change on my dashboard,maybe i need to wait for minutes?**
> 
> Please see that you need to wait at least for 10-15 minutes to see the data. It might take more time depending on the size of the project. Please keep us updated.

Thanks for quick reply! I am waiting for it and will tell you the result soon.

**Comment by yodayuuki55** [comment]
> > Due to my job demand, i have to use my PC (WINDOWS) connecting to a VM (Ubuntu) by SSH.
> 
> No problem, we completely understand the requirement. 🙂
> 
> > **I have just used `docker-compose restart` to restart the platform,but there is no change on my dashboard,maybe i need to wait for minutes?**
> 
> Please see that you need to wait at least for 10-15 minutes to see the data. It might take more time depending on the size of the project. Please keep us updated.

It seems not working,i still see nothing about data,maybe there is something wrong in my `setup.cfg` and `project.json`?

Could you help me check them? Thanks a lot!

**Comment by zhquan** [comment]
@yodayuuki55 - Check your logs (`all.log`) and search by `ERROR`. Also check your indexes `GET _cat/indices` if there are items on raw and enriched indexes.

Anyway, comment `[gitlab:issue]` and `[gitlab:merge]` sections due to in your `projects.json` only have `git` and `github`.

**Comment by yodayuuki55** [comment]
@zhquan Ok,i have commented them and the following are `ERROR` in `all.log` : 

> 2021-08-23 04:38:09,199 - grimoire_elk.elk - ERROR - [git] Problem executing study enrich_areas_of_code:git, RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
2021-08-23 04:38:09,199 - sirmordred.task_manager - ERROR - [git] Exception in Task Manager RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')


> 2021-08-23 05:08:39,883 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/chaoss/grimoirelab): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit

>  raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit

The following is my indexes `GET _cat/indices` : 

![}LT)WC6A@ @PXMTTII8Y RW](https://user-images.githubusercontent.com/87411538/130596770-50fe912c-8abd-4075-96b6-ed074772207b.png)

**Comment by zhquan** [comment]
@yodayuuki55 

>2021-08-23 05:08:39,883 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/chaoss/grimoirelab): >401 Client Error: Unauthorized for url: https://api.github.com/rate_limit

you are not using a valid token and it's strange due to you tested with Perceval (https://github.com/chaoss/grimoirelab/issues/444#issuecomment-904245612). I guess your Mordred is still using the old `setup.cfg`.

Execute this to know if your `setup.cfg` is updated (To know your Mordred container name execute `docker ps`).
```
$ docker exec -it MORDRED_CONTAINER_NAME cat /home/bitergia/conf/setup.cfg
```

Could you search in your log if you can see errors like `Error feeding raw from git (https://github.com/chaoss/grimoirelab.git):`  or any other error related to `git` due to `git` does not use `TOKEN` and I see your `git_demo_raw` index is empty.

>2021-08-23 04:38:09,199 - grimoire_elk.elk - ERROR - [git] Problem executing study enrich_areas_of_code:git, RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
2021-08-23 04:38:09,199 - sirmordred.task_manager - ERROR - [git] Exception in Task Manager RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')

This error is related to the study based on the raw index and your raw index is empty.

When you restart the Mordred container you will see a message like `Starting SirMordred engine ...` on your logs. So make sure to search errors after your last `Starting SirMordred engine ...` message.

**Comment by yodayuuki55** [comment]
> @yodayuuki55
> 
> > 2021-08-23 05:08:39,883 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/chaoss/grimoirelab): >401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
> 
> you are not using a valid token and it's strange due to you tested with Perceval ([#444 (comment)](https://github.com/chaoss/grimoirelab/issues/444#issuecomment-904245612)). I guess your Mordred is still using the old `setup.cfg`.
> 
> Execute this to know if your `setup.cfg` is updated (To know your Mordred container name execute `docker ps`).
> 
> ```
> $ docker exec -it MORDRED_CONTAINER_NAME cat /home/bitergia/conf/setup.cfg
> ```
> 
> Could you search in your log if you can see errors like `Error feeding raw from git (https://github.com/chaoss/grimoirelab.git):` or any other error related to `git` due to `git` does not use `TOKEN` and I see your `git_demo_raw` index is empty.
> 
> > 2021-08-23 04:38:09,199 - grimoire_elk.elk - ERROR - [git] Problem executing study enrich_areas_of_code:git, RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
> > 2021-08-23 04:38:09,199 - sirmordred.task_manager - ERROR - [git] Exception in Task Manager RequestError(400, 'search_phase_execution_exception', 'No mapping found for [metadata__timestamp] in order to sort on')
> 
> This error is related to the study based on the raw index and your raw index is empty.
> 
> When you restart the Mordred container you will see a message like `Starting SirMordred engine ...` on your logs. So make sure to search errors after your last `Starting SirMordred engine ...` message.

Sorry for delay @zhquan 
![J}{{KJ59LBSKK2X8NQ02H{8](https://user-images.githubusercontent.com/87411538/130622447-f724605d-b217-499d-9799-be53a43835a7.png)
It seems there is not Mordred container.

**Comment by zhquan** [comment]
@yodayuuki55 your mordred container is stopped I guess you will see it if you execute `docker ps -a`. You have to restart the mordred container `docker restart dockercompose_mordred_1` or `docker-compose up -d`

**Comment by yodayuuki55** [comment]
> @yodayuuki55 your mordred container is stopped I guess you will see it if you execute `docker ps -a`. You have to restart the mordred container `docker restart dockercompose_mordred_1` or `docker-compose up -d`

You are right! My mordred container is stopped.
![4)8{4FW{P46$%C2@%5391VA](https://user-images.githubusercontent.com/87411538/130625733-05af8802-226d-4015-98f3-8bda5d6f7ab9.png)

But after using `docker restart dockercompose_mordred_1` or ` docker-compose up -d` , my mordred is started less than 1 second and then it is stopped.
![0A$4 XTSSHFBJUM(TNA~H9](https://user-images.githubusercontent.com/87411538/130626690-cef4769c-342a-4f5b-9aad-6958bcfd7d3c.png)

The following is my `docker-compose.yml` about `mordred` : 

>   mordred:
      restart: on-failure:5
      image: bitergia/mordred:latest
      volumes:
        - ../default-grimoirelab-settings/setup.cfg:/home/bitergia/conf/setup.cfg
        - ../default-grimoirelab-settings/aliases.json:/home/bitergia/conf/aliases.json
        - ../default-grimoirelab-settings/projects.json:/home/bitergia/conf/projects.json
        - ../default-grimoirelab-settings/organizations.json:/home/bitergia/conf/organizations.json
        - ../default-grimoirelab-settings/identities.yml:/home/bitergia/conf/identities.yml
        - /tmp/:/home/bitergia/logs
        - /home/NAME/mordred-log:/home/bitergia/logs
      depends_on:
        - mariadb
        - elasticsearch
      mem_limit: 4g

**Comment by zhquan** [comment]
@yodayuuki55 - Check the Mordred container logs executing `docker logs dockercompose_mordred_1`

**Comment by yodayuuki55** [comment]
> @yodayuuki55 - Check the Mordred container logs executing `docker logs dockercompose_mordred_1`

> Traceback (most recent call last):
  File "/usr/local/bin/sirmordred", line 118, in <module>
    logger = setup_logs(logs_dir, debug_mode)
  File "/usr/local/bin/sirmordred", line 61, in setup_logs
    fh = logging.FileHandler(fh_filepath)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/bitergia/logs/all.log'

**Comment by zhquan** [comment]
@yodayuuki55 I see in your `docker-compose.yml` two volumes for `/home/bitergia/logs`
```
- /tmp/:/home/bitergia/logs
- /home/NAME/mordred-log:/home/bitergia/logs
```

>PermissionError: [Errno 13] Permission denied: '/home/bitergia/logs/all.log'

docker has no permission to access `/home/NAME/mordred-log/` and/or `/tmp/`.

If you want to keep your logs in `/home/NAME/mordred-log` you have to remove the other. And make sure docker has read and write permissions in `/home/NAME/mordred-log`.

If you have issues to know  your docker user execute this `chmod 777 /home/NAME/mordred-log`.

And restart the Mordred container.

**Comment by yodayuuki55** [comment]
> @yodayuuki55 I see in your `docker-compose.yml` two volumes for `/home/bitergia/logs`
> 
> ```
> - /tmp/:/home/bitergia/logs
> - /home/NAME/mordred-log:/home/bitergia/logs
> ```
> 
> > PermissionError: [Errno 13] Permission denied: '/home/bitergia/logs/all.log'
> 
> docker has no permission to access `/home/NAME/mordred-log/` and/or `/tmp/`.
> 
> If you want to keep your logs in `/home/NAME/mordred-log` you have to remove the other. And make sure docker has read and write permissions in `/home/NAME/mordred-log`.
> 
> If you have issues to know your docker user execute this `chmod 777 /home/NAME/mordred-log`.
> 
> And restart the Mordred container.

Thanks a lot! It works!

And now,I can see datas on my dashboard! I am truly grateful for your help @zhquan  @vchrombie

**Comment by yodayuuki55** [comment]
@zhquan I think i can close this issue,thanks! 👍
