### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab#451]
[Hacktoberfest](https://hacktoberfest.digitalocean.com/) is an annual event hosted by DigitalOcean that aims to encourage developers to contribute to open-source projects and give back to the community.

GrimoireLab project would be interested to be participating this year in Hacktoberfest. This issue is a starting point, to provide all the relevant information needed for you.

## How to participate 

1. [Register on the Hacktoberfest website](https://hacktoberfest.digitalocean.com/register) using your GitHub Account.
2. Look for some good first issues in the participating repositories (labelled with the topic: `hacktoberfest`).
3. Fork the project, work on the issue and send a pull request.
4. Participate in the review process and get your work approved & the PR merged by the maintainers of the project.
5. Continue contributing. :)

## Where to start?

We recommend to start with the [GrimoireLab tutorial](https://chaoss.github.io/grimoirelab-tutorial/). It's a long tutorial - you don't have to finish it - but you will get an idea of how the platform works and what components are part of it.

Once you think you are able to move to the next step, you can setup up grimoirelab and start playing with it. If you want to setup grimoirelab without much hassle, you can use the [docker-compose method](https://github.com/chaoss/grimoirelab/tree/master/docker-compose). This method is not suggested if you are planning to contribute code. If you want to setup grimoirelab locally using the source code, we recommend you to follow the [guide for developers](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md). With that guide, you will configure the development environment and you will be ready to start contributing on GrimoireLab.

## How to contribute?

0. Read the [contributing guidelines](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md). This guide is applicable for all the contributions to the [GrimoireLab components](https://github.com/chaoss/grimoirelab#grimoirelab-components).
1. Please comment on the issue if you are interested to pick it up for solving it. You can use the issues for any discussion/doubts related to the issue. You can also **open your own issues** if you found a bug while you were following the tutorial or testing the platform.
2. The [CHAOSS Charter](https://github.com/chaoss/governance/blob/master/project-charter.md) requires that contributions are accompanied by a [Developer Certificate of Origin sign-off](http://developercertificate.org). For ensuring it, a bot checks all incoming commits. So, be sure to [check the instructions](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#dco-and-sign-off-for-contributions) before contributing.
3. It would be easy for the maintainers to review the PRs with good commit messages. Please make sure you check the [guidelines to write good commit messages](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages).

## Issues to start with

* [chaoss/grimoirelab-perceval](https://github.com/chaoss/grimoirelab-perceval)
  * https://github.com/chaoss/grimoirelab-perceval/issues/691

* [chaoss/grimoirelab-elk](https://github.com/chaoss/grimoirelab-elk)
  * https://github.com/chaoss/grimoirelab-elk/issues/1010

* [chaoss/grimoirelab-tutorial](https://github.com/chaoss/grimoirelab-tutorial)
  * https://github.com/chaoss/grimoirelab-tutorial/issues/183
  * https://github.com/chaoss/grimoirelab-tutorial/issues/186

* [chaoss/grimoirelab-sirmordred](https://github.com/chaoss/grimoirelab-sirmordred)

* misc
  * **Add tests to improve coverage:** Most of the [GrimoireLab tools](https://github.com/chaoss/grimoirelab#grimoirelab-components) are written in Python. This aim of this task is to add tests to increase the coverage of the source code. You are free to choose any repository and open a PR to add more tests.
  * **Documentation:** You can open a PR to fix typos, broken links or add missing documentation such as running the test suite etc.

**Note:** Please ask the maintainers and get your PRs labelled accordingly.

## Resources

Please go through the [Hacktoberfest Resources](https://hacktoberfest.digitalocean.com/resources)
- [Beginners](https://hacktoberfest.digitalocean.com/resources/beginners)
- [Participation](https://hacktoberfest.digitalocean.com/resources/participation)
- [Quality Standards](https://hacktoberfest.digitalocean.com/resources/qualitystandards)

**Comment by codewith-arijit** [comment]
Hi, I am interested to work on #691
If the issue is open. Can I be assigned on it?

**Comment by vchrombie** [comment]
Closing the issue as Hacktoberfest 2021 is completed.
