### ISSUE TITLE
[question]Enrollments table is filled at which stage？

### ISSUE THREAD

**Issue by shanchenqi** [chaoss/grimoirelab#458]
Excuse me, when I run grimoirelab with the sirmordred -c command, I will get uuid and organization_id message in the Enrollments table. After checking the Identities table, I found that it seems to use the user's email domain information to obtain the organization_ id and fill the Enrollments table. For example, if the user's email is xxx@sina.com, the organization_id is 1640 in the Domains_organizations table,  the organization_id of the user in the Enrollments table will be 1640.

Could I ask when was this step completed? I tried to run the code in the editor with the following command ,  `python micro.py --enrich --debug --cfg ./setup.cfg --backends git --logs-dir `.I have tried `--raw `and `--enrich` but the enrollments table was not filled in. When was the enrollments table filled?

**Comment by zhquan** [comment]
Hi @shanchenqi 

Sorry for the late reply.

First of all, you have to add an organization and assign a domain (sina.com) to that organization. There are several ways to add organizations:
1. Use [sortinghat](https://github.com/chaoss/grimoirelab-sortinghat)
  1.1 `sortinghat --host xxx -u xxx -p xxx --database xxx orgs -a ORG`
  1.2 `sortinghat --host xxx -u xxx -p xxx --database xxx orgs -a ORG sina.com`
2. Use [orgs_file](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/docker/example_conf/setup.cfg#L25), remember to activate `load_orgs = true`. Here an example of the file https://github.com/chaoss/grimoirelab-sirmordred/blob/master/tests/data/orgs_sortinghat.json

At this point, your `organizations` and `domain_organizations` table are filled.

Now you have to activate [affiliate](https://github.com/chaoss/grimoirelab-sirmordred#sortinghat) in your `setup.cfg` file or `--identities-merge` if you are using `micro.py`

For instance:

Only execute this at the very first time and if the database does not exist. Skip this step if you have a database
```
sortinghat --host localhost -u root -p root init test_sh
```
Add the organization `Sina` with the domain `sina.com`

```
sortinghat --host localhost -u root -p root --database test_sh orgs -a Sina
sortinghat --host localhost -u root -p root --database test_sh orgs -a Sina sina.com
```
In your `sortinghat` section you have at least
```
[sortinghat]
host = localhost
user = root
password = root
database = test_sh
affiliate = true
```
Execute micro.py with `--identities-merge`  and check your `enrollments` table when the process is finished. Also, activate `--enrich` to update the data in your enriched index
```
micro.py --identities-merge --enrich --setup ./setup.cfg --backends git
```

I hope it helps you.

Best,
Quan

**Comment by shanchenqi** [comment]
@zhquan Thanks for your help! I run  _micro.py --identities-merge_， the table enrollments will be filled in. I will continue to take a look at these processes and pay more attention to the interaction with MariaDB.
