### ISSUE TITLE
Create a repository with common GitHub actions

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab#462]
We have decided to create a new repository (https://github.com/chaoss/grimoirelab-github-actions) for the common GitHub Actions for all the Grimoirelab repositories. This new repository will contain the following actions that are already implemented:
- Build a Python package using Poetry
- Create a release from a tag
- Publish the poetry package to PyPI

**Comment by vchrombie** [comment]
> We have decided to create a new repository (https://github.com/chaoss/grimoirelab-github-actions) for the common GitHub Actions for all the Grimoirelab repositories. This new repository will contain the following actions that are already implemented:

This is awesome! :rocket:

**Comment by sduenas** [comment]
@jjmerchante I've reviewed the PR.

**Comment by sduenas** [comment]
I merged the PR. We can close this ticket.
