### ISSUE TITLE
Support Poetry in every GrimoireLab component

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab#464]
Currently we are using Pip for package installation and testing of the packages. The idea is to migrate to Poetry to make the packaging and dependencies easier to manage.

We have decided to use Poetry in all the GrimoireLab components. Opening this issue to track the status of all the components:
- [x] grimoirelab-toolkit
- [x] perceval
- [x] perceval-*
  - [x] perceval-mozilla
  - [x] perceval-opnfv
  - [x] perceval-puppet
  - [x] perceval-weblate
  - [x] perceval-finos
- [x] grimoireelk
- [x] sortinghat (old)
- [x] sortinghat (new)
- [x] sirmordred
- [x] sigils
- [x] kingarthur
- [x] cereslib
- [x] kidash
- [x] graal
- [x] grimoirelab

**Comment by vchrombie** [comment]
Only this repo [chaoss/grimoirelab](https://github.com/chaoss/grimoirelab) is left in the list of projects for Poetry to be integrated. We can start rolling out releases https://github.com/chaoss/grimoirelab/issues/467 once we have Poetry integrated with all the components.

**Comment by sduenas** [comment]
We completed this task. All the components and repositories have poetry integrated. Thanks for your work @jjmerchante @vchrombie .
