### ISSUE TITLE
Use Poetry for GitHub Actions tests in Grimoirelab components

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab#465]
With the migration to Poetry for dependency management, we are migrating GitHub action tests to use Poetry.

This issue is open to track the status of all components:
- [x] grimoirelab-toolkit
- [x] perceval
- [x] perceval-*
  - [x] perceval-mozilla
  - [x] perceval-opnfv
  - [x] perceval-puppet
  - [x] perceval-weblate
  - [ ] perceval-finos (to be decommissioned soon)
- [x] grimoireelk
- [x] sortinghat (old)
- [x] sortinghat (new)
- [x] sirmordred
- [x] sigils
- [x] kingarthur
- [x] cereslib
- [ ] kidash (doesn't have a test suite, doesn't need a CI)
- [x] graal

**Comment by vchrombie** [comment]
One PR is left for merging :point_right: https://github.com/chaoss/grimoirelab-perceval-mozilla/pull/59
The rest of the tasks mentioned in the https://github.com/chaoss/grimoirelab/issues/465#issue-1126180036 are completed.

`perceval-finos` would be decommissioned soon 
`kidash` doesn't have a test suite, so there would be no CI

**Comment by vchrombie** [comment]
We have completed all the planned tasks in this issue, so closing it :partying_face: 
cc @sduenas @jjmerchante
