### ISSUE TITLE
Add workflow to GrimoireLab components to check if a changelog was included

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab#466]
GrimoireLab will start using [Bitergia/release-tools](https://github.com/Bitergia/release-tools) for the automation of releases.

From now on, it will be mandatory in most of the pull requests to include a changelog file with a brief summary of the changes made. That file will be used for the future release notes.

Each repository will run a GitHub Action to verify if every pull request contains a changelog file and validate that it has the right format.

This issue is open to track the addition of this new workflow to each component:
- [x] grimoirelab-toolkit
- [x] perceval
- [x] perceval-*
  - [x] perceval-mozilla
  - [x] perceval-opnfv
  - [x] perceval-puppet
  - [x] perceval-weblate
  - [ ] ~perceval-finos~ (to be decommissioned soon, see [#22-comment](https://github.com/Bitergia/grimoirelab-perceval-finos/pull/22#issuecomment-1039030682))
- [x] grimoireelk
- [x] sortinghat (old)
- [x] sortinghat (new)
- [x] sirmordred
- [x] sigils
- [x] kingarthur
- [x] cereslib
- [x] kidash
- [x] graal

**Comment by vchrombie** [comment]
I can confirm that we have completed all the tasks which are added in the https://github.com/chaoss/grimoirelab/issues/466#issue-1126194062

We have one PR pending for review :point_right: https://github.com/chaoss/grimoirelab-sigils/pull/499
@zhquan would you mind taking a look at it?

**Comment by sduenas** [comment]
@vchrombie I already merged the sigils PR so I think we can close this issue. Please re-open it if you see something else is missing.
