### ISSUE TITLE
Create releases for each GrimoireLab component using GitHub actions

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab#467]
The creation of future releases will be automatically. For that reason it will be necessary to include a new GitHub action workflow that automates the process.

When a new tag is created, the new workflow will perform the following actions:
- Build the package using Poetry.
- Test the built package using the tests of the repository.
- Create a GitHub release based on the new tag.
- Publish the package in PyPI using Poetry.

This issue is open to track the addition of the new release workflow to each component:
- [x] grimoirelab-toolkit
- [x] perceval
- [x] perceval-*
  - [x] perceval-mozilla
  - [x] perceval-opnfv
  - [x] perceval-puppet
  - [x] perceval-weblate
  - [ ] perceval-finos (to be decommissioned)
- [x] grimoireelk
- [x] sortinghat (old)
- [x] sortinghat (new)
- [x] sirmordred
- [x] sigils
- [x] kingarthur
- [x] cereslib
- [x] kidash
- [x] graal
- [x] grimoirelab

**Comment by vchrombie** [comment]
> There is an open PR [chaoss/grimoirelab-elk#1030](https://github.com/chaoss/grimoirelab-elk/pull/1030)

This is merged!

> > sortinghat (new)
> 
> We still need to decide about this.

A PR is opened, https://github.com/chaoss/grimoirelab-sortinghat/pull/613

We are close to completing this task too. :tada:

**Comment by sduenas** [comment]
@vchrombie pr merged. I think we have completed all the tasks here!

**Comment by vchrombie** [comment]
Yes, we can close the issue.
Thanks, @jjmerchante, and @sduenas for making this happen.

Let's roll out the releases soon!
