### ISSUE TITLE
Move all repos to the chaoss GitHub organization

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab#47]
This is issue is to move all repositories in the grimoirelab organization to the chaoss organization, following the following schema:

* grimoirelab/perceval -> chaoss/grimoirelab-perceval
* grimoirelab/perceval-opnfv -> chaoss/grimoirelab-perceval-opnfv
* grimoirelab/perceval-mozilla -> chaoss/grimoirelab-perceval-mozilla
* grimoirelab/perceval-puppet -> chaoss/grimoirelab-perceval-puppet
* grimoirelab/arthur -> chaoss/grimoirelab-kingarthur
* grimoirelab/GrimoireELK -> chaoss/grimoirelab-elk
* grimoirelab/grimoirelab-toolkit -> chaoss/grimoirelab-toolkit
* grimoirelab/sortinghat -> chaoss/grimoirelab-sortinghat
* grimoirelab/mordred -> chaoss/grimoirelab-mordred
* grimoirelab/panels -> chaoss/grimoirelab-sigils
* grimoirelab/reports -> chaoss/grimoirelab-manuscripts
* grimoirelab/grimoirelab -> chaoss/grimoirelab
* grimoirelab/training -> chaoss/grimoirelab-tutotrial
* grimoirelab/grimoirelab.github.io -> chaoss/grimoirelab-web
* grimoirelab/use_cases -> DEPRECATED

The plan will be desscribed in comments to this issue.

**Comment by jgbarah** [comment]
In short, we will proceed in this order:

* grimoirelab/training. Check all issues related to moving the repo, redirections of old repos, permissions, etc.
* grimoirelab/reports. Check all issues related to TravisCI, automated builds and tests, etc.
* All the other repos, in a short period of time afterwards.

All of this will be communicated in the mailing list.

**Comment by jgbarah** [comment]
grimoirelab/training already moved to chaoss/grimoirelab-tutotrial. The "old" repo link, https://github.com/grimoirelab/training still works, pointing to the new one.

I've also updated the machinery for syncing with GitBook.

**Comment by jgbarah** [comment]
grimoirelab/grimoirelab already moved to chaoss/grimoirelab. The "old" repo link still works.

**Comment by jgbarah** [comment]
kidash (formerly part of GrimoireELK) moved to a new repo, chaoss/grimoirelab-kidash.

**Comment by jgbarah** [comment]
grimoirelab/reports moved to chaoss/manuscripts

**Comment by jgbarah** [comment]
* grimoirelab/panels moved to chaoss/grimoirelab-sigils
* grimoirelab/mordred moved to chaoss/grimoirelab-mordred
* grimoirelab/sortinghat moved to chaoss/grimoirelab-sortinghat

**Comment by jgbarah** [comment]
Kibiter is still missing. I guess with it, the process will be complete. If you notice any problem with these changes, please let me know.

**Comment by acs** [comment]
We have issues with Travis:

https://travis-ci.org/grimoirelab/mordred/builds/341183232?utm_source=github_status&utm_medium=notification

So we need to analyze all repositories to update the Travis configuration.

**Comment by apoorvkhare07** [comment]
@jgbarah Is this issue still up for taking ? 
Would like to work on it. 
Will come up with a PR soon.

**Comment by jgbarah** [comment]
I think this was done long time ago, but we didn't close the issue. Closing it now.
