### ISSUE TITLE
Unable to get git (commit, git authors, git organizations) data from Github.

### ISSUE THREAD

**Issue by brmukum** [chaoss/grimoirelab#471]
Hi! Can I get some help understand what I'm missing? I have GrimoireLab pulling data from Github and it's reporting on things like Github repositories, Github issues and Github PRs. However, when I go to the Git overview page, I see no data found. This is how I defined the git category in my setup.cfg:
```
[git]
api-token = *****
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]
```
This is how it looks like in my projects.json:
```
},
    "git": [
      "https://github.com/MyUsername/example"
    ]
```
Do I need to set something else somewhere to get it working ?

This the git page when I login
<img width="997" alt="image" src="https://user-images.githubusercontent.com/83827605/154973374-97c0f1c3-4da5-4b34-b1f1-c8f498063ba5.png">

**Comment by vchrombie** [comment]
Hi @brmukum, thanks for using GrimoireLab and opening this issue for clarifying your doubts.

> ```
> [git]
> api-token = *****
> raw_index = git_demo_raw
> enriched_index = git_demo_enriched
> latest-items = true
> studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]
> ```

Unlike the github related data sources, git doesn't really need a `api-token` parameter. But, if the repository is private, you need to make sure you pass the credentials (`username` and `api-token`) in the URL itself.

You can find an example at https://chaoss.github.io/grimoirelab-tutorial/docs/data-sources/configurations/#git

> This is how it looks like in my projects.json:
> 
> ```
> },
>     "git": [
>       "https://github.com/MyUsername/example"
>     ]
> ```

The `projects.json` configurations look good to me, but in any case, I would suggest you check for any formatting issues using https://jsonformatter.curiousconcept.com

I hope this would solve your issue. Please let us know.

**Comment by brmukum** [comment]
Hey [vchrombie](https://github.com/vchrombie),  thanks very much! Adding the api token to the git setup made it work. I have one more question: Is there a way to pass in api-tokens securely to the projects.json or setup.cfg if I choose to store my grimoirelab files in a github repository ? I wouldn't want the tokens wide open in Github.

**Comment by vchrombie** [comment]
> Hey [vchrombie](https://github.com/vchrombie), thanks very much! Adding the api token to the git setup made it work.

Good to know it worked. Thanks for trying it.

> I have one more question: Is there a way to pass in api-tokens securely to the projects.json or setup.cfg if I choose to store my grimoirelab files in a github repository ? I wouldn't want the tokens wide open in Github.

I'm really sorry about it, I don't think there is an explicit way to do it. But, I liked the idea. It would be great if yo can open a new issue for relevant discussion.

Also, adding to the conversation, we have a project [zhquan/Q-DashMan](https://github.com/zhquan/Q-DashMan) built by one of our maintainers which kinda solves this issue by eliminating the config files altogether. If you are interested, please check it out.

**Comment by vchrombie** [comment]
Closing this issue since it is solved, please feel free to open a new one for any new doubts.
