### ISSUE TITLE
Configure organizations

### ISSUE THREAD

**Issue by brmukum** [chaoss/grimoirelab#474]
Hey team, I was wondering how we could configure organizations. Currently, I have git repositories defined in the projects.json. I want to organize them under multiple organizations. This is how the organizations icon looks like but I want to break it down.
Any idea how to go about this ? Any files I have to configure ? Thanks!
![image](https://user-images.githubusercontent.com/83827605/156409518-4b6f633c-5959-4fa9-928d-a5131cb01218.png)

I was hoping to make it look like this

![image](https://user-images.githubusercontent.com/83827605/156411845-ccc6c94d-aff3-4754-81f9-7a6a09577196.png)

**Comment by zhquan** [comment]
Hi @brmukum 

You have to affiliate profiles to organizations.

There are several ways to do it.
1. Create an identities YAML file as https://gitlab.com/Bitergia/c/CHAOSS/profiles/-/blob/master/identities.yaml and add this on your setup.cfg, more info click [here](https://github.com/chaoss/grimoirelab-sirmordred#sortinghat)
```
[sortinghat]
identities_format = grimoirelab
identities_api_token = xxx
identities_file = [https://gitlab.com/api/v4/projects/4101460/repository/files/identities.yaml/raw?ref=master]
```
2. Use [Sortinghat](https://github.com/chaoss/grimoirelab-sortinghat)
3. use [Hatstall](https://github.com/chaoss/grimoirelab-hatstall)

I hope it helps you.

Best,
Quan

**Comment by brmukum** [comment]
Is organizations in this context Github organizations or custom-created organizations ? Is the identities.yml file related to what is in the organizations.json file ?

**Comment by brmukum** [comment]
Thanks Zhquan! Just one last clarification: These organizations are basically external or internal organizations (companies or enterprises) that are part of the project, yes ?

**Comment by zhquan** [comment]
External

**Comment by bmukum** [comment]
Thanks!
