### ISSUE TITLE
Jira

### ISSUE THREAD

**Issue by brmukum** [chaoss/grimoirelab#478]
Hi GrimoireLab! Is there a way to pull jira data from a particular jira project or list of projects ?
This example in this documentation provides the URL of the jira server. 
```
{
    "Chaoss":{
        "jira": [
            "https://company.atlassian.net"
        ]
    }
}
```
What if I have a jira project known as Mobile or frontend-app ? How do I get jira data only from these projects and not every single thing in jira ?

Thanks.

**Comment by zhquan** [comment]
Hi @brmukum 

In your setup.cfg you can set the project like
```
[jira]
project = Mobile
```

Right now if you want to add more projects you have to create more sections for example
projects.json
```
{
    "Chaoss":{
        "jira:mobile": [
            "https://company.atlassian.net"
        ],
        "jira:frontend": [
            "https://company.atlassian.net"
        ]
    }
}
```
setup.cfg
```
[jira:mobile]
project = Mobile

[jira:frontend]
project = frontend-app
```

Best,
Quan

**Comment by brmukum** [comment]
Thanks,@zhquan ! It worked fine.

**Comment by zhquan** [comment]
I close the issue.

Feel free to reopen the issue.
