### ISSUE TITLE
docker-compose_mordred_1 with state Exit_1

### ISSUE THREAD

**Issue by uyaharneit** [chaoss/grimoirelab#484]
Hi,

I'm trying to run all the containers with docker-compose and I always got mordred state in Exit state.
I have already tried the suggestion given on issued  #436  but still got error. Why was wrong with my docker-compose?

I think the main problem is from here:

  | cp: cannot open 'shdb.cfg' for reading: Permission denied

But, I'm not sure because I'm completely new with this tool and have to use this for my studying.

And, here is what I got from the logs:

[logs.txt](https://github.com/chaoss/grimoirelab/files/8532486/logs.txt)

Please, really need your help!

Thanks in advance,
Neit

**Comment by zhquan** [comment]
Hi @uyaharneit 

> mordred_1        |     logs_dir = config_dict['general']['logs_dir']
> mordred_1        | KeyError: 'logs_dir'

Check your ´setup.cfg´ and make sure to add `logs_dir = /home/bitergia/logs` in the `general` section. And restart the mordred container.

I hope it helps you.

**Comment by uyaharneit** [comment]
It was already there. And it still doesn't work.

I think it's still a problem because my sudo user account doesn't have full access(my ubuntu was installed from the server at my campus). I tried to run it on other computer which is my own laptop and it works.
Thanks anyway for your reply.

**Comment by zhquan** [comment]
I guess your `docker` has no permission to read `setup.cfg`.

If you are using this https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml#L51 make sure that `docker` has read permission to all of them and write permission to `/tmp`

**Comment by uyaharneit** [comment]
Hi @zhquan

Sorry for my late reply. I tried run it using 'docker' instead 'docker-compose' and it works.
Thanks again for your help, anyway.

**Comment by vchrombie** [comment]
Hi @uyaharneit, please feel free to close the issue if it is resolved.

**Comment by uyaharneit** [comment]
> Hi @uyaharneit, please feel free to close the issue if it is resolved.

Sure. Thanks
