### ISSUE TITLE
Error in docker-compose-mordred

### ISSUE THREAD

**Issue by uyaharneit** [chaoss/grimoirelab#486]
Hi all,

I tried to run docker compose and have configured the setup and projects file and I got this error:

### docker-compose-mordred-1        | 2022-05-03 14:35:35,970 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/E-Grid/): 404 Client Error: Not Found for url: https://api.github.com/repos/E-Grid//issues?state=all&per_page=100&direction=asc&sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00
docker-compose-mordred-1        | Traceback (most recent call last):
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/elk.py", line 171, in feed_backend
docker-compose-mordred-1        |     ocean_backend.feed(**params)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/raw/elastic.py", line 231, in feed
docker-compose-mordred-1        |     self.feed_items(items)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/raw/elastic.py", line 247, in feed_items
docker-compose-mordred-1        |     for item in items:
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 316, in fetch
docker-compose-mordred-1        |     for item in self.fetch_items(category, **kwargs):
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 311, in __fetch_issues
docker-compose-mordred-1        |     for raw_issues in issues_groups:
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 915, in fetch_items
docker-compose-mordred-1        |     response = self.fetch(url_next, payload=payload)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 897, in fetch
docker-compose-mordred-1        |     response = super().fetch(url, payload, headers, method, stream, auth)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/perceval/client.py", line 143, in fetch
docker-compose-mordred-1        |     response = self._fetch_from_remote(url, payload, headers, method, stream, auth)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/perceval/client.py", line 186, in _fetch_from_remote
docker-compose-mordred-1        |     raise e
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/perceval/client.py", line 181, in _fetch_from_remote
docker-compose-mordred-1        |     response.raise_for_status()
docker-compose-mordred-1        |   File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
docker-compose-mordred-1        |     raise HTTPError(http_error_msg, response=self)
docker-compose-mordred-1        | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/E-Grid//issues?state=all&per_page=100&direction=asc&sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00

What was wrong with my mordred? Thanks in advance

cheers

**Comment by uyaharneit** [comment]
This is the setup.cfg:

[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = mariadb
user = root
password =
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
gitlab-issues = true
gitlab-merges = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

#[bugzillarest]
#raw_index = bugzillarest_demo_raw
#enriched_index = bugzillarest_demo_enriched
#no-archive = true

#[confluence]
#no-archive = true
#raw_index = confluence_demo_raw
#enriched_index = confluence_demo_enriched

#[discourse]
#raw_index = discourse_demo_raw
#enriched_index = discourse_demo_enriched
#no-archive = true

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
api-token = ghp_8oB7
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched

[github:issue]
raw_index = github_raw
enriched_index = github_enriched
api-token = ghp_8o
category = issue
sleep-for-rate = true
no-archive = true
#studies = [enrich_onion:github,
#           enrich_geolocation:user,
#           enrich_geolocation:assignee,
#           enrich_extra_data:github,
#           enrich_backlog_analysis,
#           enrich_demography:github]

[github:pull]
raw_index = github-pull_raw
enriched_index = github-pull_enriched
api-token = ghp__
category = pull_request
sleep-for-rate = true
no-archive = true
#studies = [enrich_geolocation:user,
#           enrich_geolocation:assignee,
#           enrich_extra_data:github,
#           enrich_demography:github] 

[enrich_onion:github]
in_index_iss = github_issues_onion-src
in_index_prs = github_prs_onion-src
out_index_iss = github-issues-onion_enriched
out_index_prs = github-prs-onion_enriched

[enrich_geolocation:user]
location_field = user_location
geolocation_field = user_geolocation

[enrich_geolocation:assignee]
location_field = assignee_location
geolocation_field = assignee_geolocation

[enrich_extra_data:github]
json_url = https://gist.githubusercontent.com/zhquan/bb48654bed8a835ab2ba9a149230b11a/raw/5eef38de508e0a99fa9772db8aef114042e82e47/bitergia-example.txt

[enrich_backlog_analysis]
out_index = github_enrich_backlog
interval_days = 7
reduced_labels = [bug,enhancement]
map_label = [others, bugs, enhancements]

[enrich_demography:github]

#[gitlab:issues]
#api-token = <YOUR_API_TOKEN_HERE>
#raw_index = gitlab_issues_demo_raw
#enriched_index = gitlab_issues_demo_enriched
#no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
#sleep-for-rate = true

#[gitlab:merge]
#api-token = <YOUR_API_TOKEN_HERE>
#raw_index = gitlab_merges_demo_raw
#enriched_index = gitlab_merges_demo_enriched
#no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
#category = merge_request
#sleep-for-rate = true

#[jira]
#raw_index = jira_demo_raw
#enriched_index = jira_demo_enriched
#no-archive = true

#[pipermail]
#raw_index = pipermail_demo_raw
#enriched_index = pipermail_demo_enriched
#no-verify = true

#[mediawiki]
#raw_index = mediawiki_demo_raw
#enriched_index = mediawiki_demo_enriched
#no-archive = true

#[meetup]
#raw_index = meetup_demo_raw
#enriched_index = meetup_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = "300"

#[stackexchange]
#raw_index = stackexchange_demo_raw
#enriched_index = stackexchange_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[slack]
#raw_index = slack_demo_raw
#enriched_index = slack_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[supybot]
#raw_index = supybot_demo_raw
#enriched_index = supybot_demo_enriched

#[twitter]
#raw_index = twitter_demo_raw
#enriched_index = twitter_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = 300

## studies based on enriched indexes

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash

**Comment by zhquan** [comment]
Try this projects.json
```
{
    "eclipse": {
        "meta": {
            "title": "eclipse"
        },
        "git": [
            "https://github.com/SasCezar/E-Grid.git"
        ],
        "github:issue": [
            "https://github.com/SasCezar/E-Grid"
        ],
        "github:pull": [
            "https://github.com/SasCezar/E-Grid"
        ]
    }
}
```

**Comment by uyaharneit** [comment]
Hi @zhquan,

Thank you for your quick reply. It works now and I'll close the issue
