### ISSUE TITLE
wants to remove gitlab visuals

### ISSUE THREAD

**Issue by mohlatif227** [chaoss/grimoirelab#488]
Hello,

I'm able to get data from git and github using as data sources, however I see there is GitLab visuals as well and this doesn't have any data and we are not using GitLab. Could you please help me to remove these GitLab visuals from Dashboard. Attaching screenshot for reference.

![image](https://user-images.githubusercontent.com/27799983/167883192-242c4ad9-196f-47db-85e9-842fcd077879.png)

Thank you,

--
Altif

**Comment by zhquan** [comment]
Hi @mohlatif227 

To remove visualizations from the dashboard follow these steps:
1. Click on `edit`

![image](https://user-images.githubusercontent.com/5637233/167895921-5525ebd0-4cb6-41b4-8004-1ed4a600c41b.png)

2. Click on `setting icon` and `Delete from dashboard`

![image](https://user-images.githubusercontent.com/5637233/167896354-b9b8c4a3-5954-416c-ae5c-67092ca6aa92.png)

3. Click on `save` to save the dashboard

![image](https://user-images.githubusercontent.com/5637233/167897067-deb38af0-dafc-4a76-a6b3-711c0d6e3793.png)


I hope it helps you.

**Comment by mohlatif227** [comment]
Thanks a lot @zhquan , it really helped.

--
Altif

**Comment by zhquan** [comment]
@mohlatif227 - Please close the issue, if you were able to solve it, thanks.

**Comment by mohlatif227** [comment]
Resolved, hence closing the issue.
