### ISSUE TITLE
HTTP 503 error while reaching Kibana server 

### ISSUE THREAD

**Issue by kiranravindran90** [chaoss/grimoirelab#498]
We installed Grimoirelab successfully. But we are unable to access the GUI & getting HTTP 503 error, Kibana server isnt ready.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/90866692/174532669-01a4f1e5-a49b-447e-b0f1-0b7ee0c96827.png)

OS is UBUNTU 21.04.

**Comment by zhquan** [comment]
Hi @kiranravindran90 

I need more information.
- ElasticSearch and Kibana version
- Are you using docker-compose?

Best,
Quan

**Comment by kiranravindran90** [comment]
Hi Quan,
 Yes I used docker-compose.
Just followed these steps & didnt do anything else (assumed Kibana & ElasticSearch gets installed as a package)
![image](https://user-images.githubusercontent.com/90866692/174716044-67105a18-42b9-4ae0-9723-497f8cc7f8c6.png)

But I observed none of the Kibana & ElasticSearch commands work. Should these be separately installed?

**Comment by zhquan** [comment]
In that docker-compose there are 5 dockers (mariadb, hatstall, elasticsearch, kibiter, and mordred). After running `docker-compose up -d` you will see all those containers 
```
$ docker-compose up -d
Creating network "docker-compose_default" with the default driver
Creating docker-compose_elasticsearch_1 ... done
Creating docker-compose_mariadb_1       ... done
Creating docker-compose_hatstall_1      ... done
Creating docker-compose_kibiter_1       ... done
Creating docker-compose_mordred_1       ... done
```

Remember that if elasticsearch is not ready, kibiter will return something like `Kibana server is not ready yet`

You can run `docker logs <container_name>` to see the logs

**Comment by kiranravindran90** [comment]
Hi Quan,  Elastic Search was missing. I am not sure why the initial docker compose but re-did the docker compose & it seemed to work & the GUI is accessible now.
Thank you for the suggestion,
