### ISSUE TITLE
Create Grimoirelab release using GitHub Actions

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab#499]
The creation of future releases will be automatically. For that reason it will be necessary to include a new GitHub action workflow that automates the process.

The goal for this issue is to create a release for each Grimoirelab module using [release-tools](https://github.com/Bitergia/release-tools).

The new GitHub workflow will create a new version for each package using the following steps:

- Update Grimoirelab package dependencies 
- Call to `semverup` to increase the version number
- Generate the release notes using `notes`
- Publish a new tag in the repository using `publish` that will start the `release` workflow
- Wait until the release is completed.

Each package will wait until the dependent packages have finished.

**Comment by sduenas** [comment]
We were finally able to build a release using the pipeline. Good work!

**Comment by vchrombie** [comment]
Awesome! 🎉
