### ISSUE TITLE
Issue with PyCharm & Micro.py

### ISSUE THREAD

**Issue by kiranravindran90** [chaoss/grimoirelab#500]
I installed Grimoire using docker compose. Installed all the dependencies.

But while setting up PyCharm facing the following issues.
1. The "**Project Interpreter**" option is missing. Instead I have "**Python Interpreter**".
2. I get error that **failed to set virtual environemt while creating project**.
3. Unable to find /locate **micro.py file**.

**Comment by zhquan** [comment]
Did you add all grimoirelab repositories in your `Project Structure` (make sure that you have the latest version of each repository) and could you share your script path and parameters in your `Run/Debug Configurations`?

**Comment by kiranravindran90** [comment]
Yes have added all repo's as far as we know & upgraded all the packages again to make sure. Still same error.

Please find the Run/Debug configurations below (script path included).

<img width="789" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/90866692/176589422-8fdd394c-b296-4cd7-81af-54bc14705a81.png">

Also find the Project Structure.
![InkedMicrosoftTeams-image (1)](https://user-images.githubusercontent.com/90866692/176589938-fa72dd4c-7277-43bd-b6d6-05b5d88753c6.jpg)

**Comment by jjmerchante** [comment]
Hi @kiranravindran90,

`grimoirelab-perceval-finos` is deprecated and is not supported anymore. Can you remove the repository from the list in the `Project Structure`   and try again?

**Comment by kiranravindran90** [comment]
Thank you for the swift response :)

Was able to get through this but stumbled on to a new issue.

I am getting this error --> **'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f52af0454f0>: Failed to establish a new connection: [Errno 111] Connection refused')**.
Detailed log attached.

Tried connecting to the port as mentioned here #297 & its connecting.

Seems its not exactly a connection issue but authentication issue. It asks for authentication (no prompts) & I manually authenticate it on the browser but end up getting the same error still.

Note: Earlier was able to connect to Kibana (5601 port) but now that also seems to have stopped working abruptly.
I am behind a company proxy & firewall.

[CHAOSS_Pycharm_logs.txt](https://github.com/chaoss/grimoirelab/files/9045616/CHAOSS_Pycharm_logs.txt)
.

**Comment by zhquan** [comment]
Could you try to run this curl using the url value of your `[es_collection]` section?
```
curl -XGET -k <es_collection_url>
```
Are you using docker for ElasticSearch and Kibana?

**Comment by vchrombie** [comment]
> I am getting this error --> **'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f52af0454f0>: Failed to establish a new connection: [Errno 111] Connection refused')**. Detailed log attached.

Sometimes it happens if you are restricted to access the internet, the micro mordred need to interact with APIs to fetch the data.

> Note: Earlier was able to connect to Kibana (5601 port) but now that also seems to have stopped working abruptly. I am behind a company proxy & firewall.

Not sure if it is company proxy or firewall causing issue, but please try with another internet source.

Thanks.

**Comment by kiranravindran90** [comment]
> > I am getting this error --> **'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f52af0454f0>: Failed to establish a new connection: [Errno 111] Connection refused')**. Detailed log attached.
> 
> Sometimes it happens if you are restricted to access the internet, the micro mordred need to interact with APIs to fetch the data.
> 
> > Note: Earlier was able to connect to Kibana (5601 port) but now that also seems to have stopped working abruptly. I am behind a company proxy & firewall.
> 
> Not sure if it is company proxy or firewall causing issue, but please try with another internet source.
> 
> Thanks.

Unfortunately its a company project specific laptop & connects only to company network for IT security purposes. :(

**Comment by zhquan** [comment]
curl -XGET http://user:pass@localhost:9200

**Comment by kiranravindran90** [comment]
> `curl -XGET http://user:pass@localhost:9200`

@zhquan Tried this & still getting the same error. i.e. **"Proxy Authorization Required"**

**Comment by zhquan** [comment]
I guess you have to contact your company network admin.

**Comment by vchrombie** [comment]
401 is an Unauthorized response status code

Make sure you have the correct username and password for the elasticsearch instance in the `setup.cfg` file.

If you are using micro mordred, please update in https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/utils/setup.cfg
```
[es_collection]
url = https://admin:admin@localhost:9200

[es_enrichment]
url = https://admin:admin@localhost:9200
```

**Comment by kiranravindran90** [comment]
@zhquan This worked & we are able to get through Elastic Search through 9200. Thank you.

But we are getting an error from grimoirelab-perceval (micro.py). **"perceval.errors.RepositoryError: git command - Cloning into bare repository '/home//.perceval/repositories/https://github.com/chaoss/grimoirelab-perceval-git'...
fatal: unable to access 'https://github.com/chaoss/grimoirelab-perceval/': Failed to connect to github.com port 443: Connection timed out"**

The proxy settings were done for both the system & virtual environment but still getting the error.
We are able access Github path manually but not through the script.
Please find the detailed logs attached.
[error_github_443.txt](https://github.com/chaoss/grimoirelab/files/9131201/error_github_443.txt)

**Comment by zhquan** [comment]
Are you able to clone the repository on your machine?
```
$ git clone https://github.com/chaoss/grimoirelab-perceval.git
```
Could you share your `setup.cfg`?

**Comment by kiranravindran90** [comment]
@zhquan yes cloning the repo gave no issues. Please find the setup.cfg attached below.
[setup.cfg.txt](https://github.com/chaoss/grimoirelab/files/9137861/setup.cfg.txt)

**Comment by kiranravindran90** [comment]
@zhquan Any hints about the issue from the setup.cfg file?

**Comment by zhquan** [comment]
> fatal: unable to access 'https://github.com/chaoss/grimoirelab-perceval/': Failed to connect to github.com port 443: Connection timed out

The setup.cfg looks good. So you can clone the repository on the machine but when you execute micro.py you cannot clone it. Very strange. The error tells you that it can't connect to github.com

And perceval uses this command to clone repositories
```
$ git clone --bare https://github.com/chaoss/grimoirelab-perceval
```

I guess you have a MySQL or MariaDB running on this host and use these credentials.

```
[sortinghat]
host = 127.0.0.1
user = root
password = 
```

**Comment by kiranravindran90** [comment]
@zhquan Yes we have MariaDB running & seems it uses that credentials.
Tried giving the credentials in that place but still seems to be getting this error.

**Comment by kiranravindran90** [comment]
@zhquan Just to add, we are running PyCharm from user folder & not root.
Also see the below snap shots (error when Connecting https GitHub via PyCharm)
![FireFox_Setting](https://user-images.githubusercontent.com/90866692/182795253-c2ca83b0-4629-4879-8370-87d11ef41d2f.png)
Firefox Proxy setting

![PyCharm_Setting](https://user-images.githubusercontent.com/90866692/182795307-03093047-6c68-4f90-9c85-351458622138.png)
PyCharm Proxy setting

![PyCharm_Error_HTTP](https://user-images.githubusercontent.com/90866692/182795355-5ef48d32-e670-4503-accc-c335b647e15b.png)
Error when Checking connection to HTTPS GitHub

![PyCharm_Error_SOCKS](https://user-images.githubusercontent.com/90866692/182795444-d61b87ef-5546-4ef0-b08c-61430326a4c8.png)
Error (SOCKS) when Checking connection.

**Comment by kiranravindran90** [comment]
Unfortunately didn't work. Reinstalled OS & CHAOSS but facing same issue. Seems to be a proxy/firewall issue thru Pycharm. Nonetheless, Cloned all the depended repositories into Local system & updated the scripts to call then from Local system instead of the URL's. That way its working for now.
Thanks all for the support :)
