### ISSUE TITLE
[Build Bug] p2o.py in grimoirelab-elk has been removed, check_run should be changed or removed.

### ISSUE THREAD

**Issue by ME-Msc** [chaoss/grimoirelab#512]
https://github.com/chaoss/grimoirelab/blob/d3dca8d8cb5eb136e23017773716544501e8fd1b/utils/build_grimoirelab#L80

[grimoirelab-elk](https://github.com/chaoss/grimoirelab-elk)

If not, the following error will appear while build grimoirelab with `./build_grimoirelab -l debug --logfile /home/log --build --install --check --relfile ../releases/latest --reposdir /home/repos --install_venv /home/ivenv`
![image](https://user-images.githubusercontent.com/45875501/188341959-fe4003e1-465d-479e-9c66-e9e92b92188f.png)

**Comment by sduenas** [comment]
p2o is no longer supported.
