### ISSUE TITLE
Start using sortinghat on existing indexes

### ISSUE THREAD

**Issue by robinmuilwijk** [chaoss/grimoirelab#53]
This is a follow up on https://github.com/grimoirelab/sortinghat/issues/112

I am ready to setup sortinghat, but wanted to verify e.g. double check on something. My dashboard has been running for over a year now. Based on primarily Grimoire-Elk and vanilla Elasticsearch and Kibana (5.4.x).

Can I install sortinghat and start using it, also on my existing indexes?

I use p2o to import my data, I know I will have to add some parameters so that p2o will also start using sortinghat. I do not need to create new indexes? Sortinghat will just extend them further?

Thanks.

**Comment by robinmuilwijk** [comment]
Feedback already provided by @jgbarah : 
In short, you will need to re-enrich the data. That is, you can use either p2o or Mordred to re-enrich the data, telling it (I mean, telling p2o or Mordred) that you want to use SortingHat. That will inject all identities in the raw indexes in Sorting Hat, and produce new enriched indexes with identities. Of course, you don't need to use the same indexes you're using now: you can just build new enriched indexes, test them, and if they work just create new aliases for them.

Then, it is a matter of improving SortingHat data (by eg merging identities that you know are the same), and re-enrich the enriched indexes with the new SortingHat ids.

The easiest way of doing this is probably to use Mordred. You tell Mordred (in mordred.cfg) that your raw indexes are the ones you already have, and that it produce enriched indexes under new names. And that it uses SortingHat. When Mordred runs with that configuration, it will find the raw indexes, and no enriched indexes, so it will try to produce them. Since it will be told to use SortingHat, it will just use it. Of course, backup all indexes in advance, cross fingers and all that :-O

If you want, I can try to drive you through the process (I was about to write about that for the GrimoireLab tutorial). You can be my guinea pig for a while ;-)

--

We can follow up in a ticket, if you don't mind this discussion being public: that way it could help some others. But if you prefer to go private, let's use email.

In case you prefer to go public, I suggest we open a ticket in chaoss/grimoirelab (formerly grimoirelab/grimoirelab), where we're discussing general stuff related to GrimoireLab, since more modules are going to be involved, in addition to Sorting Hat. We can later close this ticket mentioning that one.

Meanwhile, let me mention that now installation of Sorting Hat and all other components should be much easier. If you want, you can use pre-installed docker containers, have a look at https://grimoirelab.gitbooks.io/tutorial/mordred/mordred-in-a-container.html If you want, maybe I could help you, or your IT people, to move to that kind of deployment. Otherwise, installation via pip should be much more reliable now, too.

**Comment by robinmuilwijk** [comment]
@jgbarah I am preparing the installation of sortinghat this week, and its requirements. I will ping you when this is done on how to actually start configuring and using it.

**Comment by sduenas** [comment]
This is an old bug. For new readers, this can be done using the latest versions of `mordred` and `sortinghat` but you will need to regenerate the enriched indexes.
