### ISSUE TITLE
Gitlab data source support for multiple API keys

### ISSUE THREAD

**Issue by xurizaemon** [chaoss/grimoirelab#536]
Does setup.cfg for GrimoireLab yet handle retrieving data from multiple Gitlab instances, or (in case of protected projects) multiple groups on one instance?

It appears from the [default settings](https://github.com/chaoss/grimoirelab/blob/640d55667ed6c220f6e4b4a4743e48169a605a10/default-grimoirelab-settings/setup.cfg#L79-L94) that there's provision for a single API token, and my understanding now is that the API token is required for Gitlab data retrieval.

https://github.com/chaoss/grimoirelab/blob/640d55667ed6c220f6e4b4a4743e48169a605a10/default-grimoirelab-settings/setup.cfg#L79-L94

If an organisation contributes to projects across several gitlab instances (for us: [gitlab.com](http://gitlab.com/), [git.mahara.org](http://git.mahara.org/), [git.drupalcode.org](http://git.drupalcode.org/), likely others), I'm not sure how they could use setup.cfg to provide that configuration for each of the hosts or projects to index.

It doesn't feel like it would fit so well in projects.json, but I'm mindful that if we needed access to protected projects on a single instance, we might need multiple API keys for a single host. Our organisation contributes to both [gitlab.com/mataara](http://gitlab.com/mataara) and [gitlab.com/samba-team](http://gitlab.com/samba-team) but might have no team members who access both. This doesn't block us (we're only tracking public repos, so the Gitlab token is primarily a rate limiting factor), but for organisations tracking protected repos this will be a bigger issue.

Please let me know if I'm misreading the situation! 😁

**Comment by xurizaemon** [comment]
API keys are doing a few things here!

## Rate limiting

For GitHub, using an API key increases the available rate limit, and being able to iterate through multiple API keys multiplies the available rate limit if you cycle through them. See eg https://github.com/chaoss/grimoirelab-perceval/blob/e8869879ca93e0a53e663f82d0674eb2194c6a44/perceval/backends/core/github.py#L969-L989

For GitHub, using an API key appears to be optional - without an API key, there's a smaller per client IP rate limit which is applied.

For GitLab, using an API key is I believe a requirement - there's no permitted usage without an API key. If true, this means that for each GitLab host we connect to, we need a valid API key, and we need some way to associate the host and the key in our configuration.

## Access control

Separately to rate limiting, both GitHub and GitLab support access to restricted projects by API key. This might not be so significant for open source projects (where read access is typically more open by default) but introduces the implication that API keys are significant not per host but per project (or group/organization).

GitLab API keys can be created scoped to a personal users, a group, or a project.

## How to implement

I'm unfamiliar with GrimoireLab's configuration system but it seems like we might want to consider implementing at least per-host API key support in `setup.cfg`, perhaps by permitting a format like

```ini
[gitlab]
api-token[gitlab.com] = glxx-xxxxxxxx
api-token[git.drupalcode.org] = glxx-yyyyyyyy
api-token[git.mahara.org] = glxx-zzzzzzzz
```

Perhaps this could be a "best match" strategy, so we could add greater specificity if needed:

```ini
api-token[gitlab.com] = glxx-xxxxxxxx
api-token[gitlab.com/samba] = glxx-yyyyyyy
api-token[gitlab.com/behat-chrome] = glxx-zzzzzzzz
```

Or we could put project API keys directly into `projects.json` - as the keys get more project specific, it feels more appropriate to couple to the project?

**Comment by vchrombie** [comment]
That's a wonderful question @xurizaemon!. Thanks for opening the issue.
Thanks @zhquan for answering it.

Do you think we should add this somewhere?
I think we can close the issue since the doubt is clarified. Please let me know otherwise.

Thank you.
Best,
Venu

**Comment by xurizaemon** [comment]
It feels worth documenting - I have yet to test this, having realized I can't yet obtain an API key for git.drupalcode.org and that git.mahara.org isn't yet using the issue queue actively. I will try to PR some docs when I get to it. Happy for this issue to be closed as I can still refer to it when PRing, and reopen if useful. Closing proactively but feel free to reopen if you prefer it "on the radar".
