### ISSUE TITLE
Add support to the data source groups.io 

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab#54]
The service provided by groups.io is started to being used to extend and improve the mailing list services widely used by FLOSS communities like Cloudfoundry.

The API offers a REST endpoint, more info at https://groups.io/api

The first iteration of this support could offer the same support offered to mailman:
- data collection (with all the data related to the message, sender and recipient)
- data enrichment with affiliation support
- overview Kibiter panel (Kibana dashboard) with a Overview of the activity, contributors and repos (origin)

**Comment by jgbarah** [comment]
I think this is done. @sanacl can we close it?

**Comment by sanacl** [comment]
@jgbarah yep, let's close it.
