### ISSUE TITLE
grimoirelab container crashes

### ISSUE THREAD

**Issue by krokoko** [chaoss/grimoirelab#541]
Hi,

When running the docker grimoirelab image, the process crashes after a few seconds:

```
Installing and checking GrimoireLab
sudo: grimoirelab/utils/build_grimoirelab: command not found
Extracting the perceval cache data ...
/home/grimoirelab/stage: line 25: cd: /home/grimoirelab/conf: No such file or directory
Waiting for elasticsearch startup completion ...
Elasticsearch OK
Loading initial raw data ...
/home/grimoirelab/stage: line 37: cd: /home/grimoirelab/conf: No such file or directory
Waiting for kibiter startup completion ...
Kibiter OK
/home/grimoirelab/stage: line 45: mordred: command not found
```
Same thing happens if I run it manually, or through docker-compose.

The other containers seem to be running correctly (I can access the dashboard - shows `Couldn't find any Elasticsearch data` which I guess is expected since the container crashes)

Any idea ? Thanks !

**Comment by sduenas** [comment]
@krokoko recently we changed the image of grimoirelab but we didn't update it on dockerhub. We were working on some CI to do it automatically. It will be ready in a couple of hours. I'll keep you posted.

**Comment by sduenas** [comment]
However, it'll work if you create the image by yourself, if you don't want to wait.

**Comment by sduenas** [comment]
@krokoko we've just updated the docker image to the latest version, please try again. It should work now.

**Comment by vchrombie** [comment]
Thank you @krokoko and @sduenas.
