### ISSUE TITLE
Git Top Authors visual shows only 20 users data

### ISSUE THREAD

**Issue by maltif** [chaoss/grimoirelab#543]
We are using Github as datasource for Grimoire to populate Git users Metrics. We're able to get most of the required data. However, while checking Git Top Authors visual, it does show only data for top 20 Git Authors(per page 10 users). We have around 500 Git users and want to show top 100 users in Git Top Authors visual. Please refer to below screenshot:

![image](https://user-images.githubusercontent.com/100792545/195544552-72ca25c8-3958-4fb4-8af5-592f742bb290.png)

Can someone please help on this?

cc: @zhquan @vchrombie @valeriocos

**Comment by sduenas** [comment]
@maltif you can configure the number of results shown in the visualization. By default it's set to 20. Go to the edit mode, then click on the gear icon on the visualization, and expand the element under the `Buckets` section. Under the `size` box, you can set the number of results you want. It works in a same way for other visualizations than don't show the full list of entries.

**Comment by maltif** [comment]
It worked. Thanks a lot @sduenas.
