### ISSUE TITLE
Github display forks

### ISSUE THREAD

**Issue by krokoko** [chaoss/grimoirelab#546]
Hi team,

I'm a bit confused by the documentation. I am trying to get the display of repo information (forks,...) from github

Following [this link](https://pypi.org/project/profanity-filter/) it seems that I need to setup 3 different entries in my projects.json to get information about github issues, PRs, and the repo itself ([github:issue, github:pull, github:repo]). However, when I just add one entry ([github]), I get information about issues and PRs (is that expected ?) but nothing about the repo itself. Could you please clarify and help ? Do I need to add another entry for each project with the [github:repo] tag ?

My ```projects.json``` looks something like this:

```
{
   "lalalala":{
      "meta":{
         "title":"lalalalala_title"
      },
      "git":[
         "https://github.com/something.git"
      ],
      "github": [
         "https://github.com/something"
      ]
   },
```

And my ```setup-secured.cfg``` looks something like this (same as default one but with the section below uncommented):
```
[github]
api-token = mysupertoken
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched
```

Thank you again for this great project !

**Comment by krokoko** [comment]
Testing different configurations but seems I can't get it to work, could someone please help ? Thank you !

**Comment by zhquan** [comment]
Hi @krokoko 

Thank you for using it.

There are several categories for [github](https://github.com/chaoss/grimoirelab-sirmordred#github-) and each one fetches different information.

- [issues](https://github.com/chaoss/grimoirelab-sirmordred#issue) (default):
  -  issue and pull requests
- [pull requests](https://github.com/chaoss/grimoirelab-sirmordred#pull-request):
  -  pull requests
- [repo](https://github.com/chaoss/grimoirelab-sirmordred#repo):
  - forks, stars, and subscribers

Remember that for GitHub a pull request is also an issue, which is why you can see pull requests in the category issue. The category `pull_request` fetch only pull requests with some specific information that is not allowed in the issue category.

But if you also want commit information you will need [git](https://github.com/chaoss/grimoirelab-sirmordred#git-)

I think this is your configuration:

- projects.json
```
{
   "lalalala":{
      "meta":{
         "title":"lalalalala_title"
      },
      "git":[
         "https://github.com/something.git"
      ],
      "github": [
         "https://github.com/something"
      ],
      "github:repo": [
         "https://github.com/something"
      ]
   },
```

- setup.cfg
```
[git]
raw_index = git_raw
enriched_index = git_enriched
latest-items = true

[github]
api-token = mysupertoken
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched

[github:repo]
api-token = mysupertoken
raw_index = github-repo_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github-repo_demo_enriched
category = repository
```

I hope it helps you.

**Comment by krokoko** [comment]
Hi @zhquan ! Thanks ! What you posted is exactly the configuration I have, however I don't see any information related to the repo (forks,stars,...). Should I have a new item in the menu ? or the data will appear in an existing tab ?

setup-secured.cfg
```
...
[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
api-token = muspertoken
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched

[github:repo]
raw_index = github-repo_raw
enriched_index = github-repo_enriched
api-token = mysupertoken
category = repository
sleep-for-rate = true
no-archive = true
studies = [enrich_demography:github]

## studies based on enriched indexes

[enrich_demography:git]

[enrich_demography:github]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash
```

and projects.json is the same as the one you posted

**Comment by zhquan** [comment]
If you want github:repo dashboard and menu you have to add `github-repos = true` in the `panels` section more info at https://github.com/chaoss/grimoirelab-sirmordred#panels

**Comment by krokoko** [comment]
There you go ! Thanks, it works indeed. It is not mentioned in https://github.com/chaoss/grimoirelab-sirmordred#repo while mentioned for other sources, I guess that's where the confusion comes from
