### ISSUE TITLE
Get the percent of questions with a "correct" answer marked in Askbot forums

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#55]
In [Askbot](https://askbot.com/) Q&A (questions and answers) forums is possible to mark an answer as `correct`.

That info seems to missing in current [askbot data schema](https://github.com/grimoirelab/panels/blob/master/schema/askbot.csv) produced by GrimoireLab.

**Comment by sduenas** [comment]
Perceval now includes this field (see chaoss/grimoirelab-perceval#333 and chaoss/grimoirelab-perceval@6a087de8ea176d4bdf692678102c305b17959cf5).

The next step is add it to the enriched items generated by GELK.

**Comment by valeriocos** [comment]
GELK now includes this information https://github.com/chaoss/grimoirelab-elk/pull/249
