### ISSUE TITLE
"Kibana server is not ready yet" on localhost:5601/

### ISSUE THREAD

**Issue by StringCH** [chaoss/grimoirelab#551]
I'm running the default GrimoireLabs setup with docker-compose on my laptop. If I visit localhost:5601 I get the messeage "Kibana server is not ready yet" in my browser even after one hour waiting. What can I do to fix this problem?

**Comment by zhquan** [comment]
Hi @StringCH 

Probably your ElasticSearch instance is not ready. Check the logs and [here](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#low-virtual-memory-) a list of some common problems.

I guess you are using this [docker-compose](https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml).

I hope it helps you.

**Comment by StringCH** [comment]
Hi @zhquan 

if I try to run Docker Compose up kibiter and hatstall container are running and also keep running but mordred container and elasticsearch container start running and then go to status "exidet" after a really short time. I get the following logs with docker compose up:

` Running 5/0
 - Container docker-compose-elasticsearch-1  Created                                                               0.0s
 - Container docker-compose-mariadb-1        Created                                                               0.0s
 - Container docker-compose-kibiter-1        Running                                                               0.0s
 - Container docker-compose-hatstall-1       Created                                                               0.0s
 - Container docker-compose-mordred-1        Created                                                               0.0s
Attaching to docker-compose-elasticsearch-1, docker-compose-hatstall-1, docker-compose-kibiter-1, docker-compose-mariadb-1, docker-compose-mordred-1
docker-compose-mariadb-1        | 2022-10-26 08:55:15+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.10+maria~ubu2004 started.
docker-compose-mariadb-1        | 2022-10-26 08:55:16+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
docker-compose-mariadb-1        | 2022-10-26 08:55:16+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.10+maria~ubu2004 started.
docker-compose-elasticsearch-1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
docker-compose-hatstall-1       | Running Hatstall
docker-compose-mariadb-1        | 2022-10-26 08:55:17+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
docker-compose-mariadb-1        | 2022-10-26  8:55:17 0 [Note] mariadbd (server 10.6.10-MariaDB-1:10.6.10+maria~ubu2004) starting as process 1 ...
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:17Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:17Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-hatstall-1       | cp: cannot create regular file 'grimoirelab-hatstall/django-hatstall/shdb.cfg': Permission denied
docker-compose-mariadb-1        | 2022-10-26  8:55:17 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
docker-compose-mariadb-1        | 2022-10-26  8:55:17 0 [Note] InnoDB: Number of pools: 1
docker-compose-mariadb-1        | 2022-10-26  8:55:17 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
docker-compose-mariadb-1        | 2022-10-26  8:55:17 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
docker-compose-hatstall-1       | Site 000-default already disabled
docker-compose-hatstall-1       | Site apache-hatstall already enabled
docker-compose-hatstall-1       | Considering dependency setenvif for ssl:
docker-compose-hatstall-1       | Module setenvif already enabled
docker-compose-hatstall-1       | Considering dependency mime for ssl:
docker-compose-hatstall-1       | Module mime already enabled
docker-compose-hatstall-1       | Considering dependency socache_shmcb for ssl:
docker-compose-hatstall-1       | Module socache_shmcb already enabled
docker-compose-hatstall-1       | Module ssl already enabled
docker-compose-hatstall-1       | sed: couldn't open temporary file /home/grimoirelab/grimoirelab-hatstall/django-hatstall/django_hatstall/sedHcCwps: Permission denied
docker-compose-hatstall-1       | Traceback (most recent call last):
docker-compose-hatstall-1       |   File "./config_deployment.py", line 42, in <module>
docker-compose-hatstall-1       |     with open(settings_file, "w") as f:
docker-compose-hatstall-1       | PermissionError: [Errno 13] Permission denied: 'django_hatstall/settings.py'
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: Using Linux native AIO
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: Completed initialization of buffer pool
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=42522,42522
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: 128 rollback segments are active.
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: Creating shared tablespace for temporary tables
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: 10.6.10 started; log sequence number 42534; transaction id 14
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] InnoDB: Buffer pool(s) load completed at 221026  8:55:18
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] Plugin 'FEEDBACK' is disabled.
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] Server socket created on IP: '0.0.0.0'.
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] Server socket created on IP: '::'.
docker-compose-mariadb-1        | 2022-10-26  8:55:18 0 [Note] mariadbd: ready for connections.
docker-compose-mariadb-1        | Version: '10.6.10-MariaDB-1:10.6.10+maria~ubu2004'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
docker-compose-hatstall-1       | No changes detected
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:19Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:19Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-hatstall-1       | Operations to perform:
docker-compose-hatstall-1       |   Apply all migrations: admin, auth, contenttypes, sessions
docker-compose-hatstall-1       | Running migrations:
docker-compose-hatstall-1       |   No migrations to apply.
docker-compose-hatstall-1       |
docker-compose-hatstall-1       | 0 static files copied to '/home/grimoirelab/grimoirelab-hatstall/django-hatstall/static', 163 unmodified.
docker-compose-hatstall-1       | User for django admin already exists, let's update the password
docker-compose-hatstall-1       | Password for django admin user updated
docker-compose-mordred-1        | Traceback (most recent call last):
docker-compose-mordred-1        |   File "/usr/local/bin/sirmordred", line 8, in <module>
docker-compose-mordred-1        |     sys.exit(main())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 65, in main
docker-compose-mordred-1        |     logger = setup_logs(logs_dir, debug_mode)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 93, in setup_logs
docker-compose-mordred-1        |     fh = logging.FileHandler(fh_filepath)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
docker-compose-mordred-1        |     StreamHandler.__init__(self, self._open())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
docker-compose-mordred-1        |     return open(self.baseFilename, self.mode, encoding=self.encoding)
docker-compose-mordred-1        | PermissionError: [Errno 13] Permission denied: '/home/grimoire/logs/all.log'
docker-compose-hatstall-1       | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.6. Set the 'ServerName' directive globally to suppress this message
docker-compose-hatstall-1       | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.6. Set the 'ServerName' directive globally to suppress this message
docker-compose-hatstall-1       | [Wed Oct 26 08:55:21.877551 2022] [core:warn] [pid 55:tid 140076525937792] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
docker-compose-hatstall-1       | [Wed Oct 26 08:55:21.878744 2022] [wsgi:warn] [pid 55:tid 140076525937792] (98)Address already in use: mod_wsgi (pid=55): Removing stale unix domain socket '/var/run/apache2/wsgi.55.0.1.sock'.
docker-compose-hatstall-1       | [Wed Oct 26 08:55:21.880561 2022] [mpm_event:notice] [pid 55:tid 140076525937792] AH00489: Apache/2.4.38 (Debian) OpenSSL/1.1.1d mod_wsgi/4.6.5 Python/3.7 configured -- resuming normal operations
docker-compose-hatstall-1       | [Wed Oct 26 08:55:21.880611 2022] [core:notice] [pid 55:tid 140076525937792] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:22Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:22Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-mordred-1 exited with code 1
docker-compose-elasticsearch-1  | [2022-10-26T08:55:24,095][INFO ][o.e.e.NodeEnvironment    ] [a4-y0OR] using [1] data paths, mounts [[/ (overlay)]], net usable_space [225.3gb], net total_space [250.9gb], types [overlay]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:24,100][INFO ][o.e.e.NodeEnvironment    ] [a4-y0OR] heap size [1.9gb], compressed ordinary object pointers [true]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:24,104][INFO ][o.e.n.Node               ] [a4-y0OR] node name derived from node ID [a4-y0OR2TIOGB0g7DHCMKQ]; set [node.name] to override
docker-compose-elasticsearch-1  | [2022-10-26T08:55:24,105][INFO ][o.e.n.Node               ] [a4-y0OR] version[6.8.6], pid[1], build[oss/docker/3d9f765/2019-12-13T17:11:52.013738Z], OS[Linux/5.10.102.1-microsoft-standard-WSL2/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.1/13.0.1+9]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:24,105][INFO ][o.e.n.Node               ] [a4-y0OR] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-17196398379234112446, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Xms2g, -Xmx2g, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=oss, -Des.distribution.type=docker]
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:24Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:24Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,902][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [aggs-matrix-stats]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,902][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [analysis-common]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,902][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [ingest-common]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,902][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [ingest-geoip]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,903][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [ingest-user-agent]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,903][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [lang-expression]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,903][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [lang-mustache]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,903][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [lang-painless]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,903][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [mapper-extras]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,903][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [parent-join]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,903][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [percolator]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,903][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [rank-eval]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,903][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [reindex]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,904][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [repository-url]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,904][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [transport-netty4]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,904][INFO ][o.e.p.PluginsService     ] [a4-y0OR] loaded module [tribe]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:26,904][INFO ][o.e.p.PluginsService     ] [a4-y0OR] no plugins loaded
docker-compose-mordred-1        | Traceback (most recent call last):
docker-compose-mordred-1        |   File "/usr/local/bin/sirmordred", line 8, in <module>
docker-compose-mordred-1        |     sys.exit(main())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 65, in main
docker-compose-mordred-1        |     logger = setup_logs(logs_dir, debug_mode)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 93, in setup_logs
docker-compose-mordred-1        |     fh = logging.FileHandler(fh_filepath)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
docker-compose-mordred-1        |     StreamHandler.__init__(self, self._open())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
docker-compose-mordred-1        |     return open(self.baseFilename, self.mode, encoding=self.encoding)
docker-compose-mordred-1        | PermissionError: [Errno 13] Permission denied: '/home/grimoire/logs/all.log'
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:27Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:27Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-mordred-1 exited with code 1
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:29Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:29Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-elasticsearch-1  | [2022-10-26T08:55:31,867][INFO ][o.e.d.DiscoveryModule    ] [a4-y0OR] using discovery type [zen] and host providers [settings]
docker-compose-mordred-1        | Traceback (most recent call last):
docker-compose-mordred-1        |   File "/usr/local/bin/sirmordred", line 8, in <module>
docker-compose-mordred-1        |     sys.exit(main())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 65, in main
docker-compose-mordred-1        |     logger = setup_logs(logs_dir, debug_mode)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 93, in setup_logs
docker-compose-mordred-1        |     fh = logging.FileHandler(fh_filepath)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
docker-compose-mordred-1        |     StreamHandler.__init__(self, self._open())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
docker-compose-mordred-1        |     return open(self.baseFilename, self.mode, encoding=self.encoding)
docker-compose-mordred-1        | PermissionError: [Errno 13] Permission denied: '/home/grimoire/logs/all.log'
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:32Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:32Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-elasticsearch-1  | [2022-10-26T08:55:32,435][INFO ][o.e.n.Node               ] [a4-y0OR] initialized
docker-compose-elasticsearch-1  | [2022-10-26T08:55:32,435][INFO ][o.e.n.Node               ] [a4-y0OR] starting ...
docker-compose-mordred-1 exited with code 1
docker-compose-elasticsearch-1  | [2022-10-26T08:55:32,670][INFO ][o.e.t.TransportService   ] [a4-y0OR] publish_address {172.19.0.4:9300}, bound_addresses {0.0.0.0:9300}
docker-compose-elasticsearch-1  | [2022-10-26T08:55:32,688][INFO ][o.e.b.BootstrapChecks    ] [a4-y0OR] bound or publishing to a non-loopback address, enforcing bootstrap checks
docker-compose-elasticsearch-1  | ERROR: [1] bootstrap checks failed
docker-compose-elasticsearch-1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
docker-compose-elasticsearch-1  | [2022-10-26T08:55:32,700][INFO ][o.e.n.Node               ] [a4-y0OR] stopping ...
docker-compose-elasticsearch-1  | [2022-10-26T08:55:32,735][INFO ][o.e.n.Node               ] [a4-y0OR] stopped
docker-compose-elasticsearch-1  | [2022-10-26T08:55:32,735][INFO ][o.e.n.Node               ] [a4-y0OR] closing ...
docker-compose-elasticsearch-1  | [2022-10-26T08:55:32,749][INFO ][o.e.n.Node               ] [a4-y0OR] closed
docker-compose-elasticsearch-1 exited with code 78
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:34Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:35Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-mordred-1        | Traceback (most recent call last):
docker-compose-mordred-1        |   File "/usr/local/bin/sirmordred", line 8, in <module>
docker-compose-mordred-1        |     sys.exit(main())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 65, in main
docker-compose-mordred-1        |     logger = setup_logs(logs_dir, debug_mode)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 93, in setup_logs
docker-compose-mordred-1        |     fh = logging.FileHandler(fh_filepath)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
docker-compose-mordred-1        |     StreamHandler.__init__(self, self._open())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
docker-compose-mordred-1        |     return open(self.baseFilename, self.mode, encoding=self.encoding)
docker-compose-mordred-1        | PermissionError: [Errno 13] Permission denied: '/home/grimoire/logs/all.log'
docker-compose-mordred-1 exited with code 1
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:37Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:37Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-mordred-1        | Traceback (most recent call last):
docker-compose-mordred-1        |   File "/usr/local/bin/sirmordred", line 8, in <module>
docker-compose-mordred-1        |     sys.exit(main())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 65, in main
docker-compose-mordred-1        |     logger = setup_logs(logs_dir, debug_mode)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 93, in setup_logs
docker-compose-mordred-1        |     fh = logging.FileHandler(fh_filepath)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
docker-compose-mordred-1        |     StreamHandler.__init__(self, self._open())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
docker-compose-mordred-1        |     return open(self.baseFilename, self.mode, encoding=self.encoding)
docker-compose-mordred-1        | PermissionError: [Errno 13] Permission denied: '/home/grimoire/logs/all.log'
docker-compose-mordred-1 exited with code 1
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:40Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:40Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:42Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:42Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-mordred-1        | Traceback (most recent call last):
docker-compose-mordred-1        |   File "/usr/local/bin/sirmordred", line 8, in <module>
docker-compose-mordred-1        |     sys.exit(main())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 65, in main
docker-compose-mordred-1        |     logger = setup_logs(logs_dir, debug_mode)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/site-packages/sirmordred/bin/sirmordred.py", line 93, in setup_logs
docker-compose-mordred-1        |     fh = logging.FileHandler(fh_filepath)
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
docker-compose-mordred-1        |     StreamHandler.__init__(self, self._open())
docker-compose-mordred-1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
docker-compose-mordred-1        |     return open(self.baseFilename, self.mode, encoding=self.encoding)
docker-compose-mordred-1        | PermissionError: [Errno 13] Permission denied: '/home/grimoire/logs/all.log'
docker-compose-mordred-1 exited with code 1
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:45Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:45Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
docker-compose-kibiter-1        | {"type":"log","@timestamp":"2022-10-26T08:55:47Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}`

PS: The Troubleshooting-List did not help.

**Comment by zhquan** [comment]
> docker-compose-elasticsearch-1 | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

Try this https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#low-virtual-memory-

> docker-compose-mordred-1 | PermissionError: [Errno 13] Permission denied: '/home/grimoire/logs/all.log'
> docker-compose-mordred-1 exited with code 1

Try this https://github.com/chaoss/grimoirelab/issues/202#issuecomment-790018433

I hope it helps you

**Comment by spriya-m** [comment]
I faced the same issue. Setting virtual memory to 2GB solved the issue.
