### ISSUE TITLE
Get the percent of questions with a reply (comment or answer) of any kind

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#56]
In mailing lists and Q&A forums there are some questions answered or commented and other without any answer of any kind.

Questions might be marked as "answered" and with the date when they have been answered the first time and the last time (so there could be a chance to get evolution over time of attention to questions).

**Comment by jsmanrique** [comment]
Let's focus on Q&A forums: Askbot, Stackexchange, and maybe Discourse

**Comment by dicortazar** [comment]
Already done in the mentioned data sources. For each of those there is a new pie chart that gives the pieces of information of net and relative number of answered and unanswered questions.

Then, depending on the data source, there may be another pie chart stating the number of accepted answers. These are those questions with a 'proven' solution and accepted by the community or the owner of the question.

**Comment by dicortazar** [comment]
This is working for Kibana 5 and Kibana 6 panels.
