### ISSUE TITLE
`GitLab` - Can Commits Be Ingested?

### ISSUE THREAD

**Issue by loganknecht** [chaoss/grimoirelab#560]
# Question

This is a quick question

I'm looking to generate some high level statistics about lines of code added/removed for merge requests.

In `GitLab`'s documentation they state that the `Merge Request` endpoints don't have that information, but that the `Commit` endpoints do.
- https://docs.gitlab.com/ee/api/merge_requests.html

Is there a way to get `Grimoire Lab`/`Perceval` to scrape the `Commit` endpoints so I can generate dashboards around this?
 - https://docs.gitlab.com/ee/api/commits.html

Additionally, is there a way to do that for `Gerrit` as well?

# Gratitude

As always - thank you so much for everything. Grimoire Lab has really helped establish some really interesting insights into our organization. I personally really appreciate everything you've all enabled.

**Comment by zhquan** [comment]
Hi @loganknecht,

You can use [git backend](https://github.com/chaoss/grimoirelab-sirmordred#git-) with `enrich_areas_of_code:git` study.

i.e.
- projects.json: You have to add all repositories as `gitlab` backend.
  - For this repo https://review.opendev.org/admin/repos/All-Projects,general
    - `Download` -> `Clone`  -> copy the URL
```
{
    "Chaoss": {
        "git": [
            "https://review.opendev.org/All-Projects"
        ]
    }
}
```
- setup.cfg
```
[git]
raw_index = git_raw
enriched_index = git_enriched
latest-items = true
studies = [enrich_areas_of_code:git]

[enrich_areas_of_code:git]
in_index = git_raw
out_index = git-aoc_enriched
```

I hope it helps you.

**Comment by loganknecht** [comment]
Closing as done.

Anyone else who needs to do this should also see #562 for how to do multiple `git` index/configuration sections if needed.
