### ISSUE TITLE
How Do You Use Multiple `[git]` Sections?

### ISSUE THREAD

**Issue by loganknecht** [chaoss/grimoirelab#562]
Hello!

I saw a wonderful answer in issue #536 regarding how to make multiple sections and that you have to make sure that the `setup.cfg` and `projects.json` both match.

https://github.com/chaoss/grimoirelab/issues/536#issuecomment-1269535616

However when I try this configuration

```
# ...

[gitlab-commits]
category = commit
raw_index = gitlab-areas-of-code_raw
enriched_index = gitlab-areas-of-code_enriched
latest-items = true
studies = [enrich_areas_of_code:gitlab_commits, enrich_git_branches:gitlab_commits, enrich_demography:gitlab_commits, enrich_onion:gitlab_commits]

# ...
```

```json
{
    "ORGANIZATION_NAME": {
        "meta": {
            "title": "TITLE"
        },
        "gitlab-commits": [
            // ...
            "https://USERNAME:TOKEN@REPOSITORY_URL",
            // ...
        ]
    }
}
```

I get this output when spinning up the `mordred` container
```bash
docker-compose-mordred-1   | Error while consuming configuration: ('Wrong section:', 'gitlab-commits')
docker-compose-hatstall-1  | Enabling site apache-hatstall.
docker-compose-hatstall-1  | To activate the new configuration, you need to run:
docker-compose-hatstall-1  |   service apache2 reload
docker-compose-mordred-1 exited with code 1
```

------------------------------

I was under the impression that because I used the `category = commit` it should have picked up the right configurations.

Am I misunderstanding how these pieces are connected or does the `git` section not support the ability to be arbitrarily named?

**Comment by zhquan** [comment]
Hi @loganknecht 

The name of the section is wrong. For git, the first part must be `git` and the second as you wish. `[git:tag]`

Try again using these:
- setup.cfg
```
[git:gitlab]
category = commit
raw_index = gitlab-areas-of-code_raw
enriched_index = gitlab-areas-of-code_enriched
latest-items = true
studies = [enrich_areas_of_code:gitlab_commits, enrich_git_branches:gitlab_commits, enrich_demography:gitlab_commits, enrich_onion:gitlab_commits]
```
- projects.json
```
{
    "ORGANIZATION_NAME": {
        "meta": {
            "title": "TITLE"
        },
        "git:gitlab": [
            // ...
            "https://USERNAME:TOKEN@REPOSITORY_URL",
            // ...
        ]
    }
}
```

**Comment by loganknecht** [comment]
@zhquan - Thank you so much!

Can confirm this was the fix.

Closing as `solved`
