### ISSUE TITLE
Stats on Gerrit reviews

### ISSUE THREAD

**Issue by rpaik** [chaoss/grimoirelab#58]
I'd like to get some data on people's contribution for code reviews.  For example, I'd like to see a table with reviewer's names, number of reviews, number of projects where reviews were contributed, etc.

**Comment by jgbarah** [comment]
Commented in chaoss/metrics#49.

**Comment by dicortazar** [comment]
Hi @rpaik,

We've been working on defining a new index for Gerrit having in mind these requirements.

The new schema would be the following:

|name| type| description|
|------|------|------|
 |is_patchset| long| 1 if the item is a patchset.|
 |is_approval| long| 1 if the item is an approval|
 |is_patchset_comment| long| 1 if the item is a comment|
 |is_changeset| long| 1 if the item is a code review process|
 |type| keyword| "approval or  patchset or  changeset or  comment"|
 |author_bot| boolean| True if the given author is identified as a bot|
 |author_domain| keyword| Domain associated to the author in sortinghat profile|
 |author_id| keyword| Author Id from sortinghat|
 |author_name| keyword| Author name|
 |author_org_name| keyword| Organization the author belongs to|
 |author_user_name| keyword| Author user name|
 |author_uuid| keyword| Author unique identifier from sortinghat|
 |changeset_branch| keyword| Development branch created for the corresponding changeset|
 |changeset_closed| date| Closing date of the corresponding changeset|
 |changeset_domain| keyword| Domain of the author (not coming from SortingHat)|
 |changeset_num_patchsets| long| Number of patchsets/iterations involved in the changeset|
 |changeset_status| keyword| "Gerrit status of the corresponding changeset such as Abandoned,  Merged or Open. The actual value depends on the instance of Gerrit."|
 |changeset_timeopen| double| Time that the changeset has been opened in days|
 |grimoire_creation_date| date| "Item creation date (patchset|  approval|  patchset comment or code review)."|
 |is_gerrit_review| long| Field containing '1' that allows to sum fields when concatenating with other indexes|
 |metadata__enriched_on| date| Date when the item was enriched|
 |metadata__gelk_backend_name| keyword| Grimoire-ELK backend name|
 |metadata__gelk_version| keyword| Grimoire-ELK version|
 |metadata__timestamp| date| Date when the item was stored in RAW index|
 |metadata__updated_on| date| Date when the item was updated in its originaldata source|
 |number| keyword| Gerrit changeset unique identifier|
 |ocean-unique-id| keyword| Unique identifier for all of the datasets in the information lake|
 |origin| keyword| Original URL where the changeset was retrieved|
 |patchset_author_bot| boolean| True if the given author is identified as a bot|
 |patchset_author_domain| keyword| Domain associated to the author in sortinghat profile|
 |patchset_author_id| keyword| Author Id from sortinghat|
 |patchset_author_name| keyword| Author name|
 |patchset_author_org_name| keyword| Organization the author belongs to|
 |patchset_author_user_name| keyword| Author user name|
 |patchset_author_uuid| keyword| Author unique identifier from sortinghat|
 |patchset_domain| keyword| Domain associated to the author in the patchset (not coming from SortingHat)|
 |patchset_githash| keyword| Hash of the commit included in the corresponding changeset|
 |patchset_number| long| Patchset identifier|
 |project_1| keyword| Second level project hierarchy (typically not used in Gerrit)|
 |project| keyword| First level project hierarchy|
 |repository| keyword| Repository (project in Gerrit terminology) where the changeset is sent|
 |summary_analyzed| text| Text summary added by the developer. This is typically the commit message. This field is tokenized for searching purposes|
 |summary| keyword| Text summary added by the developer. This is typically the commit message|
 |tag| keyword| Perceval tag|
 |url| keyword| Full URL pointing to the changesetFull URL pointing to the changeset|
 |uuid| keyword| Perceval UUID|


This new index is as the original Gerrit one, but new events are added. These are the patchset sending action, the approval process (either automatically verified by CI or code-reviewed by a human being, and the comments left in its section.

For each of those new events, the author is retrieved and the specific action (e.g.: +1 in a code review process).

With this in mind, I'd say we would be covering the specific metrics you're talking about. And we may have some others that may help to understand how fair the code review is among organizations, or certain developers.

Comments or concerns? :)

Regards,
Daniel.

**Comment by alpgarcia** [comment]
This is solved by:
* https://github.com/chaoss/grimoirelab-elk/pull/616
* https://github.com/chaoss/grimoirelab-sigils/pull/358
* https://github.com/chaoss/grimoirelab-sirmordred/pull/297
