### ISSUE TITLE
Need help to remove GitHub Issues Menu

### ISSUE THREAD

**Issue by maltif** [chaoss/grimoirelab#583]
Hello,

I want to remove **GitHub Issues** menu and submenu `Issues`  of **GitHub Comments** menu from Kibana UI. Please refer to the attached screenshots for clarification. Could you kindly guide me on the steps to accomplish this?

![image (10)](https://user-images.githubusercontent.com/100792545/222205819-425cdc92-29f3-4661-8cf0-e132c7a82b39.png)

![image (11)](https://user-images.githubusercontent.com/100792545/222205915-27055f6e-10f5-4cf7-9912-4f7a1bd13c2e.png)

Thank you for your help.

**Comment by zhquan** [comment]
Hi @maltif 

First, you must get your current menu and copy the `metadashboard` content.

![image](https://user-images.githubusercontent.com/5637233/222487778-8705254d-94aa-468f-9e8f-c4f8382e13a9.png)

Modify the content (add or remove the sections) and upload the content.
```
PUT .kibana/_doc/metadashboard
{
  "metadashboard" : [...]
}
```

I hope it helps you

**Comment by maltif** [comment]
tried and worked flawlessly. Thank you very much, @zhquan

**Comment by maltif** [comment]
@zhquan, I followed the steps you provided to remove the GitHub Issues Menu, and it worked well initially. However, after a while , the Issue Menu reappeared automatically, and I am unsure why. It appears that the changes I made using `PUT .kibana/_doc/metadashboard` API,  are not persistent.

Would restarting the `mordred_1` Docker container restoring the previous state of the GitHub Issues Menu? Could you please provide your input on how to make these changes permanent even after restarting the Grimoire Docker containers? 

I would greatly appreciate your assistance in this matter."

**Comment by zhquan** [comment]
@maltif on your `setup.cfg` you have to deactivate `panels = false` in the `phases` section, when the `panels` is enabled it will overwrite the menu. So deactivate `panels` and restart the Mordred container

**Comment by maltif** [comment]
Thank you, @zhquan. After deactivating `panels = false` in the `phases` section of `setup.cfg` as mentioned earlier, it seems that the changes are now persistent. I will get in touch if any further issues arise.

Thank you very much for your time and assistance.
