### ISSUE TITLE
issue with using docker run

### ISSUE THREAD

**Issue by forwhat461** [chaoss/grimoirelab#591]
```
docker run --net=host \ 
    -v $(pwd)/default-grimoirelab-settings/projects.json:/home/grimoire/conf/projects.json \
    -v $(pwd)/default-grimoirelab-settings/setup-docker.cfg:/home/grimoire/conf/setup.cfg \
    -t grimoirelab/grimoirelab
```
doesn't seem to using any image to create a container.  is this command wrong?
and a lot of errors when i try setup.py  ..... shouldn't it be runing directly?

**Comment by sduenas** [comment]
Would you mind to try with docker compose? I'm afraid there's something missing there. At least, the image of other grimoirelab component (sortinghat) should be running before grimoirelab runs.

You can find more info about how to run docker compose [here](https://github.com/chaoss/grimoirelab/tree/master/docker-compose)

**Comment by forwhat461** [comment]
alright
