### ISSUE TITLE
Mordred error when running

### ISSUE THREAD

**Issue by jaidyn-vankirk** [chaoss/grimoirelab#600]
Hi, I have been searching through the troubleshooting page and issue pages for a while now and cannot seem to find a solution to my issue. I am trying to run Grimoire on my Mac, and the dashboard never opens. I have not changed anything in the setup-docker and have increased the resources in Docker that should allow it to run. When looking at the output, most of it seems to be Mordred related. In the beginning I was getting a requests.exceptions.RetryError: HTTPConnectionPool(host='kibiter', port=5601): Max retries exceeded with url: /api/kibana/settings/defaultIndex (Caused by ResponseError('too many 503 error responses')), but it seemed later this stopped and was replaced with the output below. I have no idea what is wrong and would appreciate any advice.
<img width="1440" alt="Screenshot 2023-06-28 at 11 30 05 PM" src="https://github.com/chaoss/grimoirelab/assets/76024106/66246d7d-c7bc-4093-8558-b70d305b2043">

**Comment by zhquan** [comment]
Hi @jaidyn-vankirk 

> requests.exceptions.RetryError: HTTPConnectionPool(host='kibiter', port=5601): Max retries exceeded with url: /api/kibana/settings/defaultIndex

This error is related to OpenSearch or ElasticSearch > 6.8.6 , the panel section only works for ElasticSearch and Kibana `6.8.6`.

There is no error on the image. Could you make some checks if your indexes and aliases are created correctly?
1. `GET _cat/indices`
2. `GET _cat/aliases`

I hope it helps you

**Comment by zhquan** [comment]
Ok, no problem :)

I guess that you are using the default settings.
1. Go to http://localhost:5601
2. On the top left click on settings (three horizontal stripes icon)
3. Management -> Dev Tools
4. Copy the commands `GET _cat/indices` and  `GET _cat/aliases`
5. Click on the play button

Or you can use CURL. If you did not change the configuration try these:
- USER: admin
- PASS: admin
```
curl -k -u USER:PASS https://localhost:9200/_cat/indices
curl -k -u USER:PASS https://localhost:9200/_cat/aliases
```

**Comment by jaidyn-vankirk** [comment]
Thanks, I ended up choosing the second option and received this:

<img width="1440" alt="Screenshot 2023-06-29 at 10 17 53 AM" src="https://github.com/chaoss/grimoirelab/assets/76024106/8b5d4433-5732-4d02-9175-9b0292fbad2d">

I also have not changed anything from the default files given.

**Comment by zhquan** [comment]
Could you try again but replace USER and PASS with admin

```
curl -k -u admin:admin https://localhost:9200/_cat/indices
curl -k -u admin:admin https://localhost:9200/_cat/aliases
```

**Comment by jaidyn-vankirk** [comment]
<img width="1438" alt="Screenshot 2023-06-29 at 1 48 34 PM" src="https://github.com/chaoss/grimoirelab/assets/76024106/3a0c5ee6-780a-49aa-86e6-04a550ce2ff8">

I received the same error when I ran the new lines of code.

**Comment by zhquan** [comment]
My bad sorry, could you try again, but without credentials and HTTP instead of HTTPS?

```
curl -k http://localhost:9200/_cat/indices
curl -k http://localhost:9200/_cat/aliases
```

Also, check if you can access the dashboard http://localhost:5601/ ?

**Comment by jaidyn-vankirk** [comment]
<img width="656" alt="Screenshot 2023-06-30 at 8 50 35 AM" src="https://github.com/chaoss/grimoirelab/assets/76024106/d96ca48e-e17e-4edb-94dd-bc413c6e3133">

Above is what it said in the terminal, and I have never had access to the dashboard.

**Comment by zhquan** [comment]
Your indexes and aliases are correct.

Could you run `docker ps -a` and check that the `kibiter` and `nignx` are running? If I remember well the nginx serves the dashboard at http://localhost

**Comment by jaidyn-vankirk** [comment]
Here is what I saw in the console:
<img width="1440" alt="Screenshot 2023-07-05 at 1 40 29 PM" src="https://github.com/chaoss/grimoirelab/assets/76024106/b51dbd2b-3691-4f91-9cd1-227737065952">

When I went to http://localhost it said the local host refused to connect.

**Comment by sduenas** [comment]
It should be "https://localhost:5601".

**Comment by jjmerchante** [comment]
Hi,

For the Kibiter instance it should be http://localhost:8000 or http://localhost:5601, as described [in the documentation](https://github.com/chaoss/grimoirelab/tree/master/docker-compose#getting-started-in-3-steps)

Hope it helps

**Comment by jaidyn-vankirk** [comment]
Hi, I recently downloaded Docker (only 2-3 weeks ago) but did not have the newest version downloaded. After I updated Docker, the dashboard finally opened. Thanks to everyone who tried to help me. Sorry, I did not notice this error sooner.
