### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by fioddor** [chaoss/grimoirelab#63]
Clicking at the link in https://github.com/chaoss/grimoirelab/tree/master/docs behind "grimoirelab.github.io." pointing at https://github.com/chaoss/grimoirelab/blob/master/docs/grimoirelab.github.io, a 404 page not found HTTP error is shown.

**Comment by fioddor** [comment]
I guess it shoud point to https://grimoirelab.gitbooks.io instead.

**Comment by jgbarah** [comment]
Thanks for the report. I hope #64 fixes this. Please close the issue if you feel it does.

In fact, we're transitioning from http://grimoirelab.github.io to http://chaoss.github.io/grimoirelab , and this is a side effect of that change.
