### ISSUE TITLE
kibana server is not ready yet message.

### ISSUE THREAD

**Issue by pilgrimage80** [chaoss/grimoirelab#635]
I did the installation with docker-compose according to the following document. However, when I type localhost:5601

kibana server is not ready yet message.

What is the cause of this problem ? How can I solve it ? 

https://chaoss.github.io/grimoirelab-tutorial/docs/getting-started/setup/

**Comment by jjmerchante** [comment]
Hi @pilgrimage80 

Probably your ElasticSearch instance is not ready. Check the logs of Elastic:
```
docker logs docker-compose-elasticsearch-1
```
If you see a line like:
```
elasticsearch_1  | ERROR: [1] bootstrap checks failed
elasticsearch_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```
Check this troubleshooting: https://chaoss.github.io/grimoirelab-tutorial/docs/getting-started/troubleshooting/#low-virtual-memory

I hope it helps you.

**Comment by pilgrimage80** [comment]
Problem Solved Thank you very much for your help.

Now I need to visualise data such as how much development users on our selfhosted gitlab server have done, how many repos there are, how many issues are open and how many are closed. Is there a tutorial that can do this? 


Also, the visualisations in the link below are very clean and simple, is there a chance to choose grimorirelab? 

https://insights.lfx.linuxfoundation.org/foundation/cncf

thankyou for support.

**Comment by sduenas** [comment]
If you are using ElasticSearch 6.8, you can use [kidash](https://github.com/chaoss/grimoirelab-kidash) and [sigils](https://github.com/chaoss/grimoirelab-sigils) to import predefined panels.

Even if you aren't using this version, you can check **sigils** to get an idea about what you need and how to recreate it on Kibana.

**Comment by pilgrimage80** [comment]
Where are project.json and setup.cfg files?

**Comment by sduenas** [comment]
I think this problem is resolved. Closing the issue. Feel free to open it if you find any problem related to it.
