### ISSUE TITLE
Dashboard doesn't display details.

### ISSUE THREAD

**Issue by devaniranjan** [chaoss/grimoirelab#684]
### Discussed in https://github.com/chaoss/grimoirelab/discussions/682

<div type='discussions-op-text'>

<sup>Originally posted by **devaniranjan** July 26, 2024</sup>
I am using docker-compose to create the dashboard. It works but for the organization, I can't see details. It says 'unknown'. 
![Screenshot 2024-07-26 at 10 51 09 AM](https://github.com/user-attachments/assets/dd40f2d4-2743-44d3-83e4-8db37dc17fd7)

What am I doing wrong that the repositories details are not being pulled? 

Everything else is working well and data is being pulled. I have 4 repos here but all being shown together as 'unknmown'.

**Comment by jjmerchante** [comment]
Hi @devaniranjan 

You need to open SortingHat to affiliate users with organizations. It is under the same domain with `/identities` at the end (http://localhost:8000/identities/). It won't refresh automatically, it will take a few minutes for the data to be updated in the dashboard.

**Comment by devaniranjan** [comment]
@jjmerchante Thank you. Apologies, I didn't understand the answer. I tired the 'vanilla' [default example] install using docker-compose that will install grimoirelab and it still didn't pull the details. 

![Screenshot 2024-07-29 at 9 00 38 AM](https://github.com/user-attachments/assets/253e802a-9f01-4e21-bba9-af538896aba9)

[sortinghat]
host = nginx
user = root
password = root
port = 8000
path = /identities/api/
ssl = false
database = sortinghat_db
autoprofile = [github, git]
matching = [email,name,username]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true

**Comment by jjmerchante** [comment]
Can you check that SortingHat is running? If you run `docker ps` you will get the following output:

```
$ docker ps
5a6fc2f26d32   grimoirelab/grimoirelab:latest                            "/bin/sh -c ${DEPLOY…"   3 minutes ago   Up 2 minutes (healthy)                                                                                                    docker-compose-mordred-1
0af0660ac83b   nginx:latest                                              "/docker-entrypoint.…"   3 minutes ago   Up 2 minutes (healthy)   80/tcp, 0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                docker-compose-nginx-1
fc476996d4c5   grimoirelab/sortinghat-worker:latest                      "worker-entrypoint.sh"   3 minutes ago   Up 2 minutes             9314/tcp                                                                                         docker-compose-sortinghat_worker-1
f1285f83772c   grimoirelab/sortinghat:latest                             "server-entrypoint.sh"   3 minutes ago   Up 2 minutes             9314/tcp                                                                                         docker-compose-sortinghat-1
5e14dcda7f87   bitergia/kibiter:community-v6.8.6-3                       "/docker_entrypoint.…"   3 minutes ago   Up 3 minutes             0.0.0.0:5601->5601/tcp, :::5601->5601/tcp                                                        docker-compose-kibiter-1
0f7086ecaa59   docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.6   "/usr/local/bin/dock…"   3 minutes ago   Up 3 minutes             0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 9300/tcp                                              docker-compose-elasticsearch-1
ef88ac572ea5   redis:latest                                              "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes (healthy)   6379/tcp                                                                                         docker-compose-redis-1
c9b4586a1829   mariadb:10.6                                              "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes (healthy)   3306/tcp                                                                                         docker-compose-mariadb-1

```

**Comment by sduenas** [comment]
> @jjmerchante Thank you.
> 
> Apologies, I don't quite understand.
> 
> I switched to trying the 'vanilla' [default example] install using docker-compose that will install grimoirelab and it still didn't pull the details.
> 
> ![Screenshot 2024-07-29 at 9 00 38 AM](https://private-user-images.githubusercontent.com/142247979/353143884-253e802a-9f01-4e21-bba9-af538896aba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjQ4NjcsIm5iZiI6MTcyMjMyNDU2NywicGF0aCI6Ii8xNDIyNDc5NzkvMzUzMTQzODg0LTI1M2U4MDJhLTlmMDEtNGUyMS1iYmE5LWFmNTM4ODk2YWJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwNzI5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDY1NGRhYTk5NWJjMTEyNDVhNjNjZGFhMzFjZWY1ZTMxNTBhMWI4OGU5NjczOGNjYjczYTkyMjlhOWJkZjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5bjIrTNGOZz9mJkVqBlFVOKghmBrbHaMvp8UE7AJSKM)
> 
> When I try login to http://localhost:8000/identities/
> 
> I am getting a Bad Request (400)

Try with https instead of http.

**Comment by devaniranjan** [comment]
![Screenshot 2024-07-30 at 7 38 13 AM](https://github.com/user-attachments/assets/7f17d179-38a0-41b9-9b7d-ee9a299e6e6e)

@jjmerchante - Yes, sortinghat seems to be running. 

@sduenas  - I tried using https, and that didn't work. Says localhost sent an invalid response.

**Comment by devaniranjan** [comment]
As an update - when I look at the output from executing docker-compose I see the following.

32mmariadb_1            |[0m 2024-07-30 17:06:30 205 [Warning] Aborted connection 205 to db: 'sortinghat_db' user: 'root' host: '192.168.16.6' (Got an error reading communication packets)

**Comment by sduenas** [comment]
What computer are you running the docker compose?

**Comment by devaniranjan** [comment]
@sduenas I have tried it on two different machines running Ubuntu, 22.04.4 and 22.04.1.

With the same result.

**Comment by sduenas** [comment]
Can you try to connect to the mariadb docker container and see if it works? 
```
docker exec -it docker-compose_mariadb_1 /bin/bash
```

There, run the mysql client and connect with the database
```
mysql -u root -p 
```

**Comment by devaniranjan** [comment]
Thanks @sduenas. I can connect to the Maria DB. 

![Screenshot 2024-07-31 at 9 13 56 AM](https://github.com/user-attachments/assets/52b7cc3c-996a-4361-b777-ea4447b84f9e)


Should I run a further command while in there?

**Comment by devaniranjan** [comment]
@sduenas - any guidance on what I can do next to resolve this issue? Thank you.

**Comment by sduenas** [comment]
To be honest, I'm not really sure what's going on. I found this [blog post](https://www.percona.com/blog/mysql-got-an-error-reading-communication-packet-errors/) from the people of Percona. You can give it a try and play with the mariadb settings.

Create a file for the settings and then, mounting it on the docker compose so the container can read those settings.

**Comment by devaniranjan** [comment]
Thank you @sduenas  and @jjmerchante I will give a try with the mariadb setting.
