### ISSUE TITLE
Wrong Command in GrimoireLab tutorial

### ISSUE THREAD

**Issue by apsknight** [chaoss/grimoirelab#74]
In the **Installing Manusripts** section of [GrimoireLab Tutorial](https://grimoirelab.gitbooks.io/tutorial/before-you-start/installing-grimoirelab.html), the command for verifying installation of manuscripts is

```bash
(grimoirelab) $ manuscript --help
```

instead it should be

```
(grimoirelab) $ manuscripts --help
```

**Comment by jgbarah** [comment]
Thanks!!!

I just fixed that. Please reopen if you feel it was not correctly fixed.
