### ISSUE TITLE
Add TIme to Commit Field

### ISSUE THREAD

**Issue by BenLloydPearson** [chaoss/grimoirelab#79]
One thing I have used a lot that doesn't seem to be supported in GrimoireLab is a field that provides the amount of time it takes for code to be committed upstream. This is the difference between the author_date and commit_date fields. In the past, I've done this with a scripted field in Kibana, but from my understanding this is very inefficient, and it also tends to disappear frequently after running Mordred (it seems to do something that wipes out scripted fields when I run it).

Kibana offers a basic time difference calculation, but it outputs a number of milliseconds  and needs some formatting to be made human readable. I've typically expressed this in a number of days to the nearest tenth (e.g. 14.2 days), but hours might also work.

Would it be possible to add a field for something like time_to_commit?

**Comment by jgbarah** [comment]
Hmm. Interesting. That approach would depend a lot on how commits are merged, but I see the point. It shouldn't be difficult producing that field... I´m going to open an issue in GrimoireELK (which is the module actually enriching the index), and closing this one afterwards.
