### ISSUE TITLE
Aggregated Jenkins metrics by job instead of by build

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#89]
Wouldn't it be nice having trends and metrics related with Jenkins jobs instead of builds?

For Jenkins as data source, GrimoireLab currently shows metrics related with each build:
![captura el 2018-03-15 a las 13 59 43](https://user-images.githubusercontent.com/1178305/37464697-69964bd0-2859-11e8-907d-cf9adfffedd9.png)

It would be nice having metrics related with each job, like:
* average time
* evolution of time spend on it
* success build ratio

**Comment by alpgarcia** [comment]
First version ready at: https://github.com/chaoss/grimoirelab-sigils/pull/264

New panel looks like:
![captura de pantalla de 2018-09-20 10-58-45](https://user-images.githubusercontent.com/3502941/45807690-5924dc80-bcc4-11e8-91b7-289e616698fb.png)

**Comment by jsmanrique** [comment]
I think this could be interesting for @zxiiro ;-)

**Comment by zxiiro** [comment]
Yes this would make the Jenkins dashboard a lot more useful.

Another useful addition to this would be the ability to categorize arbitrary job types based on keywords in the job. We have build types like:

* verify jobs
* merge jobs
* csit jobs
* clm jobs

etc... in OpenDaylight these types of jobs and you can tell the difference between them by the keyword in the job name. I wouldn't expect us to know all the keywords upfront so a mechanism for the community to categorize these types via publicly accessible config file would be great.

**Comment by mafesan** [comment]
Hi @zxiiro, 

We could consider this version of the panel as standard and follow this conversation via your support tracker because these keywords you mention seem to be specific for OpenDayLight. 

If you agree, we can close this ticket as this panel is now part of https://github.com/chaoss/grimoirelab-sigils repo.

Best, Miguel-Angel

**Comment by zxiiro** [comment]
Yes, thank you.

**Comment by dicortazar** [comment]
Hey I think we can close this ticket. Thanks to all of you who participated :).
