### ISSUE TITLE
Aggregate Jenkins metrics by node type

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#90]
Usually Jenkins nodes are set up dynamically with a certain configuration, and their names could be related with that configuration.

For example:
* `ubuntu1604-basebuild-4c-4g-2165`, following the pattern `<OS>-basebuild-<Cores>c-<GB RAM>g-<random>`, used by ONAP and OpenDayLight
* `lf-pod2`, following the pattern `<company>-<slave_type><number>`. Ref: [OPNFV Jenkins Slave Naming Scheme](https://wiki.opnfv.org/display/INF/Jenkins+Slave+Naming+Scheme)

Wouldn't it be nice having aggregated metrics by one of this patterns?

For example, base on the "architecture" pattern (<cores>-<RAM>) I would like to know:
* Number of builds, jobs, etc.
* Average and trends of time to build

It would help identifying efficient nodes and their characteristics.

**Comment by alpgarcia** [comment]
First version of the panel proposed at: https://github.com/chaoss/grimoirelab-sigils/pull/265

To get info about `arm` arch there are two options:
* Filtering in the table, so you get table results only for `arm*`, for instance.
* Filtering on the top search box using: `builtOn:arm*`. Then all widgets will be filtered by that.

I think this will allow to play with results to get those you are interested in.

![captura de pantalla de 2018-09-20 11-13-26](https://user-images.githubusercontent.com/3502941/45808690-b28e0b00-bcc6-11e8-9f8f-5c68471dc01d.png)

**Comment by jsmanrique** [comment]
Again, also interesting for @zxiiro

**Comment by zxiiro** [comment]
Another way to get this data is hitting the node API. (also available as xml by changing json to xml below).

https://jenkins.opendaylight.org/releng/computer/api/json?pretty=true

There's a section called "assigned labels":

```
      "assignedLabels" : [
        {
          "name" : "centos7-builder-2c-2g"
        },
        {
          "name" : "prd-centos7-builder-2c-2g-49065"
        }
```

There can be more than 1 label but at least in ODL we typically only use 1. There is always a label of the exact node name as well, imo those can be ignored.

Jobs typically trigger against a node using these label assignments.

**Comment by sduenas** [comment]
This was already fixed by https://github.com/chaoss/grimoirelab-sirmordred/pull/238 and https://github.com/chaoss/grimoirelab-elk/pull/460
