### ISSUE TITLE
Add support for Robot Framework as data source

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#91]
[Robot Framework](http://robotframework.org/) is being used by some open source projects as a a generic test automation framework for acceptance testing and acceptance test-driven development (ATDD). 

It produces some [logs and reports](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#post-processing-outputs) that can be visualized for each test:
![captura el 2018-03-15 a las 16 27 11](https://user-images.githubusercontent.com/1178305/37473050-ca5c54a0-286d-11e8-920c-7354ea738b89.png)

Wouldn't it be nice seeing the evolution overtime, trends, etc. metrics for the test ran.

**Comment by sduenas** [comment]
We're not going do work on this on the long term. I'm closing it.
