### ISSUE TITLE
Gerrit status values for patches

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab#96]
GrimorieLab groups Gerrit status for patches in MERGED (=CR+2), ABANDONED and NEW (CR-2, CR-1, CR0, CR+1) status but the enriched items miss which values were set originally.

Differentiating might be nice to cover different use cases such as:

* "This patch has not received any review / feedback at all" (CR0)
* "This patch needs improvement, follow up with the developer if they plan to improve it" (CR-1)
* "This patch needs someone with CR+2 rights to merge this patch" (CR+1).

This issue was originally opened by @aklapper in chaoss/grimoirelab-perceval#357

**Comment by aklapper** [comment]
If someone implements this then it should probably by default use `-reviewedby:self` in Gerrit to ignore patch authors who +1 their own patches.

**Comment by valeriocos** [comment]
A PR is available on ELK: https://github.com/chaoss/grimoirelab-elk/pull/679, please @sduenas @aklapper @dicortazar have a look at it

**Comment by alpgarcia** [comment]
This should be solved via https://github.com/chaoss/grimoirelab-elk/pull/679

Please @sduenas and @aklapper review it and close the issue :)

**Comment by aklapper** [comment]
I'm a bit lost I admit - is there a way to verify in some UI (e.g. using "Discover" in Grimoire), as I'm not very good when it comes to starring at Python code? :)

**Comment by aklapper** [comment]
@alpgarcia: Feel free to close, I'd say?
